(()=>{
'use strict';
const $=id=>document.getElementById(id),cfg=window.JL_CONFIG||{};
const tok=()=>window.JLSession?.getAdminToken?.()||sessionStorage.getItem('jl_admin_token')||'';
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
async function rpc(name,args){const r=await fetch(`${cfg.supabaseUrl}/rest/v1/rpc/${name}`,{method:'POST',headers:{apikey:cfg.supabaseKey,Authorization:`Bearer ${cfg.supabaseKey}`,'Content-Type':'application/json'},body:JSON.stringify(args)});const x=await r.json().catch(()=>null);if(!r.ok)throw new Error(x?.message||x?.error||`Erro ${r.status}`);return x}
function card(){if($('freeAccessAdmin'))return $('freeAccessAdmin');const root=$('adminApp');if(!root)return null;const s=document.createElement('section');s.id='freeAccessAdmin';s.className='card admin-card';s.innerHTML=`<div class="section-head"><div><p class="eyebrow">FREE · TABULEIRO</p><h2>Ludo e Dama sem aposta</h2></div><button id="freeRefresh" class="button ghost small">Atualizar</button></div><div class="admin-actions"><label class="field"><span>Valor (MZN)</span><input id="freePrice" type="number" min="0" step="0.01" value="10"></label><label class="field"><span>FREE</span><select id="freeEnabled"><option value="true">Ativo</option><option value="false">Desativado</option></select></label><button id="freeSave" class="button primary">Guardar</button></div><p class="eyebrow">PENDENTES</p><div id="freePending" class="request-list"></div><p class="eyebrow" style="margin-top:18px">JOGADORES FREE</p><div id="freeMembers" class="request-list"></div>`;root.insertBefore(s,$('ludoLiveAdmin')||root.firstChild);s.addEventListener('click',click);$('freeRefresh').onclick=load;$('freeSave').onclick=save;return s}
function render(d){$('freePrice').value=d?.settings?.price??10;$('freeEnabled').value=String(d?.settings?.enabled!==false);const p=d?.pending||[];$('freePending').innerHTML=p.length?p.map(x=>`<div class="request-row"><div><strong>${esc(x.name)}</strong><br><small>${esc(x.phone||'')}</small></div><strong>${Number(x.amount||0)} MZN</strong><div class="row-actions"><button class="button danger small" data-r="${x.id}" data-d="rejected">Rejeitar</button><button class="button success small" data-r="${x.id}" data-d="approved">Aprovar</button></div></div>`).join(''):'<div class="empty">Nenhum pedido.</div>';const m=d?.members||[];$('freeMembers').innerHTML=m.length?m.map(x=>`<div class="request-row"><div><strong>${esc(x.name)}</strong><br><small>${esc(x.phone||'')}</small></div><strong>${x.active?'ATIVO':'DESATIVADO'}</strong><div class="row-actions"><button class="button ${x.active?'danger':'success'} small" data-p="${x.player_id}" data-a="${!x.active}">${x.active?'Desativar':'Ativar'}</button></div></div>`).join(''):'<div class="empty">Nenhum jogador FREE.</div>'}
async function load(){if(!tok())return;card();try{render(await rpc('jl_admin_free_access_overview',{p_token:tok()}))}catch(e){console.warn('FREE admin',e)}}
async function save(){try{render(await rpc('jl_admin_free_access_settings',{p_token:tok(),p_price:Number($('freePrice').value||0),p_enabled:$('freeEnabled').value==='true'}))}catch(e){alert(e.message)}}
async function click(e){const r=e.target.closest('[data-r]'),p=e.target.closest('[data-p]');try{if(r)render(await rpc('jl_admin_free_access_review',{p_token:tok(),p_request_id:r.dataset.r,p_decision:r.dataset.d}));if(p)render(await rpc('jl_admin_free_access_set_player',{p_token:tok(),p_player_id:p.dataset.p,p_active:p.dataset.a==='true'}))}catch(x){alert(x.message)}}
function init(){card();load();const a=$('adminApp');if(a)new MutationObserver(()=>{if(!a.classList.contains('hidden'))load()}).observe(a,{attributes:true})}
window.addEventListener('jl-admin-session-changed',load);document.readyState==='loading'?document.addEventListener('DOMContentLoaded',init,{once:true}):init();
})();
