(()=>{'use strict';
const $=s=>document.querySelector(s);let round=null,myBet=null,raf=0,offset=0,recovering=false;
const playerToken=()=>JLSession.getPlayerToken();
function mul(){if(!round?.started_at)return 1;const e=Math.max(0,(Date.now()+offset-new Date(round.started_at).getTime())/1000);return Math.pow(1.06,e)}
function betKey(){if(!round?.id)return null;const k='jl_aviator_bet_key_'+round.id;let v=sessionStorage.getItem(k);if(!v){v=crypto.randomUUID?crypto.randomUUID():Date.now()+'-'+Math.random().toString(36).slice(2);sessionStorage.setItem(k,v)}return v}
function paint(){if(round?.status!=='FLYING')return;const m=mul();$('#multiplier').textContent=m.toFixed(2)+'×';$('#cashoutBtn').textContent=myBet?'Cash-out · '+m.toFixed(2)+'×':'Cash-out';$('#cashoutBtn').disabled=!myBet;$('.flight-area').classList.add('flying');raf=requestAnimationFrame(paint)}
async function recover(){if(recovering||!playerToken()||!round)return;recovering=true;try{const x=await JLApi.rpc('jl_aviator_player_state',{p_token:playerToken()});const bets=Array.isArray(x.bets)?x.bets:[];const active=bets.filter(b=>Number(b.round_id)===Number(round.id)&&b.status==='ACTIVE');myBet=active.length?active[active.length-1].id:null;if(myBet)$('#aviatorMessage').textContent='Aposta ativa recuperada.'}catch(_){}finally{recovering=false}}
async function state(){try{const x=await JLApi.rpc('jl_aviator_public_state');offset=new Date(x.server_time).getTime()-Date.now();const old=round?.id;round=x.round;if(!x.enabled){$('#roundState').textContent='MANUTENÇÃO';$('#betBtn').disabled=true;$('#aviatorMessage').textContent=x.maintenance_message||'Aviator em manutenção.';}if(!round)return;$('#roundState').textContent=round.status==='OPEN'?'APOSTAS ABERTAS':round.status==='FLYING'?'EM VOO':round.status;$('#betBtn').disabled=!x.enabled||round.status!=='OPEN';if(old!==round.id||!myBet)await recover();if(round.status==='CRASHED'||round.status==='SETTLED'){cancelAnimationFrame(raf);$('.flight-area').classList.remove('flying');$('#multiplier').textContent=Number(round.crash_multiplier||1).toFixed(2)+'×';$('#crashText').classList.remove('hidden');myBet=null}else $('#crashText').classList.add('hidden');if(round.visual_seed_commit)$('#proof').textContent='Prova da rodada: '+round.visual_seed_commit+(round.visual_seed_reveal?' · seed revelada: '+round.visual_seed_reveal:'');if(round.status==='FLYING'){cancelAnimationFrame(raf);paint()}}catch(e){$('#aviatorMessage').textContent=e.message}}
$('#aviatorBetForm').addEventListener('submit',async e=>{e.preventDefault();try{if(!playerToken())throw new Error('Entre na sua conta primeiro.');if(!round||round.status!=='OPEN')throw new Error('Apostas fechadas.');const r=await JLApi.rpc('jl_aviator_place_bet',{p_token:playerToken(),p_amount:Number($('#aviatorAmount').value),p_request_key:betKey()});myBet=r.bet_id;$('#aviatorMessage').textContent=r.already_processed?'Aposta já confirmada.':'Aposta aceite.';await state()}catch(e){$('#aviatorMessage').textContent=e.message}});
$('#cashoutBtn').addEventListener('click',async()=>{if(!myBet)return;const id=myBet;$('#cashoutBtn').disabled=true;try{const r=await JLApi.rpc('jl_aviator_cashout',{p_token:playerToken(),p_bet_id:id});$('#aviatorMessage').textContent='Cash-out em '+Number(r.multiplier).toFixed(2)+'× · '+Number(r.payout).toFixed(2)+' MZN';myBet=null}catch(e){$('#aviatorMessage').textContent=e.message;await recover()}});
window.addEventListener('online',()=>state());document.addEventListener('visibilitychange',()=>{if(!document.hidden)state()});
state();setInterval(state,1000)})();