(() => {
  'use strict';

  const TOKEN_KEY='jl_player_token',COLOR_KEY='jl_ludo_preferred_color',PAWN_STYLE_KEY='jl_ludo_preferred_pawn_style',SOUND_KEY='jl_ludo_sound_enabled';
  const COLORS=new Set(['red','green','yellow','blue']),PAWN_STYLES=new Set(['current','classic','video']),DICE_FACE=['?','⚀','⚁','⚂','⚃','⚄','⚅'];
  const PATH=[[6,1],[6,2],[6,3],[6,4],[6,5],[5,6],[4,6],[3,6],[2,6],[1,6],[0,6],[0,7],[0,8],[1,8],[2,8],[3,8],[4,8],[5,8],[6,9],[6,10],[6,11],[6,12],[6,13],[6,14],[7,14],[8,14],[8,13],[8,12],[8,11],[8,10],[8,9],[9,8],[10,8],[11,8],[12,8],[13,8],[14,8],[14,7],[14,6],[13,6],[12,6],[11,6],[10,6],[9,6],[8,5],[8,4],[8,3],[8,2],[8,1],[8,0],[7,0],[6,0]];
  const START={red:0,green:13,yellow:26,blue:39};
  const HOME={red:[[7,1],[7,2],[7,3],[7,4],[7,5]],green:[[1,7],[2,7],[3,7],[4,7],[5,7]],yellow:[[7,13],[7,12],[7,11],[7,10],[7,9]],blue:[[13,7],[12,7],[11,7],[10,7],[9,7]]};
  const BASE={red:[[1,1],[1,4],[4,1],[4,4]],green:[[1,10],[1,13],[4,10],[4,13]],yellow:[[10,10],[10,13],[13,10],[13,13]],blue:[[10,1],[10,4],[13,1],[13,4]]};
  const SAFE=new Set([0,8,13,21,26,34,39,47]),FINISH_CELL={red:[7,6],green:[6,7],yellow:[7,8],blue:[8,7]};
  const $=id=>document.getElementById(id);
  const ui=Object.fromEntries(['toast','statusStrip','onlineMetric','onlinePlayerCount','directMetric','directInviteCount','publicMetric','publicChallengeCount','balanceMetric','bootPanel','loggedOut','loggedOutBoard','lobby','notificationsPanel','refreshButton','refreshLobbyButton','identityBadge','accountButton','createRoomForm','createColor','createColorPicker','createPawnStyle','createPawnCount','createPlayers','createTurnSeconds','createMode','createBet','createPublic','createRoomButton','joinCodeForm','joinCode','queueForm','queuePlayers','queueMode','queueBet','queueButton','queueStatus','inviteList','publicChallengeList','room','roomLoading','roomCode','roomMeta','roomPot','copyRoomCode','leaveRoom','forfeitRoom','deadlineBar','deadlineLabel','deadlineClock','playersPanel','gamePanel','turnTitle','moveHint','turnTimer','ludoBoard','dice','soundToggle','reenterButton','pregameArea','rulesVersion','rulesSummary','rulesForm','rulesDecision','acceptRules','declineRules','invitePanel','searchPlayerForm','searchPlayer','playerSearchResults','refreshWaiting','waitingPlayers','broadcastRoom','fundingPanel','fundingText','fundButton','betProposalForm','stakeProposalAmount','chatPanel','chatMessages','chatForm','chatInput','micButton','muteOpponent','remoteAudio','resultPanel','resultTitle','resultPayouts','rematchForm','rematchBet','rematchTurn','rematchMode','rematchPawns','rematchDice','rematchColor','authModal','authTitle','closeAuth','loginTab','registerTab','loginForm','registerForm','loginPhone','loginPin','registerName','registerPhone','registerPin','registerPinConfirm','registerInviteCode','authMessage','ludoLive'].map(id=>[id,$(id)]));

  const state={token:'',status:null,room:null,roomIdHint:'',booting:true,busy:false,refreshPromise:null,refreshQueued:false,refreshTimer:0,realtimeRoomId:'',realtimeConnected:false,lastError:'',soundEnabled:localStorage.getItem(SOUND_KEY)!=='0',audioCtx:null,lastTimeoutRoom:'',lastTimeoutAt:0,peers:new Map(),localStream:null,opponentMuted:false,lastSignalId:0,lastVoicePollAt:0};
  const rpc=(name,args={})=>{if(!window.JLApi?.rpc)throw new Error('API do jogo indisponível.');return window.JLApi.rpc(name,args);};
  const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const money=v=>Number(v||0).toLocaleString('pt-MZ',{minimumFractionDigits:2,maximumFractionDigits:2});
  const firstName=v=>String(v||'Jogador').trim().split(/\s+/)[0]||'Jogador';
  function getToken(){try{return window.JLSession?.getPlayerToken?.()||localStorage.getItem(TOKEN_KEY)||'';}catch{return'';}}
  function saveToken(value){const token=String(value||'');state.token=window.JLSession?.setPlayerToken?.(token)??token;if(!window.JLSession){if(token)localStorage.setItem(TOKEN_KEY,token);else localStorage.removeItem(TOKEN_KEY);}window.JLNotifications?.setActive?.(Boolean(token));}
  function roomData(){return state.room?.room||null;}function roomPlayers(){return Array.isArray(state.room?.players)?state.room.players:[];}function me(){return state.room?.identity?.player_id||state.status?.identity?.player_id||null;}function myPlayer(){return roomPlayers().find(p=>String(p.player_id)===String(me()));}function isHost(){return Boolean(roomData()?.host_id&&String(roomData().host_id)===String(me()));}function rules(){return roomData()?.rules||{};}
  function showToast(message,type=''){if(!ui.toast)return;ui.toast.textContent=String(message||'');ui.toast.className=`toast show ${type}`.trim();clearTimeout(showToast.timer);showToast.timer=setTimeout(()=>{ui.toast.className='toast';},3600);if(ui.ludoLive)ui.ludoLive.textContent=String(message||'');}
  function setAuthMessage(message,type=''){if(!ui.authMessage)return;ui.authMessage.textContent=String(message||'');ui.authMessage.className=`modal-message ${type}`.trim();}
  function openAuth(mode='login'){ui.authModal?.classList.remove('hidden');switchAuth(mode);}function closeAuth(){ui.authModal?.classList.add('hidden');setAuthMessage('');}function switchAuth(mode){const login=mode!=='register';ui.authTitle.textContent=login?'Entrar':'Criar conta';ui.loginTab?.classList.toggle('active',login);ui.registerTab?.classList.toggle('active',!login);ui.loginForm?.classList.toggle('hidden',!login);ui.registerForm?.classList.toggle('hidden',login);}
  async function withBusy(fn){if(state.busy)return;state.busy=true;document.body.classList.add('ludo-busy');try{return await fn();}finally{state.busy=false;document.body.classList.remove('ludo-busy');}}
  function wholeStake(value,label='O valor'){const n=Number(value);if(!Number.isFinite(n)||!Number.isInteger(n)||n<10){showToast(`${label} deve ser inteiro e no mínimo 10 MZN.`,'error');return null;}return n;}
  async function ensureFunds(amount,context='continuar'){const check=await rpc('jl_check_funds',{p_token:state.token,p_game_type:'ludo',p_amount:Number(amount)});if(check?.ok)return true;if(check?.redirect_to_deposit){const shortfall=Math.max(1,Math.ceil(Number(check.shortfall||0)));showToast(`Saldo insuficiente para ${context}.`,'error');location.href=`./index.html?open=deposit&deposit_needed=${encodeURIComponent(String(shortfall))}#depositPanel`;return false;}throw new Error(check?.message||'Saldo insuficiente.');}
  const maxId=rows=>(rows||[]).reduce((m,x)=>Math.max(m,Number(x?.id)||0),0);
  function mergeRows(a,b,limit=50){const map=new Map();for(const row of [...(a||[]),...(b||[])])map.set(String(row?.id??''),row);return[...map.values()].sort((x,y)=>(Number(x?.id)||0)-(Number(y?.id)||0)).slice(-limit);}

  async function loadRoom(roomId,previous=null){let base;try{base=await rpc('jl_ludo_room_state_light',{p_token:state.token,p_room:roomId});}catch{base=await rpc('jl_ludo_room_state',{p_token:state.token,p_room:roomId});}if(!base?.room?.id)throw new Error('O servidor não devolveu a sala ativa.');const same=Boolean(previous?.room?.id&&previous.room.id===base.room.id);try{const delta=await rpc('jl_ludo_room_delta',{p_token:state.token,p_room:base.room.id,p_after_event:same?maxId(previous.events):0,p_after_chat:same?maxId(previous.chat):0,p_include_payouts:base.room.status==='finished'});base.events=same?mergeRows(previous.events,delta?.events):(delta?.events||[]).slice(-50);base.chat=same?mergeRows(previous.chat,delta?.chat):(delta?.chat||[]).slice(-50);base.payouts=base.room.status==='finished'?(delta?.payouts||previous?.payouts||[]):(same?(previous?.payouts||[]):[]);}catch{base.events=same?(previous.events||[]):(base.events||[]);base.chat=same?(previous.chat||[]):(base.chat||[]);base.payouts=same?(previous.payouts||[]):(base.payouts||[]);}return base;}
  function scheduleRefresh(delay=70){clearTimeout(state.refreshTimer);state.refreshTimer=setTimeout(()=>{void refresh();},Math.max(0,Number(delay)||0));}
  async function refresh(){if(state.refreshPromise){state.refreshQueued=true;return state.refreshPromise;}state.refreshPromise=(async()=>{state.token=getToken();state.lastError='';if(!state.token){state.status=null;state.room=null;state.roomIdHint='';state.booting=false;syncRealtime('');closeVoice();render();return;}let nextStatus;try{nextStatus=await rpc('jl_ludo_my_status',{p_token:state.token});}catch(error){if(/sess[aã]o|token/i.test(String(error?.message||''))){saveToken('');state.status=null;state.room=null;state.roomIdHint='';state.booting=false;syncRealtime('');closeVoice();render();return;}state.lastError=String(error?.message||error);state.booting=false;render();throw error;}const activeRoomId=String(nextStatus?.active_room_id||'');state.roomIdHint=activeRoomId;if(activeRoomId){if(state.room?.room?.id&&String(state.room.room.id)!==activeRoomId){closeVoice();state.room=null;}state.status=nextStatus;render();let nextRoom=null;try{nextRoom=await loadRoom(activeRoomId,state.room);}catch(error){state.lastError=String(error?.message||error);}if(String(nextStatus?.active_room_id||'')===state.roomIdHint){state.status=nextStatus;if(nextRoom)state.room=nextRoom;}}else{let challenges=[];try{challenges=await rpc('jl_ludo_public_challenges',{p_token:state.token});}catch{challenges=Array.isArray(state.status?.public_challenges)?state.status.public_challenges:[];}nextStatus.public_challenges=Array.isArray(challenges)?challenges:[];state.status=nextStatus;state.room=null;}state.booting=false;syncRealtime(state.room?.room?.id||state.roomIdHint||'');render();})().finally(()=>{state.refreshPromise=null;if(state.refreshQueued){state.refreshQueued=false;queueMicrotask(()=>{void refresh();});}});return state.refreshPromise;}
  function syncRealtime(roomId){const id=String(roomId||'');if(!id){state.realtimeRoomId='';state.realtimeConnected=false;try{void window.JLLudoRealtime?.disconnect?.();}catch{}return;}if(!window.JLLudoRealtime)return;if(state.realtimeRoomId===id&&window.JLLudoRealtime.isConnected?.())return;state.realtimeRoomId=id;window.JLLudoRealtime.connect(id,{onSignal(payload){if(payload?.kind==='dice_rolled'){const n=Number(Array.isArray(payload.dice_values)?payload.dice_values[0]:payload.dice);if(Number.isInteger(n)&&n>=1&&n<=6)renderDice(n);}scheduleRefresh(45);},onStatus(connected){if(state.realtimeRoomId!==id)return;state.realtimeConnected=Boolean(connected);if(!connected)scheduleRefresh(150);}});}

  function render(){ui.bootPanel?.classList.toggle('hidden',!state.booting);if(state.booting){ui.loggedOut?.classList.add('hidden');ui.lobby?.classList.add('hidden');ui.room?.classList.add('hidden');return;}const authed=Boolean(state.token&&state.status?.identity);ui.statusStrip?.classList.toggle('hidden',!authed);ui.loggedOut?.classList.toggle('hidden',authed);if(!authed){ui.lobby?.classList.add('hidden');ui.room?.classList.add('hidden');ui.identityBadge.textContent='Não autenticado';ui.accountButton.textContent='Entrar';paintBoard(ui.loggedOutBoard,null,true);return;}renderStatusStrip();const activeKnown=Boolean(state.roomIdHint||state.room?.room?.id);ui.lobby?.classList.toggle('hidden',activeKnown);ui.room?.classList.toggle('hidden',!activeKnown);if(activeKnown){ui.roomLoading?.classList.toggle('hidden',Boolean(state.room?.room?.id));if(state.room?.room?.id)renderRoom();else renderRoomShell();}else renderLobby();}
  function renderStatusStrip(){const identity=state.status?.identity||state.room?.identity||{},balance=Number(identity.balance);ui.identityBadge.textContent=identity.name||identity.code||'Jogador';ui.accountButton.textContent='Sair';ui.balanceMetric.textContent=identity.balance_confirmed===true&&Number.isFinite(balance)?money(balance):'—';ui.onlinePlayerCount.textContent=String(Math.max(0,Number(state.status?.online_count||0)));const invites=Array.isArray(state.status?.invites)?state.status.invites:[],challenges=Array.isArray(state.status?.public_challenges)?state.status.public_challenges:[];ui.directInviteCount.textContent=String(invites.length);ui.publicChallengeCount.textContent=String(challenges.length);window.JLNotifications?.setActive?.(true);}
  function renderLobby(){const status=state.status||{},queue=status.queue;ui.queueStatus?.classList.toggle('hidden',!queue);if(queue){ui.queueStatus.innerHTML=`Em espera: <strong>${Number(queue.player_count||0)} jogadores</strong> · ${esc(queue.mode||'solo')} · <strong>${money(queue.bet_amount)} MZN</strong>`;ui.queueButton.textContent='Sair da espera';ui.queueButton.dataset.queued='1';}else{ui.queueButton.textContent='Quero jogar';delete ui.queueButton.dataset.queued;}const invites=Array.isArray(status.invites)?status.invites:[];ui.inviteList.innerHTML=invites.length?invites.map(i=>`<article class="list-item"><div><strong>${esc(i.host||i.host_name||'Jogador')} · ${esc(i.host_code||'')}</strong><small>${esc(i.room_code||'')} · ${Number(i.player_count||0)} jogadores · ${money(i.bet_amount)} MZN</small></div><div class="list-actions"><button class="button success small" type="button" data-invite-accept="${esc(i.id)}" data-bet="${Number(i.bet_amount||0)}">Aceitar</button><button class="button danger small" type="button" data-invite-decline="${esc(i.id)}">Recusar</button></div></article>`).join(''):'<div class="empty">Nenhum convite.</div>';const challenges=Array.isArray(status.public_challenges)?status.public_challenges:[];ui.publicChallengeList.innerHTML=challenges.length?challenges.map(c=>`<article class="list-item"><div><strong>${esc(c.host_name||'Jogador')} · ${esc(c.host_code||'')}</strong><small>${esc(c.code||'')} · ${Number(c.joined_count||0)}/${Number(c.player_count||0)} · ${money(c.bet_amount)} MZN</small></div><div class="list-actions"><button class="button secondary small" type="button" data-public-accept="${esc(c.code)}" data-bet="${Number(c.bet_amount||0)}">Entrar</button></div></article>`).join(''):'<div class="empty">Nenhum desafio público.</div>';}
  function renderRoomShell(){ui.roomCode.textContent=state.roomIdHint?'Sala ativa':'—';ui.roomMeta.textContent=state.lastError?`A sincronização será repetida · ${state.lastError}`:'A carregar estado autoritativo…';ui.roomPot.textContent='—';ui.playersPanel.innerHTML='';ui.deadlineBar.classList.add('hidden');ui.gamePanel.classList.add('hidden');ui.pregameArea.classList.add('hidden');ui.fundingPanel.classList.add('hidden');ui.chatPanel.classList.add('hidden');ui.resultPanel.classList.add('hidden');}
  function roomMeta(r){return`${Number(r.player_count||0)} jogadores · ${Number(r.pawn_count||r.rules?.pawn_count||4)} peões · ${r.mode==='partners'?'Parceiros 2 × 2':'Cada um por si'} · ${money(r.bet_amount)} MZN · ${r.is_public?'Pública':'Privada'}`;}
  function renderRoom(){const r=roomData();if(!r)return;ui.roomLoading.classList.add('hidden');ui.roomCode.textContent=r.code||'—';ui.roomMeta.textContent=roomMeta(r);ui.roomPot.textContent=`${money(r.pot||Number(r.bet_amount||0)*Number(r.player_count||0))} MZN`;const started=r.status==='playing';ui.leaveRoom.classList.toggle('hidden',started);ui.forfeitRoom.classList.toggle('hidden',!started);renderPlayers();renderDeadline();renderBoardArea();ui.pregameArea.classList.toggle('hidden',['playing','finished','cancelled'].includes(r.status));renderRules();renderFunding();renderInvitePanel();renderChat();renderResult();renderVoice();}
  function renderPlayers(){const r=roomData(),players=roomPlayers();ui.playersPanel.innerHTML=Array.from({length:Number(r.player_count||0)},(_,index)=>{const seat=index+1,p=players.find(x=>Number(x.seat)===seat);if(!p)return`<article class="player-card"><small>Vaga ${seat}</small><h3>Aguardando…</h3></article>`;const accepted=Number(p.accepted_rules_version)===Number(r.rules_version),current=String(r.current_player_id||'')===String(p.player_id||'');return`<article class="player-card ${esc(p.color||'')} ${current?'current':''}"><small>${p.team?`Equipa ${esc(p.team)} · `:''}posição ${seat}</small><h3>${esc(firstName(p.name||p.code))}</h3><small>${esc(p.code||'')}</small><div class="player-flags"><span class="flag ${accepted?'ok':'wait'}">${accepted?'✓ regras':'regras…'}</span><span class="flag ${p.stake_paid?'ok':'wait'}">${p.stake_paid?'✓ aposta':'aposta…'}</span><span class="flag">${esc(p.status||'')}</span></div></article>`;}).join('');}
  function renderDeadline(){const r=roomData();let label=r.status;if(r.status==='waiting')label='Aguardando jogadores';if(r.status==='negotiating')label='Aceitação das regras · sem prazo';if(r.status==='funding')label='Confirmação da aposta';if(r.status==='playing'&&!r.started_at)label='Aguardando primeiro dado';if(r.status==='playing'&&r.started_at)label='Tempo da jogada';if(r.status==='finished')label='Partida terminada';ui.deadlineLabel.textContent=label;ui.deadlineBar.classList.remove('hidden');updateClock();}
  function secondsToClock(seconds){const s=Math.max(0,Math.ceil(Number(seconds)||0));return`${String(Math.floor(s/60)).padStart(2,'0')}:${String(s%60).padStart(2,'0')}`;}
  function updateClock(){const r=roomData();if(!r)return;if(r.status==='negotiating'){ui.deadlineClock.textContent='Sem prazo';ui.turnTimer.textContent='--:--';return;}if(!r.action_deadline){ui.deadlineClock.textContent='—';ui.turnTimer.textContent='--:--';}else{const seconds=(new Date(r.action_deadline).getTime()-Date.now())/1000,text=secondsToClock(seconds);ui.deadlineClock.textContent=text;ui.turnTimer.textContent=r.status==='playing'&&r.started_at?text:'--:--';ui.deadlineBar.classList.toggle('urgent',seconds<=10);if(seconds<=0&&['funding','playing'].includes(r.status)){const now=Date.now();if(state.lastTimeoutRoom!==r.id||now-state.lastTimeoutAt>1800){state.lastTimeoutRoom=r.id;state.lastTimeoutAt=now;void rpc('jl_ludo_process_timeouts',{p_token:state.token,p_room:r.id}).then(()=>scheduleRefresh(20)).catch(()=>{});}}}if(r.id&&Date.now()-state.lastVoicePollAt>=1000){state.lastVoicePollAt=Date.now();void pullSignals();}}

  function tokenCoord(color,steps,tokenNo){const n=Number(steps);if(n===-1)return BASE[color]?.[Math.max(0,Number(tokenNo||1)-1)]||null;if(n>=0&&n<=50)return PATH[(START[color]+n)%52];if(n>=51&&n<=55)return HOME[color]?.[n-51]||null;return FINISH_CELL[color]||[7,7];}
  function makeCells(board){const cells=Array.from({length:225},()=>{const d=document.createElement('div');d.className='cell';return d;}),at=(r,c)=>cells[r*15+c];for(let r=0;r<6;r++)for(let c=0;c<6;c++)at(r,c).classList.add('base-red');for(let r=0;r<6;r++)for(let c=9;c<15;c++)at(r,c).classList.add('base-green');for(let r=9;r<15;r++)for(let c=9;c<15;c++)at(r,c).classList.add('base-yellow');for(let r=9;r<15;r++)for(let c=0;c<6;c++)at(r,c).classList.add('base-blue');for(const[r1,r2,c1,c2]of[[1,4,1,4],[1,4,10,13],[10,13,10,13],[10,13,1,4]])for(let r=r1;r<=r2;r++)for(let c=c1;c<=c2;c++)at(r,c).classList.add('base-inner');PATH.forEach(([r,c],i)=>{at(r,c).classList.add('path');if(SAFE.has(i))at(r,c).classList.add('safe');});Object.entries(HOME).forEach(([color,coords])=>coords.forEach(([r,c])=>at(r,c).classList.add(`home-${color}`)));for(let r=6;r<=8;r++)for(let c=6;c<=8;c++)at(r,c).classList.add('center');board.replaceChildren(...cells);return{cells,at};}
  function paintBoard(board,snapshot=state.room,preview=false){if(!board)return;const{at}=makeCells(board),players=Array.isArray(snapshot?.players)?snapshot.players:[],tokens=Array.isArray(snapshot?.tokens)?snapshot.tokens:[],legal=new Set((snapshot?.legal_moves||[]).map(x=>Number(x.token_no))),mineId=snapshot?.identity?.player_id||me(),pieces=[];if(tokens.length){for(const token of tokens){const player=players.find(p=>String(p.player_id)===String(token.player_id));if(player?.color)pieces.push({player,token});}}else if(preview){for(const color of['red','green','yellow','blue'])for(let tokenNo=1;tokenNo<=4;tokenNo++)pieces.push({player:{player_id:`preview-${color}`,color,pawn_style:'current'},token:{player_id:`preview-${color}`,token_no:tokenNo,steps:-1}});}else{const count=Math.max(1,Math.min(4,Number(roomData()?.pawn_count||rules().pawn_count||4)));for(const player of players.filter(p=>p.status!=='left'&&p.color))for(let tokenNo=1;tokenNo<=count;tokenNo++)pieces.push({player,token:{player_id:player.player_id,token_no:tokenNo,steps:-1}});}const occupancy=new Map();for(const item of pieces){const coord=tokenCoord(item.player.color,item.token.steps,item.token.token_no);if(!coord)continue;const key=coord.join(':'),list=occupancy.get(key)||[];list.push(item);occupancy.set(key,list);}for(const[key,list]of occupancy){const[r,c]=key.split(':').map(Number),cell=at(r,c);if(!cell)continue;if(list.length>1)cell.classList.add('multi');for(const{player,token}of list){const piece=document.createElement('button');piece.type='button';const style=PAWN_STYLES.has(String(player.pawn_style||''))?String(player.pawn_style):'current',mine=String(player.player_id)===String(mineId),canMove=!preview&&mine&&legal.has(Number(token.token_no));piece.className=`piece ${player.color} pawn-style-${style}${mine?' mine':''}${canMove?' legal':''}`;piece.dataset.playerId=String(player.player_id||'');piece.dataset.tokenNo=String(token.token_no||'');piece.disabled=!canMove;piece.setAttribute('aria-label',`${firstName(player.name||player.code)} · peão ${Number(token.token_no||0)}${canMove?' · mover':''}`);if(canMove)piece.addEventListener('click',()=>void moveToken(Number(token.token_no)));cell.appendChild(piece);}}}
  function renderBoardArea(){const r=roomData(),show=['waiting','negotiating','funding','playing','finished'].includes(r.status);ui.gamePanel.classList.toggle('hidden',!show);if(!show)return;paintBoard(ui.ludoBoard,state.room,false);const current=roomPlayers().find(p=>String(p.player_id)===String(r.current_player_id)),myTurn=String(r.current_player_id||'')===String(me()||'');if(r.status==='playing')ui.turnTitle.textContent=current?`Vez de ${firstName(current.name||current.code)}`:'Partida em curso';else if(r.status==='finished')ui.turnTitle.textContent='Partida terminada';else ui.turnTitle.textContent=`Preparação · ${r.status}`;const legal=Array.isArray(state.room?.legal_moves)?state.room.legal_moves:[];if(r.status!=='playing')ui.moveHint.textContent='O mesmo tabuleiro permanece visível enquanto a sala é preparada.';else if(!myTurn)ui.moveHint.textContent=`Aguarde ${current?firstName(current.name||current.code):'o outro jogador'}.`;else if(r.turn_phase==='move')ui.moveHint.textContent=legal.length?'Escolha um peão destacado.':'Sem movimento legal; o servidor encerrará a vez.';else ui.moveHint.textContent='É a sua vez. Lance o dado.';const diceValue=Number(Array.isArray(r.dice_values)?r.dice_values[r.dice_index||0]:r.dice_result);renderDice(diceValue);ui.dice.disabled=!(r.status==='playing'&&myTurn&&r.turn_phase==='roll'&&!state.busy);ui.dice.classList.toggle('hidden',r.status!=='playing');const mine=myPlayer(),canReenter=Boolean(r.status==='playing'&&rules().reentry_allowed&&(mine?.can_reenter===true||/eliminat/i.test(String(mine?.status||''))));ui.reenterButton.classList.toggle('hidden',!canReenter);}
  function renderDice(value){const n=Number(value);ui.dice.textContent=Number.isInteger(n)&&n>=1&&n<=6?DICE_FACE[n]:'?';ui.dice.dataset.value=Number.isInteger(n)?String(n):'';}

  function ruleRows(){const x=rules();return[`Tempo: ${Number(x.turn_seconds||30)} s`,'Saída da base: somente 6',x.capture_required?`Captura obrigatória · ${x.capture_penalty||'perde a vez'}`:'Captura não obrigatória',x.reentry_allowed?`Reentrada: ${money(x.reentry_amount||10)} MZN`:'Sem reentrada',x.exact_finish!==false?'Chegada exata':'Chegada sem valor exato',`Dados: ${Number(x.dice_count||1)}`,x.play_location==='presential'?'Presencial':'Online','Casas seguras · sem barreiras'];}
  function fillRulesForm(){const form=ui.rulesForm;if(!form)return;const x=rules();for(const el of form.elements){if(!el.name)continue;let value=x[el.name];if(value==null){if(el.name==='turn_seconds')value=30;if(el.name==='dice_count')value=1;if(el.name==='play_location')value='online';if(el.name==='reentry_amount')value=10;}if(el.type==='checkbox')el.checked=Boolean(value);else if(value!=null)el.value=String(value);}const twoPlayers=Number(roomData()?.player_count)===2,penalty=form.elements.capture_penalty;if(penalty&&twoPlayers)penalty.value='lose_turn';if(penalty)penalty.disabled=twoPlayers;}
  function readRulesForm(){const out={};for(const el of ui.rulesForm.elements){if(!el.name)continue;if(el.type==='checkbox')out[el.name]=el.checked;else if(el.type==='number'||['turn_seconds','dice_count'].includes(el.name))out[el.name]=Number(el.value);else out[el.name]=el.value;}out.move_seconds=Number(out.turn_seconds||30);out.safe_cells=true;out.blockades=false;out.exact_finish=true;if(Number(roomData()?.player_count)===2)out.capture_penalty='lose_turn';return out;}
  function renderRules(){const r=roomData();ui.rulesVersion.textContent=`v${Number(r.rules_version||1)}`;ui.rulesSummary.innerHTML=ruleRows().map(row=>`<div class="rule-chip">${esc(row)}</div>`).join('');fillRulesForm();ui.rulesForm.classList.toggle('hidden',!isHost()||!['waiting','negotiating'].includes(r.status));const mine=myPlayer(),needs=mine&&Number(mine.accepted_rules_version)!==Number(r.rules_version)&&['waiting','negotiating'].includes(r.status);ui.rulesDecision.classList.toggle('hidden',!needs);document.querySelectorAll('.partner-rule').forEach(el=>el.classList.toggle('hidden',r.mode!=='partners'));}
  function renderFunding(){const r=roomData(),show=r.status==='funding';ui.fundingPanel.classList.toggle('hidden',!show);if(!show)return;const paid=roomPlayers().filter(p=>p.stake_paid).length;ui.fundingText.textContent=`${paid}/${Number(r.player_count||0)} jogadores confirmaram ${money(r.bet_amount)} MZN por jogador.`;ui.fundButton.disabled=Boolean(myPlayer()?.stake_paid);ui.fundButton.textContent=myPlayer()?.stake_paid?'Aposta confirmada':`Confirmar ${money(r.bet_amount)} MZN`;if(document.activeElement!==ui.stakeProposalAmount)ui.stakeProposalAmount.value=String(Math.trunc(Number(r.bet_amount||10)));}
  function renderInvitePanel(){const r=roomData(),show=isHost()&&['waiting','negotiating'].includes(r.status);ui.invitePanel.classList.toggle('hidden',!show);ui.broadcastRoom.classList.toggle('hidden',!show||!r.is_public);if(show)void loadWaiting(true);}
  function renderChat(){const enabled=Boolean(rules().chat_enabled&&roomData()?.status!=='cancelled');ui.chatPanel.classList.toggle('hidden',!enabled);if(!enabled)return;const rows=Array.isArray(state.room?.chat)?state.room.chat:[];ui.chatMessages.innerHTML=rows.length?rows.map(m=>`<div class="chat-msg"><strong>${esc(firstName(m.name||m.player_name||m.code||'Jogador'))}</strong>${esc(m.message||m.text||'')}</div>`).join(''):'<div class="empty">Sem mensagens.</div>';ui.chatMessages.scrollTop=ui.chatMessages.scrollHeight;}
  function renderResult(){const r=roomData(),show=r.status==='finished';ui.resultPanel.classList.toggle('hidden',!show);if(!show)return;const winner=roomPlayers().find(p=>String(p.player_id)===String(r.winner_player_id));ui.resultTitle.textContent=winner?`${firstName(winner.name||winner.code)} venceu`:(r.mode==='partners'&&r.winner_team?`Equipa ${r.winner_team} venceu`:'Partida terminada');const payouts=Array.isArray(state.room?.payouts)?state.room.payouts:[];ui.resultPayouts.innerHTML=payouts.length?payouts.map(p=>`<div class="payout-card"><strong>${money(p.net||p.amount||0)} MZN</strong><small>${esc(p.player_name||p.player_id||'')}</small></div>`).join(''):'<span class="muted">Pagamento a confirmar pelo servidor.</span>';ui.rematchBet.value=String(Math.trunc(Number(r.bet_amount||10)));ui.rematchTurn.value=String(Number(rules().turn_seconds||30));ui.rematchMode.value=r.mode||'solo';ui.rematchPawns.value=String(Number(r.pawn_count||rules().pawn_count||4));ui.rematchDice.value=String(Number(rules().dice_count||1));ui.rematchColor.value=myPlayer()?.color||preferredColor();}

  function preferredColor(){const value=String(localStorage.getItem(COLOR_KEY)||ui.createColor?.value||'red').toLowerCase();return COLORS.has(value)?value:'red';}function preferredPawnStyle(){const value=String(localStorage.getItem(PAWN_STYLE_KEY)||ui.createPawnStyle?.value||'current').toLowerCase();return PAWN_STYLES.has(value)?value:'current';}
  function syncColorPicker(color=preferredColor()){ui.createColor.value=color;ui.createColorPicker?.querySelectorAll('[data-color]').forEach(button=>{const on=button.dataset.color===color;button.classList.toggle('active',on);button.setAttribute('aria-pressed',on?'true':'false');});}
  async function applyPreferences(snapshot){let next=snapshot;if(!next?.room?.id)return next;const r=next.room;if(['waiting','negotiating'].includes(r.status)){try{const mine=(next.players||[]).find(p=>String(p.player_id)===String(next.identity?.player_id)),color=preferredColor();if(mine?.color!==color)next=await rpc('jl_ludo_choose_color',{p_token:state.token,p_room:r.id,p_color:color});}catch{}}if(['waiting','negotiating','funding'].includes(next?.room?.status)){try{const mine=(next.players||[]).find(p=>String(p.player_id)===String(next.identity?.player_id)),style=preferredPawnStyle();if((mine?.pawn_style||'current')!==style)next=await rpc('jl_ludo_choose_pawn_style',{p_token:state.token,p_room:next.room.id,p_pawn_style:style});}catch{}}return next;}
  async function loadWaiting(silent=false){if(!state.room?.room?.id||!isHost())return;try{const rows=await rpc('jl_ludo_waiting_players',{p_token:state.token,p_room:roomData().id});ui.waitingPlayers.innerHTML=rows?.length?rows.map(p=>`<div class="list-item"><div><strong>${esc(p.name||'Jogador')}</strong><small>${esc(p.code||'')}</small></div><button class="button ghost small" type="button" data-invite-player="${esc(p.player_id)}">Convidar</button></div>`).join(''):'<div class="empty">Nenhum compatível agora.</div>';}catch(error){if(!silent)showToast(error.message,'error');}}
  async function moveToken(tokenNo){await withBusy(async()=>{const r=roomData(),legal=(state.room?.legal_moves||[]).find(x=>Number(x.token_no)===Number(tokenNo));if(!r||!legal)return;try{playTone(420,.05);state.room=await rpc('jl_ludo_move',{p_token:state.token,p_room:r.id,p_token_no:Number(tokenNo)});render();scheduleRefresh(40);}catch(error){showToast(error.message,'error');scheduleRefresh(40);}});}
  function playTone(freq=440,duration=.06){if(!state.soundEnabled)return;try{const AudioCtx=window.AudioContext||window.webkitAudioContext;if(!AudioCtx)return;if(!state.audioCtx)state.audioCtx=new AudioCtx();if(state.audioCtx.state==='suspended')void state.audioCtx.resume();const osc=state.audioCtx.createOscillator(),gain=state.audioCtx.createGain();osc.type='triangle';osc.frequency.value=freq;gain.gain.setValueAtTime(.035,state.audioCtx.currentTime);gain.gain.exponentialRampToValueAtTime(.0001,state.audioCtx.currentTime+duration);osc.connect(gain);gain.connect(state.audioCtx.destination);osc.start();osc.stop(state.audioCtx.currentTime+duration+.02);}catch{}}
  function toggleSound(){state.soundEnabled=!state.soundEnabled;localStorage.setItem(SOUND_KEY,state.soundEnabled?'1':'0');ui.soundToggle.textContent=state.soundEnabled?'🔊 Som':'🔇 Som';ui.soundToggle.setAttribute('aria-pressed',state.soundEnabled?'true':'false');if(state.soundEnabled)playTone(520,.05);}

  function voiceAvailable(){const r=roomData();return Boolean(r&&!['finished','cancelled'].includes(r.status)&&rules().play_location!=='presential'&&navigator.mediaDevices?.getUserMedia&&window.RTCPeerConnection);}
  function renderVoice(){if(!ui.micButton)return;const available=voiceAvailable(),on=Boolean(state.localStream?.getAudioTracks?.().some(t=>t.readyState==='live'));ui.micButton.disabled=!available;ui.micButton.textContent=!available?'🎙️ Voz indisponível':(on?'🔇 Desligar microfone':'🎙️ Ligar microfone');ui.micButton.setAttribute('aria-pressed',on?'true':'false');if(ui.muteOpponent){ui.muteOpponent.disabled=!available;ui.muteOpponent.textContent=state.opponentMuted?'🔇 Silenciado':'🔊 Ouvir';ui.muteOpponent.setAttribute('aria-pressed',state.opponentMuted?'true':'false');}}
  function voiceIceServers(){const configured=Array.isArray(window.JL_CONFIG?.ludoIceServers)?window.JL_CONFIG.ludoIceServers.filter(Boolean):[];return configured.length?configured:[{urls:'stun:stun.l.google.com:19302'},{urls:'stun:stun1.l.google.com:19302'}];}
  async function sendSignal(to,type,payload){try{await rpc('jl_ludo_signal_send',{p_token:state.token,p_room:roomData().id,p_to_player:to,p_signal_type:type,p_payload:payload});}catch{}}
  function attachVoiceTracks(pc){if(!state.localStream)return;for(const track of state.localStream.getTracks()){const sender=pc.getSenders().find(s=>s.track?.kind===track.kind);if(sender){if(sender.track!==track)void sender.replaceTrack(track);}else pc.addTrack(track,state.localStream);}}
  function ensurePeer(peerId,addTracks=false){let wrap=state.peers.get(peerId);if(wrap){if(addTracks)attachVoiceTracks(wrap.pc);return wrap;}const pc=new RTCPeerConnection({iceServers:voiceIceServers()});wrap={pc,makingOffer:false,ignoreOffer:false,polite:String(me())>String(peerId),pendingIce:[]};state.peers.set(peerId,wrap);pc.onicecandidate=e=>{if(e.candidate)void sendSignal(peerId,'ice',e.candidate.toJSON());};pc.ontrack=e=>{if(!ui.remoteAudio)return;let audio=document.getElementById(`ludo-audio-${peerId}`);if(!audio){audio=document.createElement('audio');audio.id=`ludo-audio-${peerId}`;audio.autoplay=true;audio.playsInline=true;ui.remoteAudio.appendChild(audio);}audio.srcObject=e.streams[0];audio.muted=state.opponentMuted;void audio.play().catch(()=>{audio.controls=true;});};pc.onnegotiationneeded=async()=>{try{wrap.makingOffer=true;await pc.setLocalDescription(await pc.createOffer());await sendSignal(peerId,'offer',pc.localDescription);}catch{}finally{wrap.makingOffer=false;}};if(addTracks)attachVoiceTracks(pc);return wrap;}
  async function flushIce(wrap){if(!wrap?.pc?.remoteDescription)return;while(wrap.pendingIce.length){try{await wrap.pc.addIceCandidate(new RTCIceCandidate(wrap.pendingIce.shift()));}catch{}}}
  async function handleSignal(signal){const peerId=signal.from_player_id;if(!peerId||String(peerId)===String(me()))return;const wrap=ensurePeer(peerId,Boolean(state.localStream)),pc=wrap.pc;try{if(signal.signal_type==='offer'){const desc=new RTCSessionDescription(signal.payload),collision=wrap.makingOffer||pc.signalingState!=='stable';wrap.ignoreOffer=!wrap.polite&&collision;if(wrap.ignoreOffer)return;if(collision&&wrap.polite&&pc.signalingState!=='stable'){try{await pc.setLocalDescription({type:'rollback'});}catch{}}await pc.setRemoteDescription(desc);await flushIce(wrap);if(state.localStream)attachVoiceTracks(pc);await pc.setLocalDescription(await pc.createAnswer());await sendSignal(peerId,'answer',pc.localDescription);}else if(signal.signal_type==='answer'){if(pc.signalingState==='have-local-offer'){await pc.setRemoteDescription(new RTCSessionDescription(signal.payload));await flushIce(wrap);}}else if(signal.signal_type==='ice'){if(!pc.remoteDescription)wrap.pendingIce.push(signal.payload);else await pc.addIceCandidate(new RTCIceCandidate(signal.payload));}}catch{}}
  async function pullSignals(){if(!state.token||!roomData()?.id||!voiceAvailable())return;try{const rows=await rpc('jl_ludo_signal_pull',{p_token:state.token,p_room:roomData().id,p_after_id:state.lastSignalId});for(const signal of rows||[]){state.lastSignalId=Math.max(state.lastSignalId,Number(signal.id)||0);await handleSignal(signal);}}catch{}}
  async function toggleMic(){if(!voiceAvailable())return;try{if(!state.localStream){state.localStream=await navigator.mediaDevices.getUserMedia({audio:{echoCancellation:true,noiseSuppression:true,autoGainControl:true},video:false});for(const player of roomPlayers())if(String(player.player_id)!==String(me()))ensurePeer(player.player_id,true);showToast('Microfone ligado.','success');}else{state.localStream.getTracks().forEach(t=>t.stop());state.localStream=null;for(const wrap of state.peers.values())for(const sender of wrap.pc.getSenders())if(sender.track?.kind==='audio')void sender.replaceTrack(null);showToast('Microfone desligado.');}renderVoice();}catch(error){showToast(`Microfone: ${error.message}`,'error');}}
  function toggleOpponentMute(){state.opponentMuted=!state.opponentMuted;for(const audio of ui.remoteAudio?.querySelectorAll('audio')||[])audio.muted=state.opponentMuted;renderVoice();}
  function closeVoice(){for(const wrap of state.peers.values())try{wrap.pc.close();}catch{}state.peers.clear();if(state.localStream)state.localStream.getTracks().forEach(t=>t.stop());state.localStream=null;state.lastSignalId=0;state.lastVoicePollAt=0;if(ui.remoteAudio)ui.remoteAudio.replaceChildren();}

  document.querySelectorAll('[data-open-auth]').forEach(b=>b.addEventListener('click',()=>openAuth(b.dataset.openAuth||'login')));ui.closeAuth?.addEventListener('click',closeAuth);ui.loginTab?.addEventListener('click',()=>switchAuth('login'));ui.registerTab?.addEventListener('click',()=>switchAuth('register'));ui.authModal?.addEventListener('click',e=>{if(e.target===ui.authModal)closeAuth();});
  ui.loginForm?.addEventListener('submit',e=>{e.preventDefault();void withBusy(async()=>{try{setAuthMessage('Entrando…');const res=await rpc('jl_login_player',{p_phone:ui.loginPhone.value.trim(),p_pin:ui.loginPin.value.trim()});saveToken(res?.token);closeAuth();state.booting=true;render();await refresh();showToast('Sessão iniciada.','success');}catch(error){setAuthMessage(error.message,'error');}});});
  ui.registerForm?.addEventListener('submit',e=>{e.preventDefault();if(ui.registerPin.value!==ui.registerPinConfirm.value){setAuthMessage('Os PINs não coincidem.','error');return;}void withBusy(async()=>{try{setAuthMessage('Criando conta…');const res=await rpc('jl_register_player',{p_name:ui.registerName.value.trim(),p_phone:ui.registerPhone.value.trim(),p_pin:ui.registerPin.value.trim(),p_invite_code:ui.registerInviteCode.value.trim()||null});saveToken(res?.token);closeAuth();state.booting=true;render();await refresh();showToast('Conta criada.','success');}catch(error){setAuthMessage(error.message,'error');}});});
  ui.accountButton?.addEventListener('click',()=>{if(!state.token)return openAuth('login');void withBusy(async()=>{const ok=window.JLConfirmLogout?await window.JLConfirmLogout():confirm('Sair da conta?');if(!ok)return;try{await rpc('jl_logout_player',{p_token:state.token});}catch{}saveToken('');state.status=null;state.room=null;state.roomIdHint='';state.booting=false;syncRealtime('');closeVoice();render();showToast('Sessão encerrada.');});});
  ui.refreshButton?.addEventListener('click',()=>scheduleRefresh(0));ui.refreshLobbyButton?.addEventListener('click',()=>scheduleRefresh(0));ui.directMetric?.addEventListener('click',()=>ui.notificationsPanel?.scrollIntoView({behavior:'smooth',block:'start'}));ui.publicMetric?.addEventListener('click',()=>ui.notificationsPanel?.scrollIntoView({behavior:'smooth',block:'start'}));
  ui.createColorPicker?.addEventListener('click',e=>{const b=e.target.closest('[data-color]');if(!b||!COLORS.has(b.dataset.color))return;localStorage.setItem(COLOR_KEY,b.dataset.color);syncColorPicker(b.dataset.color);});ui.createPawnStyle?.addEventListener('change',()=>{if(PAWN_STYLES.has(ui.createPawnStyle.value))localStorage.setItem(PAWN_STYLE_KEY,ui.createPawnStyle.value);});ui.createMode?.addEventListener('change',()=>{if(ui.createMode.value==='partners')ui.createPlayers.value='4';});ui.createPlayers?.addEventListener('change',()=>{if(ui.createMode.value==='partners'&&ui.createPlayers.value!=='4')ui.createMode.value='solo';});ui.queueMode?.addEventListener('change',()=>{if(ui.queueMode.value==='partners')ui.queuePlayers.value='4';});
  ui.createRoomForm?.addEventListener('submit',e=>{e.preventDefault();void withBusy(async()=>{const bet=wholeStake(ui.createBet.value,'A aposta');if(bet==null)return;try{if(!(await ensureFunds(bet,'criar esta sala')))return;const seconds=Number(ui.createTurnSeconds.value||30);let snapshot=await rpc('jl_ludo_create_room',{p_token:state.token,p_player_count:Number(ui.createPlayers.value),p_bet_amount:bet,p_mode:ui.createMode.value,p_is_public:Boolean(ui.createPublic.checked),p_rules:{turn_seconds:seconds,move_seconds:seconds,pawn_count:Number(ui.createPawnCount.value||4)}});snapshot=await applyPreferences(snapshot);state.room=snapshot;state.roomIdHint=snapshot?.room?.id||'';render();scheduleRefresh(20);showToast('Sala criada.','success');}catch(error){showToast(error.message,'error');}});});
  ui.joinCodeForm?.addEventListener('submit',e=>{e.preventDefault();void withBusy(async()=>{try{let snapshot=await rpc('jl_ludo_join_public_room',{p_token:state.token,p_code:ui.joinCode.value.trim()});snapshot=await applyPreferences(snapshot);state.room=snapshot;state.roomIdHint=snapshot?.room?.id||'';render();scheduleRefresh(20);showToast('Entrou na sala.','success');}catch(error){showToast(error.message,'error');}});});
  ui.queueForm?.addEventListener('submit',e=>{e.preventDefault();void withBusy(async()=>{try{if(ui.queueButton.dataset.queued)await rpc('jl_ludo_leave_queue',{p_token:state.token});else{const bet=wholeStake(ui.queueBet.value,'A aposta');if(bet==null||!(await ensureFunds(bet,'entrar na espera')))return;await rpc('jl_ludo_enter_queue',{p_token:state.token,p_bet_amount:bet,p_player_count:Number(ui.queuePlayers.value),p_mode:ui.queueMode.value});}scheduleRefresh(20);}catch(error){showToast(error.message,'error');}});});
  ui.inviteList?.addEventListener('click',e=>{const accept=e.target.closest('[data-invite-accept]'),decline=e.target.closest('[data-invite-decline]');if(!accept&&!decline)return;void withBusy(async()=>{try{if(accept){const bet=Number(accept.dataset.bet||0);if(bet>0&&!(await ensureFunds(bet,'aceitar este convite')))return;}let result=await rpc('jl_ludo_accept_invite',{p_token:state.token,p_invitation:(accept||decline).dataset[accept?'inviteAccept':'inviteDecline'],p_accept:Boolean(accept)});if(accept&&result?.room){result=await applyPreferences(result);state.room=result;state.roomIdHint=result.room.id;render();}scheduleRefresh(20);}catch(error){showToast(error.message,'error');}});});
  ui.publicChallengeList?.addEventListener('click',e=>{const b=e.target.closest('[data-public-accept]');if(!b)return;void withBusy(async()=>{try{const bet=Number(b.dataset.bet||0);if(bet>0&&!(await ensureFunds(bet,'entrar neste desafio')))return;let snapshot=await rpc('jl_ludo_accept_public_challenge',{p_token:state.token,p_code:b.dataset.publicAccept});snapshot=await applyPreferences(snapshot);state.room=snapshot;state.roomIdHint=snapshot?.room?.id||'';render();scheduleRefresh(20);}catch(error){showToast(error.message,'error');}});});
  ui.copyRoomCode?.addEventListener('click',async()=>{const code=roomData()?.code;if(!code)return;try{await navigator.clipboard.writeText(code);showToast('Código copiado.','success');}catch{showToast(code);}});
  ui.leaveRoom?.addEventListener('click',()=>{const r=roomData();if(!r||!confirm('Sair desta sala?'))return;void withBusy(async()=>{try{await rpc('jl_ludo_cancel_or_leave',{p_token:state.token,p_room:r.id});state.room=null;state.roomIdHint='';closeVoice();render();scheduleRefresh(20);showToast('Saiu da sala.');}catch(error){showToast(error.message,'error');}});});
  ui.forfeitRoom?.addEventListener('click',()=>{const r=roomData();if(!r||!confirm('Desistir desta partida?'))return;void withBusy(async()=>{try{await rpc('jl_ludo_forfeit',{p_token:state.token,p_room:r.id});closeVoice();scheduleRefresh(20);}catch(error){showToast(error.message,'error');}});});
  ui.rulesForm?.addEventListener('submit',e=>{e.preventDefault();void withBusy(async()=>{try{state.room=await rpc('jl_ludo_update_rules',{p_token:state.token,p_room:roomData().id,p_rules:readRulesForm()});render();scheduleRefresh(20);showToast('Regras propostas.','success');}catch(error){showToast(error.message,'error');}});});
  ui.acceptRules?.addEventListener('click',()=>void withBusy(async()=>{try{state.room=await rpc('jl_ludo_accept_rules',{p_token:state.token,p_room:roomData().id,p_accept:true});render();scheduleRefresh(20);}catch(error){showToast(error.message,'error');}}));ui.declineRules?.addEventListener('click',()=>void withBusy(async()=>{try{state.room=await rpc('jl_ludo_accept_rules',{p_token:state.token,p_room:roomData().id,p_accept:false});render();scheduleRefresh(20);}catch(error){showToast(error.message,'error');}}));
  ui.fundButton?.addEventListener('click',()=>void withBusy(async()=>{const r=roomData();try{if(!(await ensureFunds(Number(r.bet_amount||0),'confirmar esta aposta')))return;state.room=await rpc('jl_ludo_commit_stake',{p_token:state.token,p_room:r.id});render();scheduleRefresh(20);}catch(error){showToast(error.message,'error');}}));
  ui.betProposalForm?.addEventListener('submit',e=>{e.preventDefault();void withBusy(async()=>{const amount=wholeStake(ui.stakeProposalAmount.value,'O novo valor');if(amount==null)return;try{state.room=await rpc('jl_ludo_propose_bet',{p_token:state.token,p_room:roomData().id,p_bet_amount:amount});render();scheduleRefresh(20);}catch(error){showToast(error.message,'error');}});});
  ui.searchPlayerForm?.addEventListener('submit',e=>{e.preventDefault();void withBusy(async()=>{try{const rows=await rpc('jl_ludo_find_players',{p_token:state.token,p_query:ui.searchPlayer.value.trim()});ui.playerSearchResults.innerHTML=rows?.length?rows.map(p=>`<div class="list-item"><div><strong>${esc(p.name||'Jogador')}</strong><small>${esc(p.code||'')}</small></div><button class="button ghost small" type="button" data-invite-player="${esc(p.player_id)}">Convidar</button></div>`).join(''):'<div class="empty">Nenhum jogador encontrado.</div>';}catch(error){showToast(error.message,'error');}});});
  document.addEventListener('click',e=>{const b=e.target.closest('[data-invite-player]');if(!b)return;void withBusy(async()=>{try{await rpc('jl_ludo_invite',{p_token:state.token,p_room:roomData().id,p_target_player:b.dataset.invitePlayer});showToast('Convite enviado.','success');}catch(error){showToast(error.message,'error');}});});ui.refreshWaiting?.addEventListener('click',()=>void loadWaiting(false));ui.broadcastRoom?.addEventListener('click',()=>void withBusy(async()=>{try{await rpc('jl_ludo_rebroadcast_challenge',{p_token:state.token,p_room:roomData().id});showToast('Convite público ativo.','success');scheduleRefresh(20);}catch(error){showToast(error.message,'error');}}));
  ui.dice?.addEventListener('click',()=>void withBusy(async()=>{const r=roomData();if(!r)return;ui.dice.classList.add('rolling');playTone(330,.08);try{state.room=await rpc('jl_ludo_roll',{p_token:state.token,p_room:r.id});const n=Number(Array.isArray(roomData()?.dice_values)?roomData().dice_values[0]:roomData()?.dice_result);playTone(520+(Number.isFinite(n)?n*30:0),.07);render();scheduleRefresh(20);}catch(error){showToast(error.message,'error');scheduleRefresh(20);}finally{ui.dice.classList.remove('rolling');}}));ui.soundToggle?.addEventListener('click',toggleSound);
  ui.reenterButton?.addEventListener('click',()=>void withBusy(async()=>{const amount=Number(rules().reentry_amount||10);try{if(!(await ensureFunds(amount,'pagar a reentrada')))return;state.room=await rpc('jl_ludo_reenter',{p_token:state.token,p_room:roomData().id});render();scheduleRefresh(20);}catch(error){showToast(error.message,'error');}}));
  ui.chatForm?.addEventListener('submit',e=>{e.preventDefault();const message=ui.chatInput.value.trim();if(!message)return;void withBusy(async()=>{try{await rpc('jl_ludo_send_chat',{p_token:state.token,p_room:roomData().id,p_message:message});ui.chatInput.value='';scheduleRefresh(20);}catch(error){showToast(error.message,'error');}});});
  ui.rematchForm?.addEventListener('submit',e=>{e.preventDefault();void withBusy(async()=>{const bet=wholeStake(ui.rematchBet.value,'A nova aposta');if(bet==null)return;try{if(!(await ensureFunds(bet,'criar a revanche')))return;localStorage.setItem(COLOR_KEY,ui.rematchColor.value);let snapshot=await rpc('jl_ludo_rematch_v2',{p_token:state.token,p_room:roomData().id,p_bet_amount:bet,p_mode:ui.rematchMode.value,p_rules:{turn_seconds:Number(ui.rematchTurn.value),move_seconds:Number(ui.rematchTurn.value),pawn_count:Number(ui.rematchPawns.value),dice_count:Number(ui.rematchDice.value)}});snapshot=await applyPreferences(snapshot);state.room=snapshot;state.roomIdHint=snapshot?.room?.id||'';render();scheduleRefresh(20);}catch(error){showToast(error.message,'error');}});});
  ui.micButton?.addEventListener('click',()=>void toggleMic());ui.muteOpponent?.addEventListener('click',toggleOpponentMute);document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='visible')scheduleRefresh(80);});window.addEventListener('focus',()=>scheduleRefresh(80));window.addEventListener('pageshow',()=>scheduleRefresh(80));window.addEventListener('beforeunload',closeVoice);

  syncColorPicker(preferredColor());if(ui.createPawnStyle)ui.createPawnStyle.value=preferredPawnStyle();ui.soundToggle.textContent=state.soundEnabled?'🔊 Som':'🔇 Som';ui.soundToggle.setAttribute('aria-pressed',state.soundEnabled?'true':'false');paintBoard(ui.loggedOutBoard,null,true);setInterval(updateClock,250);setInterval(()=>{if(document.visibilityState!=='visible'||!state.token)return;const active=Boolean(state.roomIdHint||state.room?.room?.id);if(active&&state.realtimeConnected)return;scheduleRefresh(0);},3000);state.token=getToken();void refresh();
})();
