(() => {
  'use strict';
  const cfg = window.JL_CONFIG || {};
  const TOKEN_KEY = 'jl_player_token';
  const SOUND_KEY = 'jl_ludo_sound_enabled';
  const $ = (id) => document.getElementById(id);
  const state = window.JLLudoState.create();
  let ludoRealtimeConnected=false;
  let ludoRealtimeRoomId='';
  let ludoRealtimeRefreshTimer=0;

  function queueLudoRealtimeRefresh(){
    clearTimeout(ludoRealtimeRefreshTimer);
    ludoRealtimeRefreshTimer=setTimeout(()=>{ window.JLLudoSync?.kick?.('ludo-state'); },60);
  }

  function syncLudoRealtime(roomId){
    const id=String(roomId||'').trim();
    if(!id){
      ludoRealtimeRoomId=''; ludoRealtimeConnected=false;
      clearTimeout(ludoRealtimeRefreshTimer); ludoRealtimeRefreshTimer=0;
      void window.JLLudoRealtime?.disconnect?.(); return;
    }
    if(!window.JLLudoRealtime){ ludoRealtimeRoomId=id; ludoRealtimeConnected=false; return; }
    if(id===ludoRealtimeRoomId&&window.JLLudoRealtime.isConnected?.())return;
    ludoRealtimeRoomId=id;
    window.JLLudoRealtime.connect(id,{
      onSignal:(p)=>{showRealtimeDice(p,id);queueLudoRealtimeRefresh();},
      onStatus:(connected)=>{
        if(ludoRealtimeRoomId!==id)return;
        ludoRealtimeConnected=Boolean(connected);
        if(!connected)window.JLLudoSync?.kick?.('ludo-state');
      }
    });
  }

  function loadDeferredLudoStyles(){
    if(document.getElementById('ludoDeferredStyles'))return;
    const link=document.createElement('link');
    link.id='ludoDeferredStyles'; link.rel='stylesheet';
    link.href='./ludo-deferred.css?v=20260929-1';
    document.head.appendChild(link);
  }
  if('requestIdleCallback' in window)requestIdleCallback(loadDeferredLudoStyles,{timeout:700});
  else setTimeout(loadDeferredLudoStyles,120);

  const els = Object.fromEntries([
    'toast','identityBadge','accountButton','accountMenu','accountMenuCode','accountMenuBalance','accountMenuDeposit','accountMenuWithdraw','accountMenuLogout','ludoStatusStrip','onlinePlayerCount','directNotificationMetric','publicNotificationMetric','directListShortcut','publicListShortcut','topDirectInviteCount','topPublicInviteCount','loggedOut','lobby','boardLobby','ludoLobbyBoard','balanceBadge','createRoomForm','createColor','createPawnStyle','createPawnCount','createPlayers','createMode','createBet','createTurnSeconds','createPublic',
    'joinCodeForm','joinCode','queueForm','queuePlayers','queueMode','queueBet','queueButton','queueStatus','notificationCenter','inviteList','directInviteCount','publicChallengeList','publicChallengeCount','refreshLobby',
    'room','roomCode','roomMeta','roomPot','roomPrize','copyRoomCode','leaveRoom','forfeitRoom','deadlineBar','deadlineLabel','deadlineClock','playersPanel',
    'rulesVersion','rulesSummary','rulesForm','rulesDecision','acceptRules','declineRules','rulesAcceptModal','rulesAcceptTitle','rulesAcceptSummary','rulesModalAccept','rulesModalDecline','rulesModalEdit','stakeAcceptModal','stakeAcceptTitle','stakeAcceptText','stakeBalanceText','stakeModalAccept','stakeProposalAmount','stakeProposalSend','searchPlayerForm','searchPlayer','playerSearchResults','refreshWaiting','waitingPlayers',
    'fundingPanel','fundingText','fundButton','gamePanel','turnTitle','turnTimer','pinLudo','dice','ludoBoard','rollDice','soundToggle','micQuickButton','moveHint','reenterButton','voiceState','micButton','muteOpponent','remoteAudio',
    'chatMessages','chatForm','chatInput','resultPanel','resultTitle','resultPayouts','rematchBet','rematchTurn','rematchMode','rematchPawns','rematchDice','rematchColor','rematchButton','rematchHelp','authModal','closeAuth','loginTab','registerTab','loginForm','registerForm','loginPhone','loginPin',
    'registerName','registerPhone','registerPin','registerPinConfirm','registerInviteCode','registerInviteStatus','authMessage','winModal','winModalTitle','winModalMessage','winModalOk','ludoDiceLive','ludoTurnLive','ludoErrorLive','ludoVictoryLive'
  ].map(k => [k, $(k)]));
  els.rollDice = els.dice;

  const PATH = [[6,1],[6,2],[6,3],[6,4],[6,5],[5,6],[4,6],[3,6],[2,6],[1,6],[0,6],[0,7],[0,8],[1,8],[2,8],[3,8],[4,8],[5,8],[6,9],[6,10],[6,11],[6,12],[6,13],[6,14],[7,14],[8,14],[8,13],[8,12],[8,11],[8,10],[8,9],[9,8],[10,8],[11,8],[12,8],[13,8],[14,8],[14,7],[14,6],[13,6],[12,6],[11,6],[10,6],[9,6],[8,5],[8,4],[8,3],[8,2],[8,1],[8,0],[7,0],[6,0]];
  const START = { red:0, green:13, yellow:26, blue:39 };
  const HOME = { red:[[7,1],[7,2],[7,3],[7,4],[7,5]], green:[[1,7],[2,7],[3,7],[4,7],[5,7]], yellow:[[7,13],[7,12],[7,11],[7,10],[7,9]], blue:[[13,7],[12,7],[11,7],[10,7],[9,7]] };
  const BASE = { red:[[1,1],[1,4],[4,1],[4,4]], green:[[1,10],[1,13],[4,10],[4,13]], yellow:[[10,10],[10,13],[13,10],[13,13]], blue:[[10,1],[10,4],[13,1],[13,4]] };
  const SAFE = new Set([0,8,13,21,26,34,39,47]);
  const TRACK_LAST_STEP=50, HOME_FIRST_STEP=51, HOME_LAST_STEP=55, FINISH_STEP=56;
  const FINISH_CELL={red:[7,6],green:[6,7],yellow:[7,8],blue:[8,7]};
  const DICE_LAYOUTS={1:[5],2:[1,9],3:[1,5,9],4:[1,3,7,9],5:[1,3,5,7,9],6:[1,3,4,6,7,9]};

  function syncLudoStickyTop(){const topbar=document.querySelector('.topbar');if(!topbar)return;document.documentElement.style.setProperty('--ludo-sticky-top',`${Math.ceil(topbar.getBoundingClientRect().height)}px`);}
  function installLudoStickyTop(){const topbar=document.querySelector('.topbar');if(!topbar)return;syncLudoStickyTop();if('ResizeObserver' in window){const observer=new ResizeObserver(syncLudoStickyTop);observer.observe(topbar);}window.addEventListener('resize',syncLudoStickyTop,{passive:true});}
  function firstPlayerName(player){const raw=String(player?.name||player?.code||'Jogador').trim();return raw.split(/\s+/)[0]||'Jogador';}
  function setTurnTitle(title,player=null){if(!els.turnTitle)return;if(!player){els.turnTitle.textContent=title;return;}const color=String(player?.color||'').toLowerCase();const safeColor=['red','green','yellow','blue'].includes(color)?color:'';els.turnTitle.innerHTML=`Vez de <span class="turn-player-name ${safeColor}">${escapeHtml(firstPlayerName(player))}</span>`;}
  function renderDiceFace(value,{keepRolling=false}={}){if(!els.dice)return;const n=Number(value);if(!keepRolling)els.dice.classList.remove('rolling');els.dice.replaceChildren();if(!Number.isInteger(n)||n<1||n>6){els.dice.classList.add('empty');els.dice.removeAttribute('data-value');els.dice.setAttribute('aria-label',els.rollDice&&!els.rollDice.disabled?'Lançar dado':'Dado ainda não lançado');const q=document.createElement('span');q.className='dice-placeholder';q.textContent='?';els.dice.appendChild(q);return;}els.dice.classList.remove('empty');els.dice.dataset.value=String(n);els.dice.setAttribute('aria-label',els.rollDice&&!els.rollDice.disabled?`Dado: ${n}. Toque para lançar`:`Dado: ${n}`);const visible=new Set(DICE_LAYOUTS[n]);for(let i=1;i<=9;i++){const pip=document.createElement('span');pip.className=`pip p${i}${visible.has(i)?' on':''}`;els.dice.appendChild(pip);}}
  function showRealtimeDice(p,id){if(p?.kind!=='dice_rolled'||String(p.room_id||'')!==id)return;const n=Number(Array.isArray(p.dice_values)?p.dice_values[0]:p.dice);if(!Number.isInteger(n)||n<1||n>6)return;state.lastDiceRoomId=id;state.lastDiceValue=n;if(String(p.player_id||'')===String(me()||'')&&state.diceRolling)return;renderDiceFace(n);playDiceLanding();const x=roomPlayers().find(x=>String(x.player_id)===String(p.player_id)),who=x?firstPlayerName(x):'Adversário';if(els.moveHint)els.moveHint.textContent=`${who} tirou ${n}.`;announceLive(els.ludoDiceLive,`${who} tirou ${n} no dado.`,{force:true});}
  function renderDiceRollingNeutral(){if(!els.dice)return;els.dice.replaceChildren();els.dice.removeAttribute('data-value');els.dice.classList.remove('empty','dice-landed');els.dice.classList.add('rolling','rolling-neutral');els.dice.dataset.jlRolling='1';els.dice.setAttribute('aria-label','Dado a girar');const stage=document.createElement('span');stage.className='dice-roll-stage';stage.setAttribute('aria-hidden','true');const cube=document.createElement('span');cube.className='dice-roll-cube';for(const side of ['front','back','right','left','top','bottom']){const face=document.createElement('span');face.className=`dice-roll-face ${side}`;cube.appendChild(face);}stage.appendChild(cube);els.dice.appendChild(stage);}
  function startDiceRollAnimation(maxMs=380){if(!els.dice)return()=>{};let stopped=false;let settleTimer=null;const stop=()=>{if(stopped)return;stopped=true;if(settleTimer)clearTimeout(settleTimer);els.dice.classList.remove('rolling','rolling-neutral','roll-waiting');delete els.dice.dataset.jlRolling;};renderDiceRollingNeutral();settleTimer=setTimeout(()=>{if(stopped)return;els.dice.classList.remove('rolling');els.dice.classList.add('roll-waiting');},maxMs);return stop;}
  function playDiceLanding(){if(!els.dice)return;els.dice.classList.remove('dice-landed');void els.dice.offsetWidth;els.dice.classList.add('dice-landed');setTimeout(()=>els.dice?.classList.remove('dice-landed'),190);}
  const ludoSound=window.JLLudoSound.create({state,els,showToast});
  const {updateSoundButton,toggleSound,ensureAudio,playRollSound,playStepSound,playCaptureSound,playHomeSound,playFireworksSound}=ludoSound;
  function processGameEffects(room){const events=(room?.events||[]).slice().sort((a,b)=>Number(a.id)-Number(b.id));if(!events.length)return;const maxId=Math.max(...events.map(e=>Number(e.id)||0);if(!state.lastFxEventId){state.lastFxEventId=maxId;return;}const fresh=events.filter(e=>(Number(e.id)||0)>state.lastFxEventId);for(const event of fresh){if(event.event_type==='token_captured')playCaptureSound();if(event.event_type==='token_moved'&&Number(event.payload?.to_steps)===56)playHomeSound();if(event.event_type==='game_finished')setTimeout(playFireworksSound,120);}state.lastFxEventId=Math.max(state.lastFxEventId,maxId);}
  const TOKEN_STEP_MS=95;
  const ludoAnimation=window.JLLudoAnimation.create({els,path:PATH,start:START,home:HOME,base:BASE,finishCell:FINISH_CELL,trackLastStep:TRACK_LAST_STEP,homeFirstStep:HOME_FIRST_STEP,homeLastStep:HOME_LAST_STEP,finishStep:FINISH_STEP,stepMs:TOKEN_STEP_MS,playStepSound});
  const {tokenCoord,animateTokenPath,detectForwardMove}=ludoAnimation;
  function escapeHtml(v){return String(v ?? '').replace(/[&<>'\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','\"':'&quot;'}[c]));}
  function money(v){return Number(v||0).toLocaleString('pt-MZ',{minimumFractionDigits:2,maximumFractionDigits:2});}
  function announceLive(el,message,{force=false}={}){if(!el||!message)return;const text=String(message);if(!force&&el.dataset.lastAnnouncement===text)return;el.dataset.lastAnnouncement=text;if(force&&el.textContent===text){el.textContent='';requestAnimationFrame(()=>{if(el)el.textContent=text;});}else el.textContent=text;}
  function showToast(msg,type=''){els.toast.textContent=msg;els.toast.className=`toast show ${type}`;if(type==='error'){els.toast.removeAttribute('role');els.toast.setAttribute('aria-live','off');announceLive(els.ludoErrorLive,msg,{force:true});}else{els.toast.setAttribute('role','status');els.toast.setAttribute('aria-live','polite');}clearTimeout(showToast.t);showToast.t=setTimeout(()=>{els.toast.className='toast';els.toast.setAttribute('role','status');els.toast.setAttribute('aria-live','polite');},3500);}
  function wholeStake(value,label='A aposta'){const amount=Number(value);if(!Number.isFinite(amount)||!Number.isInteger(amount)||amount<10){showToast(`${label} deve ser um valor inteiro a partir de 10 MZN.`,'error');return null;}return amount;}
  function redirectToDeposit(check,context='continuar no Ludo'){const rawMissing=Number(check?.shortfall);const hasConfirmedShortfall=check?.balance_confirmed===true&&Number.isFinite(rawMissing)&&rawMissing>0;const missing=hasConfirmedShortfall?Math.ceil(rawMissing):null;const message=missing!==null?`Saldo insuficiente para ${context}. Faltam ${money(missing)} MZN. Você será levado ao depósito.`:`Saldo insuficiente para ${context}. O valor será confirmado pelo servidor na carteira.`;showToast(message,'error');const url=missing!==null?`./index.html?deposit_needed=${encodeURIComponent(missing)}&from=ludo#depositPanel`:'./index.html?open=deposit&from=ludo#depositPanel';setTimeout(()=>{window.location.href=url;},350);}
  async function ensureLudoFunds(amount,context){const check=await rpc('jl_check_funds',{p_token:state.token,p_game_type:'ludo',p_amount:Number(amount)});if(check?.ok)return true;if(check?.redirect_to_deposit){redirectToDeposit(check,context);return false;}showToast('Saldo insuficiente para continuar.','error');return false;}
  function handleLudoMoneyError(err,context='continuar no Ludo'){const message=String(err?.message||err||'');const m=message.match(/Faltam\s+([\d.,]+)\s+MZN/i);if(/saldo insuficiente/i.test(message)){const shortfall=m?Number(m[1].replace(/\./g,'').replace(',','.')):null;redirectToDeposit({shortfall,balance_confirmed:Number.isFinite(shortfall)&&shortfall>0,redirect_to_deposit:true},context);return true;}return false;}
  function latestDiceRoll(bundle=state.room){const events=bundle?.events||[];for(let i=events.length-1;i>=0;i--){const event=events[i];if(event?.event_type!=='dice_rolled')continue;const payload=event.payload||{};const values=Array.isArray(payload.dice_values)?payload.dice_values.map(Number).filter(v=>Number.isInteger(v)&&v>=1&&v<=6):[];if(values.length)return{values,playerId:event.player_id,createdAt:event.created_at};const die=Number(payload.dice);if(Number.isInteger(die)&&die>=1&&die<=6)return{values:[die],playerId:event.player_id,createdAt:event.created_at};}return null;}
  function visibleDiceValue(room,bundle=state.room){const roomId=room?.id||null;if(state.lastDiceRoomId!==roomId){state.lastDiceRoomId=roomId;state.lastDiceValue=null;}const active=Number(room?.dice_result);if(Number.isInteger(active)&&active>=1&&active<=6){state.lastDiceValue=active;return active;}const latest=latestDiceRoll(bundle);const values=latest?.values||[];const pos=Number(room?.dice_position);const eventValue=Number(Number.isInteger(pos)&&pos>=0&&pos<values.length?values[pos]:values[0]);if(Number.isInteger(eventValue)&&eventValue>=1&&eventValue<=6){state.lastDiceValue=eventValue;return eventValue;}return state.lastDiceValue;}
  function rememberDiceBundle(bundle){if(!bundle)return state.lastDiceValue;return visibleDiceValue(bundle.room||bundle,bundle);}
  function setAuthMessage(msg='',type=''){els.authMessage.textContent=msg;els.authMessage.style.color=type==='error'?'#ff8994':type==='success'?'#8df1bb':'';}
  async function validateInviteCodeInput(){if(!els.registerInviteCode)return true;const code=els.registerInviteCode.value.trim().toUpperCase();els.registerInviteCode.value=code;if(!code){if(els.registerInviteStatus){els.registerInviteStatus.textContent='';els.registerInviteStatus.style.color='';}return true;}if(els.registerInviteStatus){els.registerInviteStatus.textContent='A validar código…';els.registerInviteStatus.style.color='';}try{const result=await rpc('jl_validate_invite_code',{p_code:code});if(!result?.valid){if(els.registerInviteStatus){els.registerInviteStatus.textContent='Código de convite inválido ou inativo.';els.registerInviteStatus.style.color='#ff8994';}return false;}if(els.registerInviteStatus){els.registerInviteStatus.textContent='Código válido · '+(result.influencer||'Influenciador');els.registerInviteInviteStatus.style.color='#8df1bb';}return true;}catch(err){if(els.registerInviteStatus){els.registerInviteStatus.textContent=err.message||'Não foi possível validar o código.';els.registerInviteStatus.style.color='#ff8994';}return false;}}
  const LUDO_WIN_SEEN_KEY='jl_seen_ludo_wins_v1';
  function ludoWinSeen(){try{return new Set(JSON.parse(localStorage.getItem(LUDO_WIN_SEEN_KEY)||'[]'));}catch{return new Set();}}
  function saveLudoWinSeen(seen){try{localStorage.setItem(LUDO_WIN_SEEN_KEY,JSON.stringify([...seen].slice(-100)));}catch{}}
  function ludoRoundTime(r){const raw=r?.finished_at||r?.ended_at||r?.updated_at||r?.created_at;if(!raw)return'hora não disponível';const d=new Date(raw);return Number.isNaN(d.getTime())?'hora não disponível':d.toLocaleTimeString('pt-MZ',{hour:'2-digit',minute:'2-digit'});}
  function setLudoEndModalMode(winner){if(!els.winModal)return;const icon=els.winModal.querySelector('.win-modal-icon');const eyebrow=els.winModal.querySelector('.eyebrow');if(icon){icon.textContent='🏆';icon.classList.toggle('hidden',!winner);}if(eyebrow){eyebrow.textContent=winner?'VITÓRIA':'';eyebrow.classList.toggle('hidden',!winner);}els.winModalMessage?.classList.toggle('hidden',!winner);}
  function showLudoWinNotice(key,amount,roundLabel,roundTime){if(!els.winModal)return;setLudoEndModalMode(true);els.winModalTitle.textContent='Parabéns!';const message=`Você venceu a partida de Ludo e ganhou ${money(amount)} MZN. Partida ${roundLabel} · hora ${roundTime}. O valor foi creditado no seu saldo.`;els.winModalMessage.textContent=message;announceLive(els.ludoVictoryLive,message,{force:true});els.winModal.dataset.winKey=key;els.winModal.classList.remove('hidden');document.body.classList.add('modal-open');}
  function showLudoLossNotice(key){if(!els.winModal)return;setLudoEndModalMode(false);els.winModalTitle.textContent='Fim do Jogo';els.winModalMessage.textContent='';announceLive(els.ludoVictoryLive,'Fim do Jogo',{force:true});els.winModal.dataset.winKey=key;els.winModal.classList.remove('hidden');document.body.classList.add('modal-open');}
  function closeLudoWinNotice(){if(!els.winModal)return;const key=els.winModal.dataset.winKey;if(key){const seen=ludoWinSeen();seen.add(key);saveLudoWinSeen(seen);}els.winModal.classList.add('hidden');document.body.classList.remove('modal-open');delete els.winModal.dataset.winKey;}
  function checkLudoWinNotice(){const r=roomData();if(!r||r.status!=='finished'||!els.winModal?.classList.contains('hidden'))return;const mine=myRoomPlayer();const won=r.mode==='partners'?Boolean(mine)&&String(mine.team??'')===String(r.winner_team??''):String(r.winner_player_id??'')===String(me()??'');if(!won){const lossKey=`${r.id||r.code||'room'}:${me()}:loss`;if(ludoWinSeen().has(lossKey))return;showLudoLossNotice(lossKey);return;}const payout=(state.room?.payouts||[]).find(p=>p.player_id===me()&&Number(p.net||0)>0);if(!payout)return;const key=`${r.id||r.code||'room'}:${me()}:${payout.net}`;if(ludoWinSeen().has(key))return;window.JLNotifications?.push({id:`ludo-win:${key}`,title:'Vitória no Ludo',message:`Você ganhou ${money(payout.net)} MZN na partida ${r.code||r.id||'—'}.`,type:'win',href:'./ludo.html#resultPanel',createdAt:r.finished_at||r.ended_at||r.updated_at||new Date().toISOString()});showLudoWinNotice(key,payout.net,r.code||r.id||'—',ludoRoundTime(r));}
  const rpc=(name,args={})=>window.JLApi.rpc(name,args);
  const ludoRoomState=window.JLLudoRoomState.create(()=>state.token);
  const attachRoomExtras=(base,previous=null)=>ludoRoomState.attachExtras(base,previous);
  const loadRoomSnapshot=(roomId,previous=null)=>ludoRoomState.load(roomId,previous);
  function saveToken(t){state.token=window.JLSession?.setPlayerToken?.(t)??String(t||'');if(!window.JLSession){if(state.token)localStorage.setItem(TOKEN_KEY,state.token);else localStorage.removeItem(TOKEN_KEY);}window.JLNotifications?.setActive(Boolean(state.token));}
  function openAuth(mode='login'){els.authModal.classList.remove('hidden');switchAuth(mode);} function closeAuth(){els.authModal.classList.add('hidden');setAuthMessage('');} function switchAuth(mode){const login=mode==='login';els.loginForm.classList.toggle('hidden',!login);els.registerForm.classList.toggle('hidden',login);els.loginTab.classList.toggle('active',login);els.registerTab.classList.toggle('active',!login);}
  function me(){return state.room?.identity?.player_id||state.status?.identity?.player_id||null;} function roomData(){return state.room?.room||null;} function roomPlayers(){return state.room?.players||[];} function myRoomPlayer(){return roomPlayers().find(p=>p.player_id===me());} function isHost(){return roomData()?.host_id===me();} function rules(){return roomData()?.rules||{};}
  function syncPlayerCountPicker(selectId){const select=$(selectId);const picker=document.querySelector(`.player-count-picker[data-select-id="${selectId}"]`);if(!select||!picker)return;picker.querySelectorAll('[data-player-count]').forEach(b=>{const active=String(b.dataset.playerCount)===String(select.value);b.classList.toggle('active',active);b.setAttribute('aria-pressed',active?'true':'false');});}
  function setPlayerCount(selectId,value){const select=$(selectId);if(!select)return;select.value=String(value);syncPlayerCountPicker(selectId);select.dispatchEvent(new Event('change',{bubbles:true}));}
  function wirePlayerCountPicker(selectId){const picker=document.querySelector(`.player-count-picker[data-select-id="${selectId}"]`);if(!picker)return;picker.addEventListener('click',e=>{const b=e.target.closest('[data-player-count]');if(!b)return;setPlayerCount(selectId,b.dataset.playerCount);});syncPlayerCountPicker(selectId);}
  function syncTurnTimer(value,urgent=false){if(!els.turnTimer)return;const r=roomData(),running=r?.status==='playing'&&Boolean(r?.started_at);els.turnTimer.classList.toggle('hidden',!running);els.turnTimer.textContent=running?value:'--:--';els.turnTimer.classList.toggle('urgent',running&&urgent);}
  function updateClock(){const r=roomData();if(r?.status==='negotiating'){els.deadlineClock.textContent='Sem prazo';els.deadlineBar.style.borderColor='';syncTurnTimer('--:--');return;}if(!r?.action_deadline){els.deadlineClock.textContent='—';els.deadlineBar.style.borderColor='';syncTurnTimer('--:--');return;}const s=Math.max(0,Math.ceil((new Date(r.action_deadline)-Date.now())/1000));const value=`${String(Math.floor(s/60)).padStart(2,'0')}:${String(s%60).padStart(2,'0')}`;els.deadlineClock.textContent=value;els.deadlineBar.style.borderColor=s<=10?'#b44b59':'';syncTurnTimer(value,s<=10);}
  function roomMetaBase(r){const mobile=window.matchMedia?.('(max-width:600px)')?.matches;if(mobile){const amount=Number(r.bet_amount||0).toLocaleString('pt-MZ',{maximumFractionDigits:2});return r.play_mode==='free'?`${r.player_count}J · ${r.pawn_count||4}P · ${r.mode==='partners'?'Dupla':'Solo'} · FREE · ${r.is_public?'Púb.':'Priv.'}`:`${r.player_count}J · ${r.pawn_count||4}P · ${r.mode==='partners'?'Dupla':'Solo'} · ${amount} MZN · ${r.is_public?'Púb.':'Priv.'}`;}return r.play_mode==='free'?`${r.player_count} jogadores · ${r.pawn_count||4} peões/jogador · ${r.mode==='partners'?'Parceiros 2 × 2':'Cada um por si'} · FREE · Sem aposta · ${r.is_public?'Pública':'Privada'}`:`${r.player_count} jogadores · ${r.pawn_count||4} peões/jogador · ${r.mode==='partners'?'Parceiros 2 × 2':'Cada um por si'} · ${money(r.bet_amount)} MZN por jogador · ${r.is_public?'Pública':'Privada'}`;}
  function renderAll(){const authed=Boolean(state.token&&state.status?.identity);window.JLNotifications?.setActive(authed);els.ludoStatusStrip?.classList.remove('hidden');els.loggedOut.classList.toggle('hidden',authed);els.lobby.classList.toggle('hidden',!authed||Boolean(state.room));els.notificationCenter?.classList.toggle('hidden',!authed);els.room.classList.toggle('hidden',!state.room);els.boardLobby.classList.toggle('hidden',Boolean(state.room));if(!state.room)renderLobbyBoard();if(authed){const i=state.status.identity;const confirmedBalance=Number(i.balance);const hasConfirmedBalance=i.balance_confirmed===true&&Number.isFinite(confirmedBalance);const balanceText=hasConfirmedBalance?`${money(confirmedBalance)} MZN`:'Saldo a confirmar';els.identityBadge.textContent=`${i.code} · ${balanceText}`;els.accountButton.textContent=i.name||i.code;els.accountMenuCode.textContent=`${i.name||'Jogador'} · ${i.code}`;els.accountMenuBalance.textContent=balanceText;els.balanceBadge.textContent=balanceText;renderLobby();}else{els.identityBadge.textContent='Não autenticado';els.accountButton.textContent='Entrar';els.accountMenu?.classList.add('hidden');els.accountButton.setAttribute('aria-expanded','false');}if(state.room)renderRoom();}
  function renderLobby(){const s=state.status;if(!s)return;}
  function renderRoom(){const r=roomData();if(!r)return;els.roomCode.textContent=r.code;els.roomMeta.textContent=roomMetaBase(r);if(els.roomPot)els.roomPot.textContent=`${money(r.pot)} MZN`;if(els.roomPrize)els.roomPrize.textContent=commissionText();els.rulesVersion.textContent=`v${r.rules_version}`;const started=r.status==='playing'&&Boolean(r.started_at);els.leaveRoom?.classList.toggle('hidden',started);els.forfeitRoom?.classList.toggle('hidden',!started);renderPlayers();renderRules();renderDeadline();renderFunding();renderGame();renderResult();renderInviter();syncEntryFlowModals();}
  function renderResult(){const r=roomData();els.resultPanel.classList.toggle('hidden',r.status!=='finished');if(r.status!=='finished')return;checkLudoWinNotice();if(els.rematchBet&&els.rematchBet.dataset.room!==String(r.id)){els.rematchBet.value=String(Math.max(10,Math.trunc(Number(r.bet_amount)||10)));els.rematchTurn.value=String(Number(r.rules?.turn_seconds||30));els.rematchMode.value=r.mode||'solo';els.rematchPawns.value=String(Number(r.pawn_count||r.rules?.pawn_count||4));els.rematchDice.value=String(Number(r.rules?.dice_count||1));els.rematchColor.value=preferredLudoColor();const partners=els.rematchMode?.querySelector('option[value="partners"]');if(partners)partners.disabled=Number(r.player_count)!==4;els.rematchBet.dataset.room=String(r.id);}if(els.rematchHelp)els.rematchHelp.textContent='Ajuste valor, tempo, modo, peões, dados e cor. As demais regras continuam editáveis na nova sala antes da aceitação.';const winner=r.mode==='partners'?`Equipa ${r.winner_team}`:(roomPlayers().find(p=>p.player_id===r.winner_player_id)?.code||'Vencedor');els.resultTitle.textContent=`${winner} venceu`;const p=state.room.payouts||[];els.resultPayouts.innerHTML=`<div class="payout-grid">${p.map(x=>{const pl=roomPlayers().find(y=>y.player_id===x.player_id);return `<div class="payout-card"><strong>${escapeHtml(pl?.code||'Jogador')}</strong><br>Bruto ${money(x.gross)} MZN<br>Casa ${money(x.commission)} MZN<br><strong>Líquido ${money(x.net)} MZN</strong></div>`}).join('')}</div>`;}
  async function renderInviter(){const r=roomData(),host=isHost()&&['waiting','negotiating'].includes(r.status);document.querySelector('.invite-panel').classList.toggle('hidden',!host);if(host)await loadWaiting(true);}
  async function loadWaiting(silent=false){if(!state.room||!isHost())return;try{const rows=await rpc('jl_ludo_waiting_players',{p_token:state.token,p_room:roomData().id});els.waitingPlayers.innerHTML=rows.length?rows.map(p=>`<div class="mini-item"><div><strong>${escapeHtml(p.name)}</strong><br><small>${escapeHtml(p.code)}</small></div><button class="button ghost small" data-invite-player="${p.player_id}">Convidar</button></div>`).join(''):'<div class="empty">Nenhum compatível agora.</div>';}
  function isFinishedRoomRegression(previousRoom,nextRoom){const previous=previousRoom?.room;const next=nextRoom?.room;if(!previous||!next||String(previous.id)!==String(next.id))return false;return previous.status==='finished'&&next.status!=='finished';}
  async function loadStatus(silent=false){if(state.animating||state.diceRolling)return;const snapshotTicket=movementGuard.beginSnapshot();if(!state.token){state.status=null;state.room=null;syncLudoRealtime(null);renderAll();return;}try{const nextStatus=await rpc('jl_ludo_my_status',{p_token:state.token});let nextRoom=null;if(nextStatus?.active_room_id){nextRoom=await loadRoomSnapshot(nextStatus.active_room_id,state.room);}if(!nextStatus?.active_room_id){try{nextStatus.public_challenges=await rpc('jl_ludo_public_challenges',{p_token:state.token});}catch{nextStatus.public_challenges=state.status?.public_challenges||[];}}else nextStatus.public_challenges=state.status?.public_challenges||[];if(state.animating||state.diceRolling||!movementGuard.canApplySnapshot(snapshotTicket))return;const previousRoom=state.room;if(isFinishedRoomRegression(previousRoom,nextRoom))return;...}
