create table if not exists public.jl_global_chat_messages (
  id bigint generated by default as identity primary key,
  player_id uuid not null references public.players(id) on delete cascade,
  message text not null check (char_length(btrim(message)) between 1 and 500),
  created_at timestamptz not null default now()
);

create index if not exists jl_global_chat_messages_created_idx
  on public.jl_global_chat_messages (created_at desc, id desc);

create table if not exists public.jl_global_chat_reads (
  player_id uuid primary key references public.players(id) on delete cascade,
  last_read_id bigint not null default 0,
  updated_at timestamptz not null default now()
);

alter table public.jl_global_chat_messages enable row level security;
alter table public.jl_global_chat_reads enable row level security;

revoke all on table public.jl_global_chat_messages from public, anon, authenticated;
revoke all on table public.jl_global_chat_reads from public, anon, authenticated;
revoke all on sequence public.jl_global_chat_messages_id_seq from public, anon, authenticated;

create or replace function public.jl_global_chat_list(
  p_token text,
  p_after_id bigint default 0,
  p_limit integer default 80
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_player uuid := public.jl_player_id(p_token);
  v_after bigint := greatest(coalesce(p_after_id, 0), 0);
  v_limit integer := least(greatest(coalesce(p_limit, 80), 1), 100);
  v_latest_id bigint := 0;
  v_last_read_id bigint := 0;
  v_unread integer := 0;
  v_messages jsonb := '[]'::jsonb;
begin
  if v_player is null then
    return jsonb_build_object('ok', false, 'error', 'Sessão inválida.');
  end if;

  select coalesce(max(id), 0)
    into v_latest_id
  from public.jl_global_chat_messages;

  insert into public.jl_global_chat_reads(player_id, last_read_id)
  values (v_player, v_latest_id)
  on conflict (player_id) do nothing;

  select r.last_read_id
    into v_last_read_id
  from public.jl_global_chat_reads r
  where r.player_id = v_player;

  select count(*)::integer
    into v_unread
  from public.jl_global_chat_messages m
  where m.id > coalesce(v_last_read_id, 0)
    and m.player_id <> v_player;

  if v_after > 0 then
    select coalesce(
      jsonb_agg(
        jsonb_build_object(
          'id', x.id,
          'username', x.username,
          'message', x.message,
          'created_at', x.created_at,
          'is_mine', x.is_mine
        ) order by x.id
      ),
      '[]'::jsonb
    )
    into v_messages
    from (
      select m.id,
             p.name as username,
             m.message,
             m.created_at,
             (m.player_id = v_player) as is_mine
      from public.jl_global_chat_messages m
      join public.players p on p.id = m.player_id
      where m.id > v_after
      order by m.id asc
      limit v_limit
    ) x;
  else
    select coalesce(
      jsonb_agg(
        jsonb_build_object(
          'id', x.id,
          'username', x.username,
          'message', x.message,
          'created_at', x.created_at,
          'is_mine', x.is_mine
        ) order by x.id
      ),
      '[]'::jsonb
    )
    into v_messages
    from (
      select m.id,
             p.name as username,
             m.message,
             m.created_at,
             (m.player_id = v_player) as is_mine
      from public.jl_global_chat_messages m
      join public.players p on p.id = m.player_id
      order by m.id desc
      limit v_limit
    ) x;
  end if;

  return jsonb_build_object(
    'ok', true,
    'messages', v_messages,
    'latest_id', v_latest_id,
    'last_read_id', coalesce(v_last_read_id, 0),
    'unread', v_unread
  );
end;
$$;

create or replace function public.jl_global_chat_mark_read(
  p_token text,
  p_last_id bigint default null
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_player uuid := public.jl_player_id(p_token);
  v_target bigint := 0;
begin
  if v_player is null then
    return jsonb_build_object('ok', false, 'error', 'Sessão inválida.');
  end if;

  if p_last_id is null then
    select coalesce(max(id), 0) into v_target
    from public.jl_global_chat_messages;
  else
    v_target := greatest(p_last_id, 0);
  end if;

  insert into public.jl_global_chat_reads(player_id, last_read_id, updated_at)
  values (v_player, v_target, now())
  on conflict (player_id) do update
    set last_read_id = greatest(public.jl_global_chat_reads.last_read_id, excluded.last_read_id),
        updated_at = now();

  return jsonb_build_object('ok', true, 'last_read_id', v_target, 'unread', 0);
end;
$$;

create or replace function public.jl_global_chat_send(
  p_token text,
  p_message text
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_player uuid := public.jl_player_id(p_token);
  v_text text := btrim(coalesce(p_message, ''));
  v_id bigint;
  v_created_at timestamptz;
  v_name text;
begin
  if v_player is null then
    return jsonb_build_object('ok', false, 'error', 'Sessão inválida.');
  end if;

  if char_length(v_text) < 1 or char_length(v_text) > 500 then
    return jsonb_build_object('ok', false, 'error', 'A mensagem deve ter entre 1 e 500 caracteres.');
  end if;

  if exists (
    select 1
    from public.jl_global_chat_messages m
    where m.player_id = v_player
      and m.created_at > now() - interval '800 milliseconds'
  ) then
    return jsonb_build_object('ok', false, 'error', 'Aguarde um instante antes de enviar outra mensagem.');
  end if;

  insert into public.jl_global_chat_messages(player_id, message)
  values (v_player, v_text)
  returning id, created_at into v_id, v_created_at;

  select p.name into v_name
  from public.players p
  where p.id = v_player;

  return jsonb_build_object(
    'ok', true,
    'message', jsonb_build_object(
      'id', v_id,
      'username', coalesce(v_name, 'Jogador'),
      'message', v_text,
      'created_at', v_created_at,
      'is_mine', true
    )
  );
end;
$$;

revoke all on function public.jl_global_chat_list(text, bigint, integer) from public;
revoke all on function public.jl_global_chat_mark_read(text, bigint) from public;
revoke all on function public.jl_global_chat_send(text, text) from public;

grant execute on function public.jl_global_chat_list(text, bigint, integer) to anon, authenticated;
grant execute on function public.jl_global_chat_mark_read(text, bigint) to anon, authenticated;
grant execute on function public.jl_global_chat_send(text, text) to anon, authenticated;
