-- Dama Lendária — motor 8x8, 1x1, autoridade no servidor.
-- Base: Damas Brasileiras (64 casas): captura obrigatória, lei da maioria,
-- pedra captura para frente/trás, dama voadora, promoção somente ao terminar o lance.

create table if not exists public.dama_rooms (
  id uuid primary key default extensions.gen_random_uuid(),
  code text not null unique,
  host_id uuid not null references public.players(id) on delete restrict,
  bet_amount numeric(12,2) not null check (bet_amount >= 10 and bet_amount = trunc(bet_amount)),
  turn_seconds integer not null check (turn_seconds in (120,180)),
  host_color text not null check (host_color in ('white','black')),
  host_starts boolean not null default true,
  is_public boolean not null default false,
  status text not null default 'waiting' check (status in ('waiting','funding','ready','playing','finished','cancelled')),
  pot numeric(12,2) not null default 0 check (pot >= 0),
  current_player_id uuid references public.players(id) on delete restrict,
  action_deadline timestamptz,
  started_at timestamptz,
  finished_at timestamptz,
  winner_player_id uuid references public.players(id) on delete restrict,
  result text check (result is null or result in ('win','draw')),
  finish_reason text,
  commission_total numeric(12,2) not null default 0 check (commission_total >= 0),
  move_no integer not null default 0,
  king_only_count integer not null default 0,
  endgame_key text,
  endgame_count integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.dama_room_players (
  room_id uuid not null references public.dama_rooms(id) on delete cascade,
  player_id uuid not null references public.players(id) on delete restrict,
  seat integer not null check (seat in (1,2)),
  color text not null check (color in ('white','black')),
  stake_paid boolean not null default false,
  stake_amount numeric(12,2) not null default 0,
  status text not null default 'active' check (status in ('active','finished','left','forfeited')),
  joined_at timestamptz not null default now(),
  primary key(room_id,player_id),
  unique(room_id,seat),
  unique(room_id,color)
);

create table if not exists public.dama_pieces (
  id uuid primary key default extensions.gen_random_uuid(),
  room_id uuid not null references public.dama_rooms(id) on delete cascade,
  player_id uuid not null references public.players(id) on delete restrict,
  piece_no integer not null check (piece_no between 1 and 12),
  row_no integer not null check (row_no between 0 and 7),
  col_no integer not null check (col_no between 0 and 7),
  is_king boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(room_id,player_id,piece_no),
  unique(room_id,row_no,col_no)
);

create table if not exists public.dama_events (
  id bigint generated by default as identity primary key,
  room_id uuid not null references public.dama_rooms(id) on delete cascade,
  player_id uuid references public.players(id) on delete set null,
  event_type text not null,
  payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create table if not exists public.dama_positions (
  id bigint generated by default as identity primary key,
  room_id uuid not null references public.dama_rooms(id) on delete cascade,
  position_key text not null,
  player_to_move uuid not null references public.players(id) on delete restrict,
  move_no integer not null,
  created_at timestamptz not null default now()
);

create table if not exists public.dama_payouts (
  id uuid primary key default extensions.gen_random_uuid(),
  room_id uuid not null references public.dama_rooms(id) on delete cascade,
  player_id uuid not null references public.players(id) on delete restrict,
  gross_amount numeric(12,2) not null,
  commission numeric(12,2) not null,
  net_amount numeric(12,2) not null,
  created_at timestamptz not null default now(),
  unique(room_id,player_id)
);

create table if not exists public.dama_invitations (
  id uuid primary key default extensions.gen_random_uuid(),
  room_id uuid not null references public.dama_rooms(id) on delete cascade,
  invited_by uuid not null references public.players(id) on delete cascade,
  target_player_id uuid not null references public.players(id) on delete cascade,
  status text not null default 'pending' check (status in ('pending','accepted','declined','cancelled')),
  created_at timestamptz not null default now(),
  responded_at timestamptz
);

create table if not exists public.dama_draw_offers (
  id uuid primary key default extensions.gen_random_uuid(),
  room_id uuid not null references public.dama_rooms(id) on delete cascade,
  proposed_by uuid not null references public.players(id) on delete cascade,
  status text not null default 'pending' check (status in ('pending','accepted','declined','cancelled')),
  created_move_no integer not null,
  created_at timestamptz not null default now(),
  responded_at timestamptz
);

create table if not exists public.dama_signals (
  id bigint generated by default as identity primary key,
  room_id uuid not null references public.dama_rooms(id) on delete cascade,
  from_player_id uuid not null references public.players(id) on delete cascade,
  to_player_id uuid not null references public.players(id) on delete cascade,
  signal_type text not null check (signal_type in ('offer','answer','ice','renegotiate')),
  payload jsonb not null,
  created_at timestamptz not null default now(),
  expires_at timestamptz not null default (now()+interval '2 minutes')
);

create index if not exists dama_rooms_active_idx on public.dama_rooms(status,created_at desc);
create index if not exists dama_rooms_deadline_idx on public.dama_rooms(action_deadline) where status='playing';
create index if not exists dama_players_player_idx on public.dama_room_players(player_id,room_id);
create index if not exists dama_events_room_idx on public.dama_events(room_id,id desc);
create index if not exists dama_positions_room_key_idx on public.dama_positions(room_id,position_key,player_to_move);
create index if not exists dama_invites_target_idx on public.dama_invitations(target_player_id,status,created_at desc);
create index if not exists dama_signals_target_idx on public.dama_signals(to_player_id,room_id,id);

alter table public.dama_rooms enable row level security;
alter table public.dama_room_players enable row level security;
alter table public.dama_pieces enable row level security;
alter table public.dama_events enable row level security;
alter table public.dama_positions enable row level security;
alter table public.dama_payouts enable row level security;
alter table public.dama_invitations enable row level security;
alter table public.dama_draw_offers enable row level security;
alter table public.dama_signals enable row level security;

revoke all on table public.dama_rooms,public.dama_room_players,public.dama_pieces,
 public.dama_events,public.dama_positions,public.dama_payouts,public.dama_invitations,
 public.dama_draw_offers,public.dama_signals from anon, authenticated;

create or replace function public.jl_dama_event(
  p_room uuid,p_player uuid,p_type text,p_payload jsonb default '{}'::jsonb
) returns void
language plpgsql security definer set search_path=public
as $$
begin
  insert into public.dama_events(room_id,player_id,event_type,payload)
  values(p_room,p_player,p_type,coalesce(p_payload,'{}'::jsonb));
end;
$$;

create or replace function public.jl_dama_code()
returns text
language plpgsql volatile set search_path=public,extensions
as $$
declare c text;
begin
  loop
    c:='DAMA-'||upper(substr(encode(extensions.gen_random_bytes(5),'hex'),1,6));
    exit when not exists(select 1 from public.dama_rooms where code=c);
  end loop;
  return c;
end;
$$;

create or replace function public.jl_dama_is_member(p_room uuid,p_player uuid)
returns boolean language sql stable set search_path=public
as $$
  select exists(
    select 1 from public.dama_room_players
    where room_id=p_room and player_id=p_player and status<>'left'
  );
$$;

create or replace function public.jl_dama_position_key(p_room uuid,p_turn uuid)
returns text
language sql stable set search_path=public
as $$
  select md5(
    coalesce(string_agg(
      rp.color||':'||dp.row_no||':'||dp.col_no||':'||case when dp.is_king then 'K' else 'M' end,
      '|' order by rp.color,dp.row_no,dp.col_no,dp.piece_no
    ),'')||'|turn='||coalesce(p_turn::text,'')
  )
  from public.dama_pieces dp
  join public.dama_room_players rp
    on rp.room_id=dp.room_id and rp.player_id=dp.player_id
  where dp.room_id=p_room;
$$;

create or replace function public.jl_dama_capture_routes_from(
  p_room uuid,
  p_piece uuid,
  p_owner uuid,
  p_row integer,
  p_col integer,
  p_is_king boolean,
  p_captured uuid[],
  p_path jsonb
) returns setof jsonb
language plpgsql stable set search_path=public
as $$
declare
  dr integer;
  dc integer;
  mr integer;
  mc integer;
  lr integer;
  lc integer;
  sr integer;
  sc integer;
  occ record;
  enemy record;
  child jsonb;
  found_next boolean:=false;
  new_path jsonb;
  new_caps uuid[];
begin
  if not p_is_king then
    foreach dr in array array[-1,1] loop
      foreach dc in array array[-1,1] loop
        mr:=p_row+dr; mc:=p_col+dc;
        lr:=p_row+2*dr; lc:=p_col+2*dc;
        if mr not between 0 and 7 or mc not between 0 and 7
           or lr not between 0 and 7 or lc not between 0 and 7 then
          continue;
        end if;

        select dp.id,dp.player_id into occ
        from public.dama_pieces dp
        where dp.room_id=p_room and dp.id<>p_piece
          and dp.row_no=mr and dp.col_no=mc
        limit 1;

        if occ.id is null or occ.player_id=p_owner or occ.id=any(coalesce(p_captured,'{}'::uuid[])) then
          continue;
        end if;

        if exists(
          select 1 from public.dama_pieces dp
          where dp.room_id=p_room and dp.id<>p_piece
            and dp.row_no=lr and dp.col_no=lc
        ) then
          continue;
        end if;

        found_next:=true;
        new_caps:=array_append(coalesce(p_captured,'{}'::uuid[]),occ.id);
        new_path:=p_path||jsonb_build_array(jsonb_build_array(lr,lc));

        for child in
          select * from public.jl_dama_capture_routes_from(
            p_room,p_piece,p_owner,lr,lc,false,new_caps,new_path
          )
        loop
          return next child;
        end loop;
      end loop;
    end loop;
  else
    foreach dr in array array[-1,1] loop
      foreach dc in array array[-1,1] loop
        sr:=p_row+dr; sc:=p_col+dc;
        enemy:=null;

        while sr between 0 and 7 and sc between 0 and 7 loop
          select dp.id,dp.player_id into occ
          from public.dama_pieces dp
          where dp.room_id=p_room and dp.id<>p_piece
            and dp.row_no=sr and dp.col_no=sc
          limit 1;

          if occ.id is null then
            if enemy.id is not null then
              found_next:=true;
              new_caps:=array_append(coalesce(p_captured,'{}'::uuid[]),enemy.id);
              new_path:=p_path||jsonb_build_array(jsonb_build_array(sr,sc));
              for child in
                select * from public.jl_dama_capture_routes_from(
                  p_room,p_piece,p_owner,sr,sc,true,new_caps,new_path
                )
              loop
                return next child;
              end loop;
            end if;
          else
            if enemy.id is not null then
              exit;
            end if;
            if occ.player_id=p_owner or occ.id=any(coalesce(p_captured,'{}'::uuid[])) then
              exit;
            end if;
            enemy:=occ;
          end if;

          sr:=sr+dr; sc:=sc+dc;
        end loop;
      end loop;
    end loop;
  end if;

  if not found_next and coalesce(array_length(p_captured,1),0)>0 then
    return next jsonb_build_object(
      'path',p_path,
      'captures',to_jsonb(p_captured),
      'capture_count',coalesce(array_length(p_captured,1),0),
      'to',jsonb_build_array(p_row,p_col)
    );
  end if;
  return;
end;
$$;

create or replace function public.jl_dama_legal_moves_data(p_room uuid,p_player uuid)
returns jsonb
language plpgsql stable set search_path=public
as $$
declare
  p record;
  route jsonb;
  obj jsonb;
  captures jsonb:='[]'::jsonb;
  simples jsonb:='[]'::jsonb;
  maxcap integer:=0;
  dr integer;
  dc integer;
  nr integer;
  nc integer;
  sr integer;
  sc integer;
  path jsonb;
  rid text;
begin
  for p in
    select dp.*,rp.color
    from public.dama_pieces dp
    join public.dama_room_players rp
      on rp.room_id=dp.room_id and rp.player_id=dp.player_id
    where dp.room_id=p_room and dp.player_id=p_player
    order by dp.piece_no
  loop
    path:=jsonb_build_array(jsonb_build_array(p.row_no,p.col_no));
    for route in
      select * from public.jl_dama_capture_routes_from(
        p_room,p.id,p.player_id,p.row_no,p.col_no,p.is_king,'{}'::uuid[],path
      )
    loop
      rid:=md5(p.id::text||':'||(route->'path')::text||':'||(route->'captures')::text);
      obj:=route||jsonb_build_object(
        'route_id',rid,
        'piece_id',p.id,
        'piece_no',p.piece_no,
        'from',jsonb_build_array(p.row_no,p.col_no),
        'is_capture',true,
        'was_king',p.is_king
      );
      captures:=captures||jsonb_build_array(obj);
      maxcap:=greatest(maxcap,(route->>'capture_count')::integer);
    end loop;
  end loop;

  if maxcap>0 then
    return coalesce((
      select jsonb_agg(value order by (value->>'piece_no')::int,value->>'route_id')
      from jsonb_array_elements(captures)
      where (value->>'capture_count')::int=maxcap
    ),'[]'::jsonb);
  end if;

  for p in
    select dp.*,rp.color
    from public.dama_pieces dp
    join public.dama_room_players rp
      on rp.room_id=dp.room_id and rp.player_id=dp.player_id
    where dp.room_id=p_room and dp.player_id=p_player
    order by dp.piece_no
  loop
    if not p.is_king then
      dr:=case when p.color='white' then -1 else 1 end;
      foreach dc in array array[-1,1] loop
        nr:=p.row_no+dr; nc:=p.col_no+dc;
        if nr between 0 and 7 and nc between 0 and 7
           and not exists(
             select 1 from public.dama_pieces x
             where x.room_id=p_room and x.row_no=nr and x.col_no=nc
           ) then
          path:=jsonb_build_array(jsonb_build_array(p.row_no,p.col_no),jsonb_build_array(nr,nc));
          rid:=md5(p.id::text||':'||path::text);
          simples:=simples||jsonb_build_array(jsonb_build_object(
            'route_id',rid,'piece_id',p.id,'piece_no',p.piece_no,
            'from',jsonb_build_array(p.row_no,p.col_no),
            'to',jsonb_build_array(nr,nc),'path',path,
            'captures','[]'::jsonb,'capture_count',0,'is_capture',false,'was_king',false
          ));
        end if;
      end loop;
    else
      foreach dr in array array[-1,1] loop
        foreach dc in array array[-1,1] loop
          sr:=p.row_no+dr; sc:=p.col_no+dc;
          while sr between 0 and 7 and sc between 0 and 7 loop
            exit when exists(
              select 1 from public.dama_pieces x
              where x.room_id=p_room and x.row_no=sr and x.col_no=sc
            );
            path:=jsonb_build_array(jsonb_build_array(p.row_no,p.col_no),jsonb_build_array(sr,sc));
            rid:=md5(p.id::text||':'||path::text);
            simples:=simples||jsonb_build_array(jsonb_build_object(
              'route_id',rid,'piece_id',p.id,'piece_no',p.piece_no,
              'from',jsonb_build_array(p.row_no,p.col_no),
              'to',jsonb_build_array(sr,sc),'path',path,
              'captures','[]'::jsonb,'capture_count',0,'is_capture',false,'was_king',true
            ));
            sr:=sr+dr; sc:=sc+dc;
          end loop;
        end loop;
      end loop;
    end if;
  end loop;

  return simples;
end;
$$;

create or replace function public.jl_dama_endgame_info(p_room uuid)
returns jsonb
language plpgsql stable set search_path=public
as $$
declare
  a uuid;
  b uuid;
  ak int; am int; bk int; bm int;
  lone_king_bigdiag boolean:=false;
  key text:=null;
  lim int:=null;
begin
  select min(player_id),max(player_id) into a,b
  from public.dama_room_players where room_id=p_room and status<>'left';

  if a is null or b is null or a=b then return '{}'::jsonb; end if;

  select count(*) filter(where is_king),count(*) filter(where not is_king)
    into ak,am from public.dama_pieces where room_id=p_room and player_id=a;
  select count(*) filter(where is_king),count(*) filter(where not is_king)
    into bk,bm from public.dama_pieces where room_id=p_room and player_id=b;

  if ak=1 and am=0 and bk=1 and bm=0 then
    key:='1K-1K'; lim:=2;
  elsif ((ak=2 and am=0 and bk=1 and bm=0) or (bk=2 and bm=0 and ak=1 and am=0)) then
    key:='2K-1K'; lim:=5;
  elsif ((ak=1 and am=1 and bk=1 and bm=0) or (bk=1 and bm=1 and ak=1 and am=0)) then
    key:='1K1M-1K'; lim:=5;
  elsif ak=1 and am=1 and bk=1 and bm=1 then
    key:='1K1M-1K1M'; lim:=5;
  elsif ak=2 and am=0 and bk=2 and bm=0 then
    key:='2K-2K'; lim:=5;
  else
    select exists(
      select 1 from public.dama_pieces
      where room_id=p_room and is_king and row_no+col_no=7
        and player_id=case
          when ak=3 and am=0 and bk=1 and bm=0 then b
          when bk=3 and bm=0 and ak=1 and am=0 then a
          when ak=2 and am=1 and bk=1 and bm=0 then b
          when bk=2 and bm=1 and ak=1 and am=0 then a
          when ak=1 and am=2 and bk=1 and bm=0 then b
          when bk=1 and bm=2 and ak=1 and am=0 then a
          else null
        end
    ) into lone_king_bigdiag;

    if lone_king_bigdiag then
      if (ak=3 and am=0 and bk=1 and bm=0) or (bk=3 and bm=0 and ak=1 and am=0) then key:='3K-1K-bigdiag'; lim:=5;
      elsif (ak=2 and am=1 and bk=1 and bm=0) or (bk=2 and bm=1 and ak=1 and am=0) then key:='2K1M-1K-bigdiag'; lim:=5;
      elsif (ak=1 and am=2 and bk=1 and bm=0) or (bk=1 and bm=2 and ak=1 and am=0) then key:='1K2M-1K-bigdiag'; lim:=5;
      end if;
    end if;
  end if;

  return jsonb_build_object('key',key,'limit',lim);
end;
$$;

revoke all on function public.jl_dama_event(uuid,uuid,text,jsonb) from public,anon,authenticated;
revoke all on function public.jl_dama_code() from public,anon,authenticated;
revoke all on function public.jl_dama_is_member(uuid,uuid) from public,anon,authenticated;
revoke all on function public.jl_dama_position_key(uuid,uuid) from public,anon,authenticated;
revoke all on function public.jl_dama_capture_routes_from(uuid,uuid,uuid,integer,integer,boolean,uuid[],jsonb) from public,anon,authenticated;
revoke all on function public.jl_dama_legal_moves_data(uuid,uuid) from public,anon,authenticated;
revoke all on function public.jl_dama_endgame_info(uuid) from public,anon,authenticated;
