-- Ponto 5: limitar tentativas de login de jogadores e administração.
-- Jogador: 5 falhas por janela; bloqueios progressivos 5, 15, 30, 60 min,
-- depois 2h, 4h, 8h, 16h e máximo 24h.
-- Admin: 3 falhas por janela; bloqueios 15, 30, 60 min, 2h, 4h, 8h,
-- 16h e máximo 24h. Cada bloqueio administrativo gera alerta e audit log.
-- O rate limit é por origem (IP quando disponível) + conta/telefone para jogador,
-- e por origem para admin, evitando que uma origem bloqueie todos os acessos.

create table if not exists public.login_rate_limits (
  scope text not null check (scope in ('player','admin')),
  subject_key text not null,
  failed_attempts integer not null default 0 check (failed_attempts >= 0),
  block_level integer not null default 0 check (block_level >= 0),
  blocked_until timestamptz,
  last_failed_at timestamptz,
  updated_at timestamptz not null default now(),
  primary key (scope, subject_key)
);

alter table public.login_rate_limits enable row level security;
revoke all privileges on table public.login_rate_limits from public, anon, authenticated;
grant select, insert, update, delete on table public.login_rate_limits to service_role;

create table if not exists public.admin_login_alerts (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  failed_attempts integer not null,
  block_level integer not null,
  blocked_until timestamptz not null,
  ip_address text,
  country_code text,
  user_agent text,
  seen_at timestamptz
);

alter table public.admin_login_alerts enable row level security;
revoke all privileges on table public.admin_login_alerts from public, anon, authenticated;
grant select, insert, update, delete on table public.admin_login_alerts to service_role;

create index if not exists admin_login_alerts_unseen_idx
  on public.admin_login_alerts (created_at desc)
  where seen_at is null;

create or replace function public.jl_login_player(p_phone text, p_pin text)
returns jsonb
language plpgsql
security definer
set search_path to 'public', 'extensions'
as $function$
declare
  v_phone text := public.jl_phone(p_phone);
  v_player public.players%rowtype;
  v_token text;
  v_headers jsonb := coalesce(nullif(current_setting('request.headers', true), '')::jsonb, '{}'::jsonb);
  v_ip text;
  v_source text;
  v_key text;
  v_rate public.login_rate_limits%rowtype;
  v_failed integer;
  v_level integer;
  v_minutes integer;
  v_retry integer;
begin
  v_ip := nullif(btrim(split_part(coalesce(v_headers->>'x-forwarded-for',''), ',', 1)), '');
  if v_ip is null then v_ip := nullif(v_headers->>'cf-connecting-ip',''); end if;
  if v_ip is null then v_ip := nullif(v_headers->>'x-real-ip',''); end if;
  v_source := coalesce(v_ip, nullif(v_headers->>'user-agent',''), 'unknown');
  v_key := encode(extensions.digest(v_phone || '|' || v_source, 'sha256'), 'hex');

  insert into public.login_rate_limits(scope, subject_key)
  values ('player', v_key)
  on conflict (scope, subject_key) do nothing;

  select * into v_rate
  from public.login_rate_limits
  where scope='player' and subject_key=v_key
  for update;

  if v_rate.last_failed_at is not null
     and v_rate.last_failed_at < now() - interval '24 hours'
     and coalesce(v_rate.blocked_until, '-infinity'::timestamptz) <= now() then
    update public.login_rate_limits
       set failed_attempts=0, block_level=0, blocked_until=null, updated_at=now()
     where scope='player' and subject_key=v_key;
    v_rate.failed_attempts := 0;
    v_rate.block_level := 0;
    v_rate.blocked_until := null;
  end if;

  if v_rate.blocked_until is not null and v_rate.blocked_until > now() then
    v_retry := greatest(1, ceil(extract(epoch from (v_rate.blocked_until-now())) / 60.0)::integer);
    perform set_config('response.status','429',true);
    return jsonb_build_object(
      'ok', false,
      'message', format('Muitas tentativas. Tente novamente em %s minuto(s).', v_retry),
      'retry_after_minutes', v_retry
    );
  end if;

  select * into v_player from public.players where phone = v_phone limit 1;

  if v_player.id is null or extensions.crypt(coalesce(p_pin,''), v_player.pin_hash) <> v_player.pin_hash then
    v_failed := coalesce(v_rate.failed_attempts,0) + 1;

    if v_failed >= 5 then
      v_level := coalesce(v_rate.block_level,0) + 1;
      v_minutes := case v_level
        when 1 then 5
        when 2 then 15
        when 3 then 30
        when 4 then 60
        when 5 then 120
        when 6 then 240
        when 7 then 480
        when 8 then 960
        else 1440
      end;

      update public.login_rate_limits
         set failed_attempts=0,
             block_level=v_level,
             blocked_until=now()+make_interval(mins=>v_minutes),
             last_failed_at=now(),
             updated_at=now()
       where scope='player' and subject_key=v_key;

      perform set_config('response.status','429',true);
      return jsonb_build_object(
        'ok', false,
        'message', format('Muitas tentativas. Tente novamente em %s minuto(s).', v_minutes),
        'retry_after_minutes', v_minutes
      );
    end if;

    update public.login_rate_limits
       set failed_attempts=v_failed, last_failed_at=now(), updated_at=now()
     where scope='player' and subject_key=v_key;

    perform set_config('response.status','401',true);
    return jsonb_build_object(
      'ok', false,
      'message', 'Telefone ou PIN incorreto.',
      'attempts_remaining', 5-v_failed
    );
  end if;

  if v_player.blocked then
    perform set_config('response.status','403',true);
    return jsonb_build_object('ok', false, 'message', 'Esta conta está bloqueada.');
  end if;

  delete from public.login_rate_limits
  where scope='player' and subject_key=v_key;

  v_token := encode(extensions.gen_random_bytes(32), 'hex');
  insert into public.player_sessions(player_id, token_hash, expires_at)
  values (v_player.id, public.jl_token_hash(v_token), now() + interval '30 days');

  return jsonb_build_object(
    'ok', true,
    'token', v_token,
    'player', jsonb_build_object(
      'id',v_player.id,
      'name',v_player.name,
      'phone',v_player.phone,
      'balance',v_player.balance,
      'blocked',v_player.blocked
    )
  );
end;
$function$;

create or replace function public.jl_admin_login(p_code text)
returns jsonb
language plpgsql
security definer
set search_path to 'public', 'extensions'
as $function$
declare
  v_hash text;
  v_token text;
  v_headers jsonb := coalesce(nullif(current_setting('request.headers', true), '')::jsonb, '{}'::jsonb);
  v_ip text;
  v_country text;
  v_agent text;
  v_source text;
  v_key text;
  v_rate public.login_rate_limits%rowtype;
  v_failed integer;
  v_level integer;
  v_minutes integer;
  v_retry integer;
  v_unseen integer := 0;
  v_last_alert public.admin_login_alerts%rowtype;
begin
  v_ip := nullif(btrim(split_part(coalesce(v_headers->>'x-forwarded-for',''), ',', 1)), '');
  if v_ip is null then v_ip := nullif(v_headers->>'cf-connecting-ip',''); end if;
  if v_ip is null then v_ip := nullif(v_headers->>'x-real-ip',''); end if;

  v_country := coalesce(
    nullif(v_headers->>'cf-ipcountry',''),
    nullif(v_headers->>'x-vercel-ip-country',''),
    nullif(v_headers->>'x-country-code','')
  );
  v_agent := nullif(v_headers->>'user-agent','');
  v_source := coalesce(v_ip, v_agent, 'unknown');
  v_key := encode(extensions.digest(v_source, 'sha256'), 'hex');

  insert into public.login_rate_limits(scope, subject_key)
  values ('admin', v_key)
  on conflict (scope, subject_key) do nothing;

  select * into v_rate
  from public.login_rate_limits
  where scope='admin' and subject_key=v_key
  for update;

  if v_rate.last_failed_at is not null
     and v_rate.last_failed_at < now() - interval '24 hours'
     and coalesce(v_rate.blocked_until, '-infinity'::timestamptz) <= now() then
    update public.login_rate_limits
       set failed_attempts=0, block_level=0, blocked_until=null, updated_at=now()
     where scope='admin' and subject_key=v_key;
    v_rate.failed_attempts := 0;
    v_rate.block_level := 0;
    v_rate.blocked_until := null;
  end if;

  if v_rate.blocked_until is not null and v_rate.blocked_until > now() then
    v_retry := greatest(1, ceil(extract(epoch from (v_rate.blocked_until-now())) / 60.0)::integer);
    perform set_config('response.status','429',true);\n    return jsonb_build_object(
      'ok', false,
      'message', format('Acesso administrativo temporariamente limitado. Tente novamente em %s minuto(s).', v_retry),
      'retry_after_minutes', v_retry
    );
  end if;

  select code_hash into v_hash from public.admin_config order by id limit 1;

  if v_hash is null or encode(extensions.digest(coalesce(p_code,''), 'sha256'),'hex') <> v_hash then
    v_failed := coalesce(v_rate.failed_attempts,0) + 1;

    if v_failed >= 3 then
      v_level := coalesce(v_rate.block_level,0) + 1;
      v_minutes := case v_level
        when 1 then 15
        when 2 then 30
        when 3 then 60
        when 4 then 120
        when 5 then 240
        when 6 then 480
        when 7 then 960
        else 1440
      end;

      update public.login_rate_limits
         set failed_attempts=0,
             block_level=v_level,
             blocked_until=now()+make_interval(mins=>v_minutes),
             last_failed_at=now(),
             updated_at=now()
       where scope='admin' and subject_key=v_key;

      insert into public.admin_login_alerts(
        failed_attempts, block_level, blocked_until, ip_address, country_code, user_agent
      ) values (
        3, v_level, now()+make_interval(mins=>v_minutes), v_ip, v_country, v_agent
      );

      insert into public.audit_log(action, details)
      values ('admin_login_rate_limited', jsonb_build_object(
        'failed_attempts',3,
        'block_level',v_level,
        'blocked_minutes',v_minutes,
        'ip_address',v_ip,
        'country_code',v_country,
        'user_agent',v_agent
      ));

      perform set_config('response.status','429',true);
      return jsonb_build_object(
        'ok', false,
        'message', format('Acesso administrativo temporariamente limitado. Tente novamente em %s minuto(s).', v_minutes),
        'retry_after_minutes', v_minutes
      );
    end if;

    update public.login_rate_limits
       set failed_attempts=v_failed, last_failed_at=now(), updated_at=now()
     where scope='admin' and subject_key=v_key;

    perform set_config('response.status','401',true);
    return jsonb_build_object(
      'ok', false,
      'message', 'Código administrativo incorreto.',
      'attempts_remaining', 3-v_failed
    );
  end if;

  delete from public.login_rate_limits
  where scope='admin' and subject_key=v_key;

  select count(*)::integer into v_unseen
  from public.admin_login_alerts
  where seen_at is null;

  if v_unseen > 0 then
    select * into v_last_alert
    from public.admin_login_alerts
    where seen_at is null
    order by created_at desc
    limit 1;

    update public.admin_login_alerts
       set seen_at=now()
     where seen_at is null;
  end if;

  v_token := encode(extensions.gen_random_bytes(32),'hex');
  insert into public.admin_sessions(token_hash,expires_at)
  values(public.jl_token_hash(v_token),now()+interval '12 hours');

  return jsonb_build_object(
    'ok', true,
    'token',v_token,
    'expires_in_hours',12,
    'security_alert',
      case when v_unseen > 0 then jsonb_build_object(
        'count',v_unseen,
        'created_at',v_last_alert.created_at,
        'ip_address',v_last_alert.ip_address,
        'country_code',v_last_alert.country_code,
        'failed_attempts',v_last_alert.failed_attempts,
        'blocked_until',v_last_alert.blocked_until
      ) else null end
  );
end;
$function$;
