-- Dama Lendária — núcleo autoritativo 8x8
-- Regras brasileiras: captura obrigatória, Lei da Maioria, pedra captura nos dois sentidos,
-- dama voadora, promoção ao terminar a sequência, repetição e empates regulamentares.

create table if not exists public.dama_rooms (
  id uuid primary key default extensions.gen_random_uuid(),
  code text not null unique,
  host_id uuid not null references public.players(id) on delete restrict,
  guest_id uuid references public.players(id) on delete restrict,
  bet_amount numeric(12,2) not null,
  turn_seconds integer not null default 120,
  host_color text not null default 'white',
  first_player_choice text not null default 'host',
  is_public boolean not null default false,
  status text not null default 'waiting',
  current_player_id uuid references public.players(id) on delete restrict,
  started_at timestamptz,
  action_deadline timestamptz,
  pot numeric(12,2) not null default 0,
  winner_player_id uuid references public.players(id) on delete restrict,
  result_reason text,
  move_seq integer not null default 0,
  board_version integer not null default 0,
  quiet_king_moves integer not null default 0,
  regulation_key text,
  regulation_moves integer not null default 0,
  regulation_limit integer not null default 0,
  draw_offer_by uuid references public.players(id) on delete restrict,
  draw_offer_created_at timestamptz,
  draw_host_reoffer_at integer not null default 0,
  draw_guest_reoffer_at integer not null default 0,
  last_move jsonb,
  commission_total numeric(12,2) not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  finished_at timestamptz,
  constraint dama_rooms_bet_check check (bet_amount>=10 and bet_amount=trunc(bet_amount)),
  constraint dama_rooms_turn_check check (turn_seconds in (120,180)),
  constraint dama_rooms_color_check check (host_color in ('white','red')),
  constraint dama_rooms_first_check check (first_player_choice in ('host','guest')),
  constraint dama_rooms_status_check check (status in ('waiting','negotiating','funding','ready','playing','finished','cancelled')),
  constraint dama_rooms_pot_check check (pot>=0)
);

create table if not exists public.dama_room_players (
  room_id uuid not null references public.dama_rooms(id) on delete cascade,
  player_id uuid not null references public.players(id) on delete restrict,
  seat integer not null,
  color text not null,
  settings_accepted boolean not null default false,
  stake_paid boolean not null default false,
  stake_amount numeric(12,2) not null default 0,
  move_count integer not null default 0,
  status text not null default 'active',
  joined_at timestamptz not null default now(),
  primary key(room_id,player_id),
  unique(room_id,seat),
  unique(room_id,color),
  constraint dama_room_players_seat_check check (seat in (1,2)),
  constraint dama_room_players_color_check check (color in ('white','red')),
  constraint dama_room_players_status_check check (status in ('active','left','finished'))
);

create table if not exists public.dama_pieces (
  id uuid primary key default extensions.gen_random_uuid(),
  room_id uuid not null references public.dama_rooms(id) on delete cascade,
  player_id uuid not null references public.players(id) on delete restrict,
  piece_no integer not null,
  row_no integer not null,
  col_no integer not null,
  is_king boolean not null default false,
  alive boolean not null default true,
  updated_at timestamptz not null default now(),
  unique(room_id,player_id,piece_no),
  constraint dama_piece_no_check check (piece_no between 1 and 12),
  constraint dama_piece_row_check check (row_no between 0 and 7),
  constraint dama_piece_col_check check (col_no between 0 and 7),
  constraint dama_piece_dark_square_check check ((row_no+col_no)%2=1)
);
create unique index if not exists dama_piece_live_square_uidx
  on public.dama_pieces(room_id,row_no,col_no) where alive;
create index if not exists dama_piece_room_player_idx
  on public.dama_pieces(room_id,player_id) where alive;

create table if not exists public.dama_events (
  id bigint generated by default as identity primary key,
  room_id uuid not null references public.dama_rooms(id) on delete cascade,
  player_id uuid references public.players(id) on delete set null,
  event_type text not null,
  payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);
create index if not exists dama_events_room_idx on public.dama_events(room_id,id desc);

create table if not exists public.dama_payouts (
  id uuid primary key default extensions.gen_random_uuid(),
  room_id uuid not null references public.dama_rooms(id) on delete cascade,
  player_id uuid not null references public.players(id) on delete restrict,
  gross_amount numeric(12,2) not null,
  commission numeric(12,2) not null,
  net_amount numeric(12,2) not null,
  created_at timestamptz not null default now(),
  unique(room_id,player_id)
);

create table if not exists public.dama_positions (
  room_id uuid not null references public.dama_rooms(id) on delete cascade,
  position_key text not null,
  occurrences integer not null default 1,
  updated_at timestamptz not null default now(),
  primary key(room_id,position_key)
);

create table if not exists public.dama_signals (
  id bigint generated by default as identity primary key,
  room_id uuid not null references public.dama_rooms(id) on delete cascade,
  from_player_id uuid not null references public.players(id) on delete cascade,
  to_player_id uuid not null references public.players(id) on delete cascade,
  signal_type text not null,
  payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  expires_at timestamptz not null default now()+interval '2 minutes'
);
create index if not exists dama_signals_pull_idx on public.dama_signals(room_id,to_player_id,id);

alter table public.dama_rooms enable row level security;
alter table public.dama_room_players enable row level security;
alter table public.dama_pieces enable row level security;
alter table public.dama_events enable row level security;
alter table public.dama_payouts enable row level security;
alter table public.dama_positions enable row level security;
alter table public.dama_signals enable row level security;

revoke all on table public.dama_rooms from anon, authenticated;
revoke all on table public.dama_room_players from anon, authenticated;
revoke all on table public.dama_pieces from anon, authenticated;
revoke all on table public.dama_events from anon, authenticated;
revoke all on table public.dama_payouts from anon, authenticated;
revoke all on table public.dama_positions from anon, authenticated;
revoke all on table public.dama_signals from anon, authenticated;

create or replace function public.jl_dama_room_code()
returns text
language plpgsql
security definer
set search_path=public,extensions
as $$
declare c text;
begin
  loop
    c:='DAMA-'||upper(substr(encode(extensions.gen_random_bytes(4),'hex'),1,6));
    exit when not exists(select 1 from public.dama_rooms where code=c);
  end loop;
  return c;
end;
$$;

create or replace function public.jl_dama_is_member(p_room uuid,p_player uuid)
returns boolean
language sql
stable
security definer
set search_path=public
as $$
  select exists(
    select 1 from public.dama_room_players
    where room_id=p_room and player_id=p_player and status<>'left'
  );
$$;

create or replace function public.jl_dama_event(
  p_room uuid,p_player uuid,p_type text,p_payload jsonb default '{}'::jsonb
)
returns bigint
language plpgsql
security definer
set search_path=public
as $$
declare v_id bigint;
begin
  insert into public.dama_events(room_id,player_id,event_type,payload)
  values(p_room,p_player,p_type,coalesce(p_payload,'{}'::jsonb))
  returning id into v_id;
  return v_id;
end;
$$;

create or replace function public.jl_dama_square_name(p_row integer,p_col integer)
returns text
language sql
immutable
as $$
  select chr(97+p_col)||((p_row+1)::text);
$$;

create or replace function public.jl_dama_init_board(p_room uuid)
returns void
language plpgsql
security definer
set search_path=public
as $$
declare
  r public.dama_rooms%rowtype;
  white_player uuid;
  red_player uuid;
  rr integer;
  cc integer;
  n integer;
begin
  select * into r from public.dama_rooms where id=p_room for update;
  if r.id is null or r.guest_id is null then raise exception 'Sala incompleta.'; end if;

  select player_id into white_player
  from public.dama_room_players
  where room_id=p_room and color='white' and status<>'left';

  select player_id into red_player
  from public.dama_room_players
  where room_id=p_room and color='red' and status<>'left';

  if white_player is null or red_player is null then raise exception 'Cores da Dama incompletas.'; end if;

  delete from public.dama_pieces where room_id=p_room;
  n:=0;
  for rr in 0..2 loop
    for cc in 0..7 loop
      if (rr+cc)%2=1 then
        n:=n+1;
        insert into public.dama_pieces(room_id,player_id,piece_no,row_no,col_no)
        values(p_room,red_player,n,rr,cc);
      end if;
    end loop;
  end loop;

  n:=0;
  for rr in 5..7 loop
    for cc in 0..7 loop
      if (rr+cc)%2=1 then
        n:=n+1;
        insert into public.dama_pieces(room_id,player_id,piece_no,row_no,col_no)
        values(p_room,white_player,n,rr,cc);
      end if;
    end loop;
  end loop;
end;
$$;

create or replace function public.jl_dama_capture_options(
  p_room uuid,
  p_piece uuid,
  p_row integer,
  p_col integer,
  p_is_king boolean,
  p_captured uuid[] default array[]::uuid[]
)
returns table(enemy_id uuid,land_row integer,land_col integer)
language plpgsql
stable
security definer
set search_path=public
as $$
declare
  owner_id uuid;
  d record;
  step integer;
  rr integer;
  cc integer;
  rr2 integer;
  cc2 integer;
  occ_id uuid;
  occ_owner uuid;
  seen_enemy uuid;
begin
  select player_id into owner_id
  from public.dama_pieces
  where id=p_piece and room_id=p_room and alive;

  if owner_id is null then return; end if;

  for d in select * from (values(-1,-1),(-1,1),(1,-1),(1,1)) v(dr,dc) loop
    if not p_is_king then
      rr:=p_row+d.dr;
      cc:=p_col+d.dc;
      rr2:=p_row+(2*d.dr);
      cc2:=p_col+(2*d.dc);
      if rr2 not between 0 and 7 or cc2 not between 0 and 7 then continue; end if;

      occ_id:=null; occ_owner:=null;
      select x.id,x.player_id into occ_id,occ_owner
      from public.dama_pieces x
      where x.room_id=p_room and x.alive and x.id<>p_piece
        and x.row_no=rr and x.col_no=cc
      limit 1;

      if occ_id is null or occ_owner=owner_id or occ_id=any(coalesce(p_captured,array[]::uuid[])) then
        continue;
      end if;

      if not exists(
        select 1 from public.dama_pieces x
        where x.room_id=p_room and x.alive and x.id<>p_piece
          and x.row_no=rr2 and x.col_no=cc2
      ) then
        enemy_id:=occ_id; land_row:=rr2; land_col:=cc2; return next;
      end if;
    else
      seen_enemy:=null;
      for step in 1..7 loop
        rr:=p_row+(d.dr*step);
        cc:=p_col+(d.dc*step);
        exit when rr not between 0 and 7 or cc not between 0 and 7;

        occ_id:=null; occ_owner:=null;
        select x.id,x.player_id into occ_id,occ_owner
        from public.dama_pieces x
        where x.room_id=p_room and x.alive and x.id<>p_piece
          and x.row_no=rr and x.col_no=cc
        limit 1;

        if occ_id is not null then
          if seen_enemy is not null then
            exit;
          end if;
          if occ_owner=owner_id or occ_id=any(coalesce(p_captured,array[]::uuid[])) then
            exit;
          end if;
          seen_enemy:=occ_id;
        elsif seen_enemy is not null then
          enemy_id:=seen_enemy; land_row:=rr; land_col:=cc; return next;
        end if;
      end loop;
    end if;
  end loop;
end;
$$;

create or replace function public.jl_dama_capture_routes(p_piece uuid)
returns table(
  route_id text,
  path jsonb,
  captured_ids uuid[],
  capture_count integer,
  final_row integer,
  final_col integer
)
language sql
stable
security definer
set search_path=public
as $$
with recursive base as (
  select p.id,p.room_id,p.row_no,p.col_no,p.is_king
  from public.dama_pieces p
  where p.id=p_piece and p.alive
),
walk as (
  select
    b.id as piece_id,
    b.room_id,
    b.is_king,
    b.row_no as row_no,
    b.col_no as col_no,
    array[]::uuid[] as captured,
    jsonb_build_array(jsonb_build_object('row',b.row_no,'col',b.col_no)) as path,
    0 as depth
  from base b
  union all
  select
    w.piece_id,
    w.room_id,
    w.is_king,
    o.land_row,
    o.land_col,
    w.captured||o.enemy_id,
    w.path||jsonb_build_array(jsonb_build_object('row',o.land_row,'col',o.land_col)),
    w.depth+1
  from walk w
  cross join lateral public.jl_dama_capture_options(
    w.room_id,w.piece_id,w.row_no,w.col_no,w.is_king,w.captured
  ) o
),
terminal as (
  select w.*
  from walk w
  where w.depth>0
    and not exists(
      select 1
      from public.jl_dama_capture_options(
        w.room_id,w.piece_id,w.row_no,w.col_no,w.is_king,w.captured
      )
    )
)
select
  md5(piece_id::text||':'||path::text||':'||captured::text) as route_id,
  path,
  captured as captured_ids,
  depth as capture_count,
  row_no as final_row,
  col_no as final_col
from terminal;
$$;

create or replace function public.jl_dama_legal_moves_data(p_room uuid,p_player uuid)
returns jsonb
language plpgsql
stable
security definer
set search_path=public
as $$
declare
  p record;
  cr record;
  d record;
  step integer;
  rr integer;
  cc integer;
  dr integer;
  max_capture integer:=0;
  arr jsonb:='[]'::jsonb;
  obj jsonb;
  r public.dama_rooms%rowtype;
begin
  select * into r from public.dama_rooms where id=p_room;
  if r.id is null or not public.jl_dama_is_member(p_room,p_player) then return '[]'::jsonb; end if;

  for p in
    select * from public.dama_pieces
    where room_id=p_room and player_id=p_player and alive
    order by piece_no
  loop
    for cr in select * from public.jl_dama_capture_routes(p.id) loop
      if cr.capture_count>max_capture then
        max_capture:=cr.capture_count;
        arr:='[]'::jsonb;
      end if;
      if cr.capture_count=max_capture then
        obj:=jsonb_build_object(
          'route_id',cr.route_id,
          'piece_id',p.id,
          'piece_no',p.piece_no,
          'is_king',p.is_king,
          'is_capture',true,
          'capture_count',cr.capture_count,
          'captures',to_jsonb(cr.captured_ids),
          'path',cr.path,
          'from_row',p.row_no,'from_col',p.col_no,
          'to_row',cr.final_row,'to_col',cr.final_col
        );
        arr:=arr||jsonb_build_array(obj);
      end if;
    end loop;
  end loop;

  if max_capture>0 then return arr; end if;

  for p in
    select rp.*,pl.color
    from public.dama_pieces rp
    join public.dama_room_players pl
      on pl.room_id=rp.room_id and pl.player_id=rp.player_id
    where rp.room_id=p_room and rp.player_id=p_player and rp.alive
    order by rp.piece_no
  loop
    if p.is_king then
      for d in select * from (values(-1,-1),(-1,1),(1,-1),(1,1)) v(dr,dc) loop
        for step in 1..7 loop
          rr:=p.row_no+(d.dr*step);
          cc:=p.col_no+(d.dc*step);
          exit when rr not between 0 and 7 or cc not between 0 and 7;
          exit when exists(
            select 1 from public.dama_pieces x
            where x.room_id=p_room and x.alive and x.row_no=rr and x.col_no=cc
          );

          obj:=jsonb_build_object(
            'route_id',md5(p.id::text||':'||p.row_no||':'||p.col_no||':'||rr||':'||cc),
            'piece_id',p.id,'piece_no',p.piece_no,'is_king',true,
            'is_capture',false,'capture_count',0,'captures','[]'::jsonb,
            'path',jsonb_build_array(
              jsonb_build_object('row',p.row_no,'col',p.col_no),
              jsonb_build_object('row',rr,'col',cc)
            ),
            'from_row',p.row_no,'from_col',p.col_no,'to_row',rr,'to_col',cc
          );
          arr:=arr||jsonb_build_array(obj);
        end loop;
      end loop;
    else
      dr:=case when p.color='red' then 1 else -1 end;
      for d in select * from (values(-1),(1)) v(dc) loop
        rr:=p.row_no+dr;
        cc:=p.col_no+d.dc;
        if rr between 0 and 7 and cc between 0 and 7
           and not exists(
             select 1 from public.dama_pieces x
             where x.room_id=p_room and x.alive and x.row_no=rr and x.col_no=cc
           ) then
          obj:=jsonb_build_object(
            'route_id',md5(p.id::text||':'||p.row_no||':'||p.col_no||':'||rr||':'||cc),
            'piece_id',p.id,'piece_no',p.piece_no,'is_king',false,
            'is_capture',false,'capture_count',0,'captures','[]'::jsonb,
            'path',jsonb_build_array(
              jsonb_build_object('row',p.row_no,'col',p.col_no),
              jsonb_build_object('row',rr,'col',cc)
            ),
            'from_row',p.row_no,'from_col',p.col_no,'to_row',rr,'to_col',cc
          );
          arr:=arr||jsonb_build_array(obj);
        end if;
      end loop;
    end if;
  end loop;

  return arr;
end;
$$;

create or replace function public.jl_dama_position_key(p_room uuid,p_next uuid)
returns text
language sql
stable
security definer
set search_path=public
as $$
  select md5(
    coalesce((
      select string_agg(
        p.player_id::text||':'||p.row_no||':'||p.col_no||':'||(case when p.is_king then 'K' else 'M' end),
        '|' order by p.player_id,p.row_no,p.col_no,p.piece_no
      )
      from public.dama_pieces p
      where p.room_id=p_room and p.alive
    ),'')||'|next:'||coalesce(p_next::text,'')
  );
$$;

create or replace function public.jl_dama_regulation_state(p_room uuid)
returns jsonb
language plpgsql
stable
security definer
set search_path=public
as $$
declare
  a uuid; b uuid;
  ak int; am int; bk int; bm int;
  a_long boolean:=false; b_long boolean:=false;
  lim int:=0;
  sig text:='';
begin
  select player_id into a from public.dama_room_players where room_id=p_room and seat=1 and status<>'left';
  select player_id into b from public.dama_room_players where room_id=p_room and seat=2 and status<>'left';
  if a is null or b is null then return jsonb_build_object('key',null,'limit',0); end if;

  select count(*) filter(where is_king),count(*) filter(where not is_king)
  into ak,am from public.dama_pieces where room_id=p_room and player_id=a and alive;
  select count(*) filter(where is_king),count(*) filter(where not is_king)
  into bk,bm from public.dama_pieces where room_id=p_room and player_id=b and alive;

  if ak=1 and am=0 then
    select coalesce(bool_or(row_no+col_no=7),false) into a_long
    from public.dama_pieces where room_id=p_room and player_id=a and alive and is_king;
  end if;
  if bk=1 and bm=0 then
    select coalesce(bool_or(row_no+col_no=7),false) into b_long
    from public.dama_pieces where room_id=p_room and player_id=b and alive and is_king;
  end if;

  if ak=1 and am=0 and bk=1 and bm=0 then
    lim:=2;
  elsif
    (ak=2 and am=0 and bk=1 and bm=0) or
    (bk=2 and bm=0 and ak=1 and am=0) or
    (ak=1 and am=1 and bk=1 and bm=0) or
    (bk=1 and bm=1 and ak=1 and am=0) or
    (ak=1 and am=1 and bk=1 and bm=1) or
    (ak=2 and am=0 and bk=2 and bm=0) or
    (b_long and ((ak=3 and am=0) or (ak=2 and am=1) or (ak=1 and am=2))) or
    (a_long and ((bk=3 and bm=0) or (bk=2 and bm=1) or (bk=1 and bm=2)))
  then
    lim:=5;
  end if;

  if lim>0 then
    sig:=format('%s:%s:%s:%s:%s:%s:%s',ak,am,bk,bm,a_long,b_long,lim);
  end if;
  return jsonb_build_object('key',nullif(sig,''),'limit',lim);
end;
$$;

create or replace function public.jl_dama_refund_room(
  p_room uuid,p_note text default 'Reembolso Dama'
)
returns void
language plpgsql
security definer
set search_path=public
as $$
declare x record; restored numeric;
begin
  perform 1 from public.dama_rooms where id=p_room for update;
  for x in
    select * from public.dama_room_players
    where room_id=p_room and stake_paid
    order by seat for update
  loop
    perform public.jl_lock_player_wallet(x.player_id);
    update public.players
    set balance=balance+x.stake_amount,updated_at=now()
    where id=x.player_id;

    restored:=public.jl_reverse_cash_wager(x.player_id,'dama_stake',p_room);

    insert into public.transactions(player_id,kind,amount,status,reference_id,note)
    values(
      x.player_id,'dama_refund',x.stake_amount,'completed',p_room,
      p_note||' · '||restored||' MZN voltaram a ficar bloqueados até serem jogados'
    );
  end loop;

  update public.dama_room_players
  set stake_paid=false,stake_amount=0
  where room_id=p_room and stake_paid;

  update public.dama_rooms set pot=0,updated_at=now() where id=p_room;
end;
$$;

create or replace function public.jl_dama_finish_win(
  p_room uuid,p_winner uuid,p_reason text
)
returns void
language plpgsql
security definer
set search_path=public
as $$
declare
  r public.dama_rooms%rowtype;
  gross numeric; comm numeric; net numeric;
  payout_id uuid;
begin
  select * into r from public.dama_rooms where id=p_room for update;
  if r.status in ('finished','cancelled') then return; end if;
  if not public.jl_dama_is_member(p_room,p_winner) then raise exception 'Vencedor inválido.'; end if;

  gross:=round(r.pot,2);
  comm:=least(gross,greatest(1,ceil(gross*0.01)));
  net:=gross-comm;

  insert into public.dama_payouts(room_id,player_id,gross_amount,commission,net_amount)
  values(p_room,p_winner,gross,comm,net)
  on conflict(room_id,player_id) do nothing
  returning id into payout_id;

  if payout_id is not null then
    perform public.jl_lock_player_wallet(p_winner);
    update public.players set balance=balance+net,updated_at=now() where id=p_winner;
    insert into public.transactions(player_id,kind,amount,status,reference_id,note)
    values(p_winner,'dama_payout',net,'completed',p_room,'Prémio Dama líquido; comissão '||comm||' MZN');
  end if;

  update public.dama_room_players
  set status=case when player_id=p_winner then 'finished' else status end
  where room_id=p_room;

  update public.dama_rooms
  set status='finished',winner_player_id=p_winner,result_reason=p_reason,
      commission_total=comm,action_deadline=null,finished_at=now(),updated_at=now()
  where id=p_room;

  perform public.jl_dama_event(
    p_room,p_winner,'game_finished',
    jsonb_build_object('winner_player_id',p_winner,'reason',p_reason,'pot',gross,'commission',comm)
  );
end;
$$;

create or replace function public.jl_dama_finish_draw(p_room uuid,p_reason text)
returns void
language plpgsql
security definer
set search_path=public
as $$
declare r public.dama_rooms%rowtype;
begin
  select * into r from public.dama_rooms where id=p_room for update;
  if r.status in ('finished','cancelled') then return; end if;

  perform public.jl_dama_refund_room(p_room,'Empate Dama sem comissão: '||p_reason);

  update public.dama_rooms
  set status='finished',winner_player_id=null,result_reason=p_reason,
      commission_total=0,action_deadline=null,finished_at=now(),updated_at=now()
  where id=p_room;

  perform public.jl_dama_event(
    p_room,null,'game_drawn',
    jsonb_build_object('reason',p_reason,'commission',0)
  );
end;
$$;

-- O mesmo saldo/controle de depósito passa a reconhecer a Dama como jogo da casa.
create or replace function public.jl_apply_cash_wager(
  p_player_id uuid,
  p_amount numeric,
  p_source_type text,
  p_reference_id uuid
)
returns numeric
language plpgsql
security definer
set search_path=public
as $$
declare
  r public.deposit_wager_requirements%rowtype;
  need numeric:=greatest(0,coalesce(p_amount,0));
  take numeric;
  cleared numeric:=0;
begin
  if p_source_type not in (
    'number_bet','pair_bet','ludo_stake','ludo_reentry','aviator_bet','dama_stake'
  ) then
    raise exception 'Origem de jogo inválida.';
  end if;

  if need<=0 then return 0; end if;

  for r in
    select *
    from public.deposit_wager_requirements
    where player_id=p_player_id and status='active' and remaining_amount>0
    order by created_at,id
    for update
  loop
    exit when need<=0;
    take:=least(need,r.remaining_amount);

    update public.deposit_wager_requirements
    set remaining_amount=remaining_amount-take,
        status=case when remaining_amount-take<=0 then 'cleared' else 'active' end,
        updated_at=now()
    where id=r.id;

    insert into public.deposit_wager_usages(
      requirement_id,player_id,source_type,reference_id,amount
    ) values(r.id,p_player_id,p_source_type,p_reference_id,take);

    cleared:=cleared+take;
    need:=need-take;
  end loop;

  return cleared;
end;
$$;

revoke all on function public.jl_dama_room_code() from public,anon,authenticated;
revoke all on function public.jl_dama_is_member(uuid,uuid) from public,anon,authenticated;
revoke all on function public.jl_dama_event(uuid,uuid,text,jsonb) from public,anon,authenticated;
revoke all on function public.jl_dama_init_board(uuid) from public,anon,authenticated;
revoke all on function public.jl_dama_capture_options(uuid,uuid,integer,integer,boolean,uuid[]) from public,anon,authenticated;
revoke all on function public.jl_dama_capture_routes(uuid) from public,anon,authenticated;
revoke all on function public.jl_dama_legal_moves_data(uuid,uuid) from public,anon,authenticated;
revoke all on function public.jl_dama_position_key(uuid,uuid) from public,anon,authenticated;
revoke all on function public.jl_dama_regulation_state(uuid) from public,anon,authenticated;
revoke all on function public.jl_dama_refund_room(uuid,text) from public,anon,authenticated;
revoke all on function public.jl_dama_finish_win(uuid,uuid,text) from public,anon,authenticated;
revoke all on function public.jl_dama_finish_draw(uuid,text) from public,anon,authenticated;
