
create extension if not exists pg_net with schema extensions;

create table if not exists public.player_notifications (
  id bigint generated by default as identity primary key,
  player_id uuid not null references public.players(id) on delete cascade,
  kind text not null default 'info',
  title text not null,
  message text not null default '',
  href text not null default '',
  source_key text,
  created_at timestamptz not null default now(),
  read_at timestamptz,
  dismissed_at timestamptz,
  push_attempted_at timestamptz,
  push_sent_at timestamptz
);

create unique index if not exists player_notifications_source_uidx
  on public.player_notifications(player_id, source_key)
  where source_key is not null;

create index if not exists player_notifications_player_created_idx
  on public.player_notifications(player_id, created_at desc)
  where dismissed_at is null;

alter table public.player_notifications enable row level security;
revoke all on table public.player_notifications from anon, authenticated;

create table if not exists public.player_follows (
  follower_id uuid not null references public.players(id) on delete cascade,
  followed_id uuid not null references public.players(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (follower_id, followed_id),
  constraint player_follows_not_self check (follower_id <> followed_id)
);

create index if not exists player_follows_followed_idx
  on public.player_follows(followed_id, created_at desc);

alter table public.player_follows enable row level security;
revoke all on table public.player_follows from anon, authenticated;

create table if not exists public.player_push_subscriptions (
  id uuid primary key default extensions.gen_random_uuid(),
  player_id uuid not null references public.players(id) on delete cascade,
  endpoint text not null unique,
  p256dh text not null,
  auth text not null,
  user_agent text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  last_success_at timestamptz,
  disabled_at timestamptz
);

create index if not exists player_push_subscriptions_player_idx
  on public.player_push_subscriptions(player_id)
  where disabled_at is null;

alter table public.player_push_subscriptions enable row level security;
revoke all on table public.player_push_subscriptions from anon, authenticated;

create index if not exists player_sessions_player_seen_idx
  on public.player_sessions(player_id, last_seen_at desc);

create or replace function public.jl_notification_create(
  p_player_id uuid,
  p_kind text,
  p_title text,
  p_message text default '',
  p_href text default '',
  p_source_key text default null
)
returns bigint
language plpgsql
security definer
set search_path to 'public'
as $$
declare
  v_id bigint;
  v_source text := nullif(trim(coalesce(p_source_key,'')),'');
begin
  if p_player_id is null or not exists(
    select 1 from public.players p
    where p.id=p_player_id and not p.blocked and p.deleted_at is null
  ) then
    return null;
  end if;

  if v_source is null then
    insert into public.player_notifications(player_id,kind,title,message,href)
    values(
      p_player_id,
      left(coalesce(nullif(trim(p_kind),''),'info'),60),
      left(coalesce(nullif(trim(p_title),''),'Notificação'),160),
      left(coalesce(p_message,''),700),
      left(coalesce(p_href,''),500)
    )
    returning id into v_id;
  else
    insert into public.player_notifications(player_id,kind,title,message,href,source_key)
    values(
      p_player_id,
      left(coalesce(nullif(trim(p_kind),''),'info'),60),
      left(coalesce(nullif(trim(p_title),''),'Notificação'),160),
      left(coalesce(p_message,''),700),
      left(coalesce(p_href,''),500),
      left(v_source,220)
    )
    on conflict (player_id, source_key) where source_key is not null
    do update set
      kind=excluded.kind,
      title=excluded.title,
      message=excluded.message,
      href=excluded.href
    returning id into v_id;
  end if;

  return v_id;
end;
$$;

revoke all on function public.jl_notification_create(uuid,text,text,text,text,text) from public, anon, authenticated;
grant execute on function public.jl_notification_create(uuid,text,text,text,text,text) to service_role;

create or replace function public.jl_notifications_feed(
  p_token text,
  p_limit integer default 80
)
returns jsonb
language plpgsql
security definer
set search_path to 'public'
as $$
declare
  me uuid := public.jl_player_id(p_token);
  lim integer := greatest(1,least(coalesce(p_limit,80),100));
  rows jsonb;
begin
  update public.player_sessions
  set last_seen_at=now()
  where token_hash=public.jl_token_hash(p_token)
    and expires_at>now();

  select coalesce(jsonb_agg(x order by x.created_at desc),'[]'::jsonb)
  into rows
  from (
    select
      coalesce(n.source_key,'server:'||n.id::text) as id,
      n.id as "serverId",
      n.kind as type,
      n.title,
      n.message,
      n.href,
      n.created_at as "createdAt",
      (n.read_at is not null) as read,
      true as "serverBacked"
    from public.player_notifications n
    where n.player_id=me
      and n.dismissed_at is null
    order by n.created_at desc
    limit lim
  ) x;

  return rows;
end;
$$;

create or replace function public.jl_notifications_mark_read(
  p_token text,
  p_notification_id bigint default null,
  p_source_key text default null,
  p_all boolean default false
)
returns jsonb
language plpgsql
security definer
set search_path to 'public'
as $$
declare
  me uuid := public.jl_player_id(p_token);
  changed integer := 0;
begin
  if coalesce(p_all,false) then
    update public.player_notifications
    set read_at=coalesce(read_at,now())
    where player_id=me and dismissed_at is null and read_at is null;
    get diagnostics changed=row_count;
  elsif p_notification_id is not null then
    update public.player_notifications
    set read_at=coalesce(read_at,now())
    where player_id=me and id=p_notification_id and dismissed_at is null;
    get diagnostics changed=row_count;
  elsif nullif(trim(coalesce(p_source_key,'')),'') is not null then
    update public.player_notifications
    set read_at=coalesce(read_at,now())
    where player_id=me and source_key=p_source_key and dismissed_at is null;
    get diagnostics changed=row_count;
  end if;
  return jsonb_build_object('ok',true,'changed',changed);
end;
$$;

create or replace function public.jl_notifications_clear(p_token text)
returns jsonb
language plpgsql
security definer
set search_path to 'public'
as $$
declare
  me uuid := public.jl_player_id(p_token);
  changed integer := 0;
begin
  update public.player_notifications
  set dismissed_at=now(), read_at=coalesce(read_at,now())
  where player_id=me and dismissed_at is null;
  get diagnostics changed=row_count;
  return jsonb_build_object('ok',true,'changed',changed);
end;
$$;

grant execute on function public.jl_notifications_feed(text,integer) to anon, authenticated;
grant execute on function public.jl_notifications_mark_read(text,bigint,text,boolean) to anon, authenticated;
grant execute on function public.jl_notifications_clear(text) to anon, authenticated;

create or replace function public.jl_social_list(p_token text)
returns jsonb
language plpgsql
security definer
set search_path to 'public'
as $$
declare
  me uuid := public.jl_player_id(p_token);
  rows jsonb;
  following_total integer;
  followers_total integer;
  online_total integer;
begin
  update public.player_sessions
  set last_seen_at=now()
  where token_hash=public.jl_token_hash(p_token)
    and expires_at>now();

  insert into public.ludo_player_codes(player_id)
  select p.id
  from public.players p
  where not p.blocked
    and p.deleted_at is null
    and not exists(select 1 from public.ludo_player_codes c where c.player_id=p.id)
  order by p.created_at,p.id
  on conflict(player_id) do nothing;

  select count(*) into following_total
  from public.player_follows
  where follower_id=me;

  select count(*) into followers_total
  from public.player_follows
  where followed_id=me;

  select count(*) into online_total
  from public.player_follows f
  where f.follower_id=me
    and exists(
      select 1
      from public.player_sessions s
      where s.player_id=f.followed_id
        and s.expires_at>now()
        and s.last_seen_at>=now()-interval '25 seconds'
    );

  select coalesce(jsonb_agg(x order by x.online desc, x.name, x.code),'[]'::jsonb)
  into rows
  from (
    select
      p.id as player_id,
      p.name,
      public.jl_ludo_display_code(p.id) as code,
      exists(
        select 1 from public.player_sessions s
        where s.player_id=p.id
          and s.expires_at>now()
          and s.last_seen_at>=now()-interval '25 seconds'
      ) as online,
      exists(
        select 1
        from public.ludo_room_players rp
        join public.ludo_rooms r on r.id=rp.room_id
        where rp.player_id=p.id
          and rp.status<>'left'
          and r.status in ('waiting','negotiating','funding','playing')
      ) as in_game,
      exists(
        select 1 from public.player_follows back
        where back.follower_id=p.id and back.followed_id=me
      ) as mutual,
      f.created_at as followed_at
    from public.player_follows f
    join public.players p on p.id=f.followed_id
    where f.follower_id=me
      and not p.blocked
      and p.deleted_at is null
  ) x;

  return jsonb_build_object(
    'following',rows,
    'following_count',following_total,
    'followers_count',followers_total,
    'online_count',online_total
  );
end;
$$;

create or replace function public.jl_social_find_players(
  p_token text,
  p_query text default ''
)
returns jsonb
language plpgsql
security definer
set search_path to 'public'
as $$
declare
  me uuid := public.jl_player_id(p_token);
  q text := trim(coalesce(p_query,''));
begin
  insert into public.ludo_player_codes(player_id)
  select p.id
  from public.players p
  where not p.blocked
    and p.deleted_at is null
    and not exists(select 1 from public.ludo_player_codes c where c.player_id=p.id)
  order by p.created_at,p.id
  on conflict(player_id) do nothing;

  return coalesce((
    select jsonb_agg(jsonb_build_object(
      'player_id',x.id,
      'name',x.name,
      'code',public.jl_ludo_display_code(x.id),
      'following',exists(
        select 1 from public.player_follows f
        where f.follower_id=me and f.followed_id=x.id
      ),
      'follows_you',exists(
        select 1 from public.player_follows f
        where f.follower_id=x.id and f.followed_id=me
      ),
      'online',exists(
        select 1 from public.player_sessions s
        where s.player_id=x.id
          and s.expires_at>now()
          and s.last_seen_at>=now()-interval '25 seconds'
      ),
      'in_game',exists(
        select 1
        from public.ludo_room_players rp
        join public.ludo_rooms r on r.id=rp.room_id
        where rp.player_id=x.id
          and rp.status<>'left'
          and r.status in ('waiting','negotiating','funding','playing')
      )
    ) order by x.name,public.jl_ludo_display_code(x.id))
    from (
      select p.id,p.name
      from public.players p
      where p.id<>me
        and not p.blocked
        and p.deleted_at is null
        and (
          q=''
          or p.name ilike '%'||q||'%'
          or public.jl_ludo_display_code(p.id) ilike '%'||q||'%'
        )
      order by p.name,p.created_at
      limit 40
    ) x
  ),'[]'::jsonb);
end;
$$;

create or replace function public.jl_social_follow(
  p_token text,
  p_target_player uuid,
  p_follow boolean default true
)
returns jsonb
language plpgsql
security definer
set search_path to 'public'
as $$
declare
  me uuid := public.jl_player_id(p_token);
  actor_name text;
  actor_code text;
  is_mutual boolean := false;
begin
  if p_target_player is null or p_target_player=me then
    raise exception 'Jogador inválido.';
  end if;

  if not exists(
    select 1 from public.players
    where id=p_target_player and not blocked and deleted_at is null
  ) then
    raise exception 'Jogador não encontrado.';
  end if;

  if coalesce(p_follow,true) then
    insert into public.player_follows(follower_id,followed_id)
    values(me,p_target_player)
    on conflict do nothing;

    select name into actor_name from public.players where id=me;
    perform public.jl_ludo_ensure_code(me);
    actor_code:=public.jl_ludo_display_code(me);

    perform public.jl_notification_create(
      p_target_player,
      'follow',
      actor_name||' começou a seguir você',
      actor_code||' adicionou você à lista de jogadores acompanhados.',
      './ludo.html#socialZone',
      'follow:'||me::text||':'||p_target_player::text
    );
  else
    delete from public.player_follows
    where follower_id=me and followed_id=p_target_player;
  end if;

  select exists(
    select 1 from public.player_follows
    where follower_id=p_target_player and followed_id=me
  ) into is_mutual;

  return jsonb_build_object(
    'ok',true,
    'following',coalesce(p_follow,true),
    'mutual',is_mutual
  );
end;
$$;

grant execute on function public.jl_social_list(text) to anon, authenticated;
grant execute on function public.jl_social_find_players(text,text) to anon, authenticated;
grant execute on function public.jl_social_follow(text,uuid,boolean) to anon, authenticated;

create or replace function public.jl_push_subscribe(
  p_token text,
  p_endpoint text,
  p_p256dh text,
  p_auth text,
  p_user_agent text default ''
)
returns jsonb
language plpgsql
security definer
set search_path to 'public'
as $$
declare
  me uuid := public.jl_player_id(p_token);
  v_id uuid;
begin
  if p_endpoint is null or length(p_endpoint) not between 20 and 2048 or p_endpoint !~ '^https://' then
    raise exception 'Subscrição push inválida.';
  end if;
  if p_p256dh is null or length(p_p256dh)<20 or p_auth is null or length(p_auth)<8 then
    raise exception 'Chaves push inválidas.';
  end if;

  insert into public.player_push_subscriptions(
    player_id,endpoint,p256dh,auth,user_agent,updated_at,disabled_at
  )
  values(
    me,left(p_endpoint,2048),left(p_p256dh,500),left(p_auth,500),
    left(coalesce(p_user_agent,''),300),now(),null
  )
  on conflict(endpoint) do update set
    player_id=excluded.player_id,
    p256dh=excluded.p256dh,
    auth=excluded.auth,
    user_agent=excluded.user_agent,
    updated_at=now(),
    disabled_at=null
  returning id into v_id;

  return jsonb_build_object('ok',true,'subscription_id',v_id);
end;
$$;

create or replace function public.jl_push_unsubscribe(
  p_token text,
  p_endpoint text
)
returns jsonb
language plpgsql
security definer
set search_path to 'public'
as $$
declare
  me uuid := public.jl_player_id(p_token);
  changed integer := 0;
begin
  update public.player_push_subscriptions
  set disabled_at=now(),updated_at=now()
  where player_id=me and endpoint=p_endpoint and disabled_at is null;
  get diagnostics changed=row_count;
  return jsonb_build_object('ok',true,'changed',changed);
end;
$$;

grant execute on function public.jl_push_subscribe(text,text,text,text,text) to anon, authenticated;
grant execute on function public.jl_push_unsubscribe(text,text) to anon, authenticated;

create or replace function public.jl_push_service_bundle(p_notification_id bigint)
returns jsonb
language plpgsql
security definer
set search_path to 'public','vault'
as $$
declare
  v_public text;
  v_private text;
  v_notice jsonb;
  v_subs jsonb;
begin
  select decrypted_secret into v_public
  from vault.decrypted_secrets
  where name='jl_web_push_vapid_public'
  order by created_at desc
  limit 1;

  select decrypted_secret into v_private
  from vault.decrypted_secrets
  where name='jl_web_push_vapid_private'
  order by created_at desc
  limit 1;

  select jsonb_build_object(
    'id',coalesce(n.source_key,'server:'||n.id::text),
    'serverId',n.id,
    'playerId',n.player_id,
    'title',n.title,
    'message',n.message,
    'href',n.href,
    'type',n.kind,
    'createdAt',n.created_at
  )
  into v_notice
  from public.player_notifications n
  where n.id=p_notification_id and n.dismissed_at is null;

  if v_notice is null then
    return null;
  end if;

  select coalesce(jsonb_agg(jsonb_build_object(
    'endpoint',s.endpoint,
    'keys',jsonb_build_object('p256dh',s.p256dh,'auth',s.auth)
  )),'[]'::jsonb)
  into v_subs
  from public.player_push_subscriptions s
  where s.player_id=(v_notice->>'playerId')::uuid
    and s.disabled_at is null;

  return jsonb_build_object(
    'vapid_public',v_public,
    'vapid_private',v_private,
    'notification',v_notice,
    'subscriptions',v_subs
  );
end;
$$;

create or replace function public.jl_push_dispatch_secret()
returns text
language sql
security definer
set search_path to 'vault'
as $$
  select decrypted_secret
  from vault.decrypted_secrets
  where name='jl_push_dispatch_secret'
  order by created_at desc
  limit 1;
$$;

create or replace function public.jl_push_mark_delivery(
  p_notification_id bigint,
  p_sent_count integer default 0,
  p_invalid_endpoints text[] default array[]::text[]
)
returns void
language plpgsql
security definer
set search_path to 'public'
as $$
begin
  update public.player_notifications
  set push_attempted_at=now(),
      push_sent_at=case when coalesce(p_sent_count,0)>0 then now() else push_sent_at end
  where id=p_notification_id;

  if coalesce(array_length(p_invalid_endpoints,1),0)>0 then
    update public.player_push_subscriptions
    set disabled_at=now(),updated_at=now()
    where endpoint=any(p_invalid_endpoints);
  end if;
end;
$$;

revoke all on function public.jl_push_service_bundle(bigint) from public, anon, authenticated;
revoke all on function public.jl_push_dispatch_secret() from public, anon, authenticated;
revoke all on function public.jl_push_mark_delivery(bigint,integer,text[]) from public, anon, authenticated;
grant execute on function public.jl_push_service_bundle(bigint) to service_role;
grant execute on function public.jl_push_dispatch_secret() to service_role;
grant execute on function public.jl_push_mark_delivery(bigint,integer,text[]) to service_role;

create or replace function public.jl_notify_ludo_invite()
returns trigger
language plpgsql
security definer
set search_path to 'public'
as $$
declare
  r public.ludo_rooms%rowtype;
  host_name text;
  host_code text;
begin
  if new.status<>'pending' then return new; end if;
  select * into r from public.ludo_rooms where id=new.room_id;
  select name into host_name from public.players where id=new.invited_by;
  host_code:=public.jl_ludo_display_code(new.invited_by);

  perform public.jl_notification_create(
    new.target_player_id,
    'ludo-invite',
    'Convite de '||coalesce(host_name,'jogador'),
    coalesce(r.code,'Ludo')||' · '||coalesce(r.player_count,0)||' jogadores · '||
      coalesce(r.mode,'solo')||' · '||coalesce(r.bet_amount,0)||' MZN',
    './ludo.html#notificationCenter',
    'ludo-invite:'||new.id::text
  );
  return new;
end;
$$;

drop trigger if exists trg_jl_notify_ludo_invite on public.ludo_invitations;
create trigger trg_jl_notify_ludo_invite
after insert on public.ludo_invitations
for each row execute function public.jl_notify_ludo_invite();

create or replace function public.jl_notify_support_reply()
returns trigger
language plpgsql
security definer
set search_path to 'public'
as $$
begin
  if new.sender='admin' then
    perform public.jl_notification_create(
      new.player_id,
      'support',
      'Nova resposta da Linha de Cliente',
      left(new.message,260),
      './index.html?open=support#playerArea',
      'support:'||new.id::text
    );
  end if;
  return new;
end;
$$;

drop trigger if exists trg_jl_notify_support_reply on public.customer_support_messages;
create trigger trg_jl_notify_support_reply
after insert on public.customer_support_messages
for each row execute function public.jl_notify_support_reply();

create or replace function public.jl_notify_deposit_status()
returns trigger
language plpgsql
security definer
set search_path to 'public'
as $$
begin
  if new.status='pending' then return new; end if;
  if tg_op='UPDATE' and old.status is not distinct from new.status then return new; end if;

  perform public.jl_notification_create(
    new.player_id,
    'finance',
    case when new.status='approved' then 'Depósito aprovado' else 'Depósito rejeitado' end,
    new.amount||' MZN · '||
      case when new.status='approved'
        then 'O valor foi creditado no seu saldo.'
        else 'O pedido de depósito não foi aprovado.'
      end,
    './index.html#depositPanel',
    'deposit-status:'||new.id::text||':'||new.status
  );
  return new;
end;
$$;

drop trigger if exists trg_jl_notify_deposit_status on public.deposit_requests;
create trigger trg_jl_notify_deposit_status
after insert or update of status on public.deposit_requests
for each row execute function public.jl_notify_deposit_status();

create or replace function public.jl_notify_withdrawal_status()
returns trigger
language plpgsql
security definer
set search_path to 'public'
as $$
begin
  if new.status='pending' then return new; end if;
  if tg_op='UPDATE' and old.status is not distinct from new.status then return new; end if;

  perform public.jl_notification_create(
    new.player_id,
    'finance',
    case when new.status='approved' then 'Saque aprovado' else 'Saque rejeitado' end,
    new.amount||' MZN · '||
      case when new.status='approved'
        then 'O saque foi aprovado.'
        else coalesce(nullif(new.reason,''),'O pedido de saque não foi aprovado.')
      end,
    './index.html#withdrawPanel',
    'withdraw-status:'||new.id::text||':'||new.status
  );
  return new;
end;
$$;

drop trigger if exists trg_jl_notify_withdrawal_status on public.withdrawal_requests;
create trigger trg_jl_notify_withdrawal_status
after insert or update of status on public.withdrawal_requests
for each row execute function public.jl_notify_withdrawal_status();

create or replace function public.jl_push_after_notification_insert()
returns trigger
language plpgsql
security definer
set search_path to 'public','vault','extensions'
as $$
declare
  dispatch_key text;
begin
  if not exists(
    select 1 from public.player_push_subscriptions s
    where s.player_id=new.player_id and s.disabled_at is null
  ) then
    return new;
  end if;

  select decrypted_secret into dispatch_key
  from vault.decrypted_secrets
  where name='jl_push_dispatch_secret'
  order by created_at desc
  limit 1;

  if coalesce(dispatch_key,'')='' then
    return new;
  end if;

  perform net.http_post(
    url:='https://bxndjyzghgrmkelshtdp.supabase.co/functions/v1/jogos-push/dispatch',
    headers:=jsonb_build_object(
      'Content-Type','application/json',
      'x-jl-push-secret',dispatch_key
    ),
    body:=jsonb_build_object('notification_id',new.id),
    timeout_milliseconds:=5000
  );

  return new;
end;
$$;

drop trigger if exists trg_jl_push_after_notification_insert on public.player_notifications;
create trigger trg_jl_push_after_notification_insert
after insert on public.player_notifications
for each row execute function public.jl_push_after_notification_insert();
