-- Superseded before deployment.
-- The real production hotfix is recorded in:
-- 20261003105616_aviator_fix_bank_alias_reopen_no_veto_metrics_zero.sql
-- Keep this migration intentionally empty so a future migration run cannot
-- reintroduce the older admin-state/reopen implementation.
