-- Aviator pontos 65 e 66:
-- observabilidade operacional + alarme administrativo de consistência financeira.

alter table public.jl_aviator_settings
  add column if not exists last_financial_check_at timestamptz,
  add column if not exists last_financial_check_ok boolean not null default false,
  add column if not exists last_financial_check_result jsonb not null default '{}'::jsonb;

create table if not exists public.jl_aviator_client_metrics (
  id bigint generated by default as identity primary key,
  player_id uuid not null references public.players(id) on delete cascade,
  operation text not null check (operation in ('BET','CASHOUT','RECONNECT')),
  duration_ms integer not null check (duration_ms between 0 and 60000),
  success boolean not null,
  error_code text,
  round_id bigint references public.jl_aviator_rounds(id) on delete set null,
  bet_id bigint references public.jl_aviator_bets(id) on delete set null,
  created_at timestamptz not null default clock_timestamp()
);

alter table public.jl_aviator_client_metrics enable row level security;
revoke all on table public.jl_aviator_client_metrics from public,anon,authenticated;
grant select,insert,update,delete on table public.jl_aviator_client_metrics to service_role;

create index if not exists jl_aviator_client_metrics_created_idx
  on public.jl_aviator_client_metrics(created_at desc);

create index if not exists jl_aviator_client_metrics_operation_created_idx
  on public.jl_aviator_client_metrics(operation,created_at desc);

create table if not exists public.jl_aviator_admin_alerts (
  id bigint generated by default as identity primary key,
  alert_key text not null unique,
  severity text not null check (severity in ('INFO','WARNING','CRITICAL')),
  title text not null,
  message text not null,
  details jsonb not null default '{}'::jsonb,
  first_seen_at timestamptz not null default clock_timestamp(),
  last_seen_at timestamptz not null default clock_timestamp(),
  seen_at timestamptz,
  resolved_at timestamptz
);

alter table public.jl_aviator_admin_alerts enable row level security;
revoke all on table public.jl_aviator_admin_alerts from public,anon,authenticated;
grant select,insert,update,delete on table public.jl_aviator_admin_alerts to service_role;

create index if not exists jl_aviator_admin_alerts_open_idx
  on public.jl_aviator_admin_alerts(severity,last_seen_at desc)
  where resolved_at is null;

create or replace function public.jl_aviator_record_client_metric(
  p_token text,
  p_operation text,
  p_duration_ms integer,
  p_success boolean,
  p_error_code text default null,
  p_round_id bigint default null,
  p_bet_id bigint default null
)
returns jsonb
language plpgsql
security definer
set search_path to 'pg_catalog','public'
as $function$
declare
  v_player uuid:=public.jl_player_id(p_token);
  v_operation text:=upper(btrim(coalesce(p_operation,'')));
begin
  if v_operation not in ('BET','CASHOUT','RECONNECT') then
    raise exception 'Operação de telemetria inválida.';
  end if;

  if p_duration_ms is null or p_duration_ms<0 or p_duration_ms>60000 then
    raise exception 'Latência de telemetria inválida.';
  end if;

  perform public.jl_rate_limit_enforce(
    'aviator_client_metric',
    v_player::text,
    60,60,240,300
  );

  insert into public.jl_aviator_client_metrics(
    player_id,operation,duration_ms,success,error_code,round_id,bet_id
  )
  values(
    v_player,
    v_operation,
    p_duration_ms,
    coalesce(p_success,false),
    nullif(left(btrim(coalesce(p_error_code,'')),80),''),
    p_round_id,
    p_bet_id
  );

  return jsonb_build_object('ok',true);
end;
$function$;

revoke all on function public.jl_aviator_record_client_metric(
  text,text,integer,boolean,text,bigint,bigint
) from public;
grant execute on function public.jl_aviator_record_client_metric(
  text,text,integer,boolean,text,bigint,bigint
) to anon,authenticated,service_role;

create or replace function public.jl_aviator_financial_consistency_snapshot()
returns jsonb
language plpgsql
security definer
set search_path to 'pg_catalog','public'
as $function$
declare
  v_bet_missing bigint:=0;
  v_payout_missing bigint:=0;
  v_refund_missing bigint:=0;
  v_unexpected_money bigint:=0;
  v_balance_mismatch bigint:=0;
  v_negative_balance bigint:=0;
  v_active_finalized bigint:=0;
  v_bank_balance_mismatch bigint:=0;
  v_stakes numeric:=0;
  v_bet_debits numeric:=0;
  v_payouts numeric:=0;
  v_payout_tx numeric:=0;
  v_refunds numeric:=0;
  v_refund_tx numeric:=0;
  v_ok boolean:=false;
begin
  select count(*)
    into v_bet_missing
  from public.jl_aviator_bets b
  where not exists(
    select 1
    from public.transactions t
    where t.aviator_bet_id=b.id
      and t.aviator_operation='BET'
      and t.kind='aviator_bet'
      and round(t.amount,2)=-round(b.stake,2)
      and t.status='completed'
  );

  select coalesce(sum(stake),0)
    into v_stakes
  from public.jl_aviator_bets;

  select coalesce(sum(-amount),0)
    into v_bet_debits
  from public.transactions
  where aviator_operation='BET'
    and kind='aviator_bet'
    and status='completed';

  select count(*)
    into v_payout_missing
  from public.jl_aviator_bets b
  where b.status='CASHED_OUT'
    and (
      b.payout_transaction_id is null
      or not exists(
        select 1
        from public.transactions t
        where t.id=b.payout_transaction_id
          and t.aviator_bet_id=b.id
          and t.aviator_operation='PAYOUT'
          and t.kind='aviator_payout'
          and round(t.amount,2)=round(b.payout,2)
          and t.status='completed'
      )
    );

  select coalesce(sum(payout),0)
    into v_payouts
  from public.jl_aviator_bets
  where status='CASHED_OUT';

  select coalesce(sum(amount),0)
    into v_payout_tx
  from public.transactions
  where aviator_operation='PAYOUT'
    and kind='aviator_payout'
    and status='completed';

  select count(*)
    into v_refund_missing
  from public.jl_aviator_bets b
  where b.status='REFUNDED'
    and (
      b.refund_transaction_id is null
      or not exists(
        select 1
        from public.transactions t
        where t.id=b.refund_transaction_id
          and t.aviator_bet_id=b.id
          and t.aviator_operation='REFUND'
          and t.kind='aviator_refund'
          and round(t.amount,2)=round(b.stake,2)
          and t.status='completed'
      )
    );

  select coalesce(sum(stake),0)
    into v_refunds
  from public.jl_aviator_bets
  where status='REFUNDED';

  select coalesce(sum(amount),0)
    into v_refund_tx
  from public.transactions
  where aviator_operation='REFUND'
    and kind='aviator_refund'
    and status='completed';

  select count(*)
    into v_unexpected_money
  from public.transactions t
  join public.jl_aviator_bets b on b.id=t.aviator_bet_id
  where
    (t.aviator_operation='PAYOUT' and b.status<>'CASHED_OUT')
    or (t.aviator_operation='REFUND' and b.status<>'REFUNDED')
    or (t.aviator_operation='BET' and round(t.amount,2)<>-round(b.stake,2));

  select count(*)
    into v_balance_mismatch
  from public.players p
  where round(p.balance,2)<>round(public.jl_player_ledger_balance(p.id),2);

  select count(*)
    into v_negative_balance
  from public.players
  where balance<0;

  select count(*)
    into v_active_finalized
  from public.jl_aviator_bets b
  join public.jl_aviator_rounds r on r.id=b.round_id
  where b.status='ACTIVE'
    and r.status in ('CANCELLED','SETTLED');

  select
    case
      when latest.id is null then 0
      when round(bank.balance,2)=round(latest.balance_after,2) then 0
      else 1
    end
  into v_bank_balance_mismatch
  from public.jl_aviator_bank bank
  left join lateral(
    select id,balance_after
    from public.jl_aviator_bank_ledger
    order by id desc
    limit 1
  ) latest on true
  where bank.id=true;

  v_bank_balance_mismatch:=coalesce(v_bank_balance_mismatch,0);

  v_ok:=
    v_bet_missing=0
    and v_payout_missing=0
    and v_refund_missing=0
    and v_unexpected_money=0
    and v_balance_mismatch=0
    and v_negative_balance=0
    and v_active_finalized=0
    and v_bank_balance_mismatch=0
    and round(v_stakes,2)=round(v_bet_debits,2)
    and round(v_payouts,2)=round(v_payout_tx,2)
    and round(v_refunds,2)=round(v_refund_tx,2);

  return jsonb_build_object(
    'ok',v_ok,
    'checked_at',clock_timestamp(),
    'counts',jsonb_build_object(
      'bet_transaction_mismatches',v_bet_missing,
      'payout_mismatches',v_payout_missing,
      'refund_mismatches',v_refund_missing,
      'unexpected_money_operations',v_unexpected_money,
      'player_balance_mismatches',v_balance_mismatch,
      'negative_player_balances',v_negative_balance,
      'active_bets_in_finalized_rounds',v_active_finalized,
      'aviator_bank_balance_mismatch',v_bank_balance_mismatch
    ),
    'totals',jsonb_build_object(
      'bet_stakes',round(v_stakes,2),
      'bet_debits',round(v_bet_debits,2),
      'payouts_recorded',round(v_payouts,2),
      'payout_transactions',round(v_payout_tx,2),
      'refunds_recorded',round(v_refunds,2),
      'refund_transactions',round(v_refund_tx,2)
    )
  );
end;
$function$;

revoke all on function public.jl_aviator_financial_consistency_snapshot()
from public,anon,authenticated;
grant execute on function public.jl_aviator_financial_consistency_snapshot()
to service_role;

create or replace function public.jl_aviator_financial_consistency_watch()
returns jsonb
language plpgsql
security definer
set search_path to 'pg_catalog','public'
as $function$
declare
  v_snapshot jsonb;
  v_ok boolean;
  v_had_open boolean:=false;
begin
  v_snapshot:=public.jl_aviator_financial_consistency_snapshot();
  v_ok:=coalesce((v_snapshot->>'ok')::boolean,false);

  update public.jl_aviator_settings
     set last_financial_check_at=clock_timestamp(),
         last_financial_check_ok=v_ok,
         last_financial_check_result=v_snapshot
   where id=true;

  select exists(
    select 1
    from public.jl_aviator_admin_alerts
    where alert_key='AVIATOR_FINANCIAL_MISMATCH'
      and resolved_at is null
  )
  into v_had_open;

  if not v_ok then
    update public.jl_aviator_settings
       set last_release_gate_passed=false
     where id=true
       and coalesce(last_release_gate_passed,false)=true;

    insert into public.jl_aviator_admin_alerts(
      alert_key,severity,title,message,details,first_seen_at,last_seen_at,resolved_at
    )
    values(
      'AVIATOR_FINANCIAL_MISMATCH',
      'CRITICAL',
      'Inconsistência financeira no Aviator',
      'Totais de apostas, débitos, pagamentos, reembolsos ou saldos não conferem.',
      v_snapshot,
      clock_timestamp(),
      clock_timestamp(),
      null
    )
    on conflict(alert_key) do update
      set severity='CRITICAL',
          title=excluded.title,
          message=excluded.message,
          details=excluded.details,
          last_seen_at=clock_timestamp(),
          resolved_at=null;

    if not v_had_open then
      insert into public.audit_log(action,details,target_type,target_id)
      values(
        'aviator.financial_inconsistency_detected',
        v_snapshot,
        'aviator_finance',
        'global'
      );
    end if;
  else
    update public.jl_aviator_admin_alerts
       set last_seen_at=clock_timestamp(),
           resolved_at=coalesce(resolved_at,clock_timestamp())
     where alert_key='AVIATOR_FINANCIAL_MISMATCH'
       and resolved_at is null;
  end if;

  return v_snapshot;
end;
$function$;

revoke all on function public.jl_aviator_financial_consistency_watch()
from public,anon,authenticated;
grant execute on function public.jl_aviator_financial_consistency_watch()
to service_role;

create or replace function public.jl_aviator_admin_observability(p_token text)
returns jsonb
language plpgsql
security definer
set search_path to 'pg_catalog','public'
as $function$
declare
  v_round_duration_ms numeric:=0;
  v_avg_round_duration_ms numeric:=0;
  v_bets_60 bigint:=0;
  v_cashouts_60 bigint:=0;
  v_bet_failures_15 bigint:=0;
  v_cashout_failures_15 bigint:=0;
  v_reconnect_failures_15 bigint:=0;
  v_payment_failures_15 bigint:=0;
  v_bet_p95 numeric:=0;
  v_cashout_p95 numeric:=0;
  v_reconnect_p95 numeric:=0;
  v_consistency jsonb;
  v_last_financial_check_at timestamptz;
  v_alerts jsonb:='[]'::jsonb;
begin
  perform public.jl_require_admin(p_token);

  select coalesce(
    extract(epoch from (
      coalesce(settled_at,crashed_at,clock_timestamp())-opened_at
    ))*1000,
    0
  )
  into v_round_duration_ms
  from public.jl_aviator_rounds
  order by id desc
  limit 1;

  select coalesce(avg(
    extract(epoch from (coalesce(settled_at,crashed_at)-opened_at))*1000
  ),0)
  into v_avg_round_duration_ms
  from public.jl_aviator_rounds
  where coalesce(settled_at,crashed_at) is not null
    and opened_at>=clock_timestamp()-interval '15 minutes';

  select count(*) into v_bets_60
  from public.jl_aviator_bets
  where created_at>=clock_timestamp()-interval '60 seconds';

  select count(*) into v_cashouts_60
  from public.jl_aviator_bets
  where status='CASHED_OUT'
    and cashed_out_at>=clock_timestamp()-interval '60 seconds';

  select
    count(*) filter(where operation='BET' and not success),
    count(*) filter(where operation='CASHOUT' and not success),
    count(*) filter(where operation='RECONNECT' and not success),
    count(*) filter(
      where operation='CASHOUT'
        and not success
        and coalesce(error_code,'') not in (
          'ROUND_CRASHED',
          'BET_SETTLED',
          'FLIGHT_INACTIVE',
          'BOT_RATE_LIMITED',
          'BOT_TOO_FAST',
          'RATE_LIMITED',
          'AUTH_INVALID'
        )
    )
  into
    v_bet_failures_15,
    v_cashout_failures_15,
    v_reconnect_failures_15,
    v_payment_failures_15
  from public.jl_aviator_client_metrics
  where created_at>=clock_timestamp()-interval '15 minutes';

  select
    coalesce(percentile_cont(.95) within group(order by duration_ms)
      filter(where operation='BET' and success),0),
    coalesce(percentile_cont(.95) within group(order by duration_ms)
      filter(where operation='CASHOUT' and success),0),
    coalesce(percentile_cont(.95) within group(order by duration_ms)
      filter(where operation='RECONNECT' and success),0)
  into v_bet_p95,v_cashout_p95,v_reconnect_p95
  from public.jl_aviator_client_metrics
  where created_at>=clock_timestamp()-interval '15 minutes';

  select last_financial_check_at,last_financial_check_result
    into v_last_financial_check_at,v_consistency
  from public.jl_aviator_settings
  where id=true;

  if v_last_financial_check_at is null
     or v_last_financial_check_at<clock_timestamp()-interval '30 seconds'
     or v_consistency is null
     or v_consistency='{}'::jsonb then
    v_consistency:=public.jl_aviator_financial_consistency_watch();
  end if;

  select coalesce(jsonb_agg(jsonb_build_object(
    'id',id,
    'severity',severity,
    'title',title,
    'message',message,
    'details',details,
    'first_seen_at',first_seen_at,
    'last_seen_at',last_seen_at
  ) order by last_seen_at desc),'[]'::jsonb)
  into v_alerts
  from public.jl_aviator_admin_alerts
  where resolved_at is null;

  return jsonb_build_object(
    'round',jsonb_build_object(
      'latest_duration_ms',round(v_round_duration_ms),
      'avg_duration_ms_15m',round(v_avg_round_duration_ms)
    ),
    'throughput',jsonb_build_object(
      'bets_last_60s',v_bets_60,
      'bets_per_second_60s',round(v_bets_60/60.0,2),
      'cashouts_last_60s',v_cashouts_60,
      'cashouts_per_second_60s',round(v_cashouts_60/60.0,2)
    ),
    'latency_p95_ms_15m',jsonb_build_object(
      'bet',round(v_bet_p95),
      'cashout',round(v_cashout_p95),
      'reconnect',round(v_reconnect_p95)
    ),
    'failures_15m',jsonb_build_object(
      'bet',v_bet_failures_15,
      'cashout',v_cashout_failures_15,
      'reconnect',v_reconnect_failures_15,
      'payment',v_payment_failures_15+
        coalesce((v_consistency->'counts'->>'payout_mismatches')::bigint,0)+
        coalesce((v_consistency->'counts'->>'refund_mismatches')::bigint,0)+
        coalesce((v_consistency->'counts'->>'unexpected_money_operations')::bigint,0)+
        coalesce((v_consistency->'counts'->>'aviator_bank_balance_mismatch')::bigint,0)
    ),
    'financial_consistency',v_consistency,
    'alerts',v_alerts,
    'updated_at',clock_timestamp()
  );
end;
$function$;

revoke all on function public.jl_aviator_admin_observability(text) from public;
grant execute on function public.jl_aviator_admin_observability(text)
to anon,authenticated,service_role;

do $cron$
declare
  v_jobid bigint;
begin
  select jobid into v_jobid
  from cron.job
  where jobname='aviator_financial_consistency_watch'
  limit 1;

  if v_jobid is not null then
    perform cron.unschedule(v_jobid);
  end if;

  perform cron.schedule(
    'aviator_financial_consistency_watch',
    '* * * * *',
    'select public.jl_aviator_financial_consistency_watch();'
  );
end
$cron$;
