alter table public.free_access_memberships
  add column if not exists valid_until timestamptz;

update public.free_access_memberships
set valid_until = coalesce(valid_until, greatest(activated_at, now()) + interval '1 month')
where active and valid_until is null;

alter table public.free_access_requests
  add column if not exists months integer not null default 1,
  add column if not exists unit_price numeric(18,2);

update public.free_access_requests
set unit_price = coalesce(unit_price, case when months > 0 then round(amount / months,2) else amount end)
where unit_price is null;

do $$ begin
  alter table public.free_access_requests
    add constraint free_access_requests_months_ck check (months between 1 and 120);
exception when duplicate_object then null; end $$;

create table if not exists public.free_game_catalog (
  game_key text primary key,
  label text not null,
  free_enabled boolean not null default false,
  bet_enabled boolean not null default true,
  trial_limit integer not null default 10 check (trial_limit between 0 and 1000),
  sort_order integer not null default 100,
  updated_at timestamptz not null default now(),
  check (game_key ~ '^[a-z0-9_-]+$')
);

insert into public.free_game_catalog(game_key,label,free_enabled,bet_enabled,trial_limit,sort_order)
values
  ('ludo','Ludo Lendário',true,true,10,10),
  ('dama','Dama Lendária',true,true,10,20)
on conflict(game_key) do update set
  label=excluded.label,
  free_enabled=excluded.free_enabled,
  bet_enabled=excluded.bet_enabled,
  trial_limit=excluded.trial_limit,
  sort_order=excluded.sort_order,
  updated_at=now();

create table if not exists public.free_trial_usage (
  id bigint generated by default as identity primary key,
  player_id uuid not null references public.players(id) on delete cascade,
  game_key text not null references public.free_game_catalog(game_key),
  room_id uuid not null,
  used_at timestamptz not null default now(),
  unique(player_id,game_key,room_id)
);

create index if not exists free_trial_usage_player_game_idx
  on public.free_trial_usage(player_id,game_key,used_at desc);

alter table public.free_game_catalog enable row level security;
alter table public.free_trial_usage enable row level security;
revoke all on public.free_game_catalog from anon, authenticated;
revoke all on public.free_trial_usage from anon, authenticated;

create or replace function public.jl_free_access_active(p_player uuid)
returns boolean
language sql
stable
security definer
set search_path='pg_catalog','public'
as $$
  select coalesce((
    select m.active and m.valid_until is not null and m.valid_until > now()
    from public.free_access_memberships m
    where m.player_id=p_player
  ),false);
$$;

create or replace function public.jl_free_game_public_config(p_game text)
returns jsonb
language sql
stable
security definer
set search_path='pg_catalog','public'
as $$
  select coalesce((
    select jsonb_build_object(
      'game_key',g.game_key,
      'label',g.label,
      'free_enabled',g.free_enabled,
      'bet_enabled',g.bet_enabled,
      'trial_limit',g.trial_limit
    )
    from public.free_game_catalog g
    where g.game_key=lower(trim(p_game))
  ),jsonb_build_object(
    'game_key',lower(trim(coalesce(p_game,''))),
    'free_enabled',false,
    'bet_enabled',true,
    'trial_limit',0
  ));
$$;

create or replace function public.jl_free_game_status(p_player uuid,p_game text)
returns jsonb
language plpgsql
stable
security definer
set search_path='pg_catalog','public'
as $$
declare
  g public.free_game_catalog%rowtype;
  s public.free_access_settings%rowtype;
  used_count integer:=0;
  paid boolean:=false;
  expiry timestamptz;
begin
  select * into s from public.free_access_settings where id=1;
  select * into g from public.free_game_catalog where game_key=lower(trim(p_game));
  if g.game_key is null then
    return jsonb_build_object(
      'game_key',lower(trim(coalesce(p_game,''))),
      'free_enabled',false,'bet_enabled',true,'trial_limit',0,
      'used',0,'remaining_trials',0,'paid_active',false,'eligible',false
    );
  end if;

  select count(*)::integer into used_count
  from public.free_trial_usage u
  where u.player_id=p_player and u.game_key=g.game_key;

  paid:=public.jl_free_access_active(p_player);
  select m.valid_until into expiry
  from public.free_access_memberships m
  where m.player_id=p_player;

  return jsonb_build_object(
    'game_key',g.game_key,
    'label',g.label,
    'free_enabled',g.free_enabled,
    'bet_enabled',g.bet_enabled,
    'trial_limit',g.trial_limit,
    'used',used_count,
    'remaining_trials',greatest(0,g.trial_limit-used_count),
    'paid_active',paid,
    'valid_until',expiry,
    'eligible',coalesce(s.enabled,false) and g.free_enabled and (paid or used_count<g.trial_limit),
    'payment_required',coalesce(s.enabled,false) and g.free_enabled and not paid and used_count>=g.trial_limit
  );
end;
$$;

create or replace function public.jl_free_game_require(p_player uuid,p_game text)
returns void
language plpgsql
security definer
set search_path='pg_catalog','public'
as $$
declare st jsonb;
begin
  st:=public.jl_free_game_status(p_player,p_game);
  if not coalesce((st->>'free_enabled')::boolean,false) then
    raise exception 'FREE indisponível para este jogo.';
  end if;
  if not coalesce((st->>'eligible')::boolean,false) then
    raise exception 'Limite FREE atingido.';
  end if;
end;
$$;

create or replace function public.jl_free_access_require(p_player uuid)
returns void
language plpgsql
security definer
set search_path='pg_catalog','public'
as $$
begin
  if not coalesce((select s.enabled from public.free_access_settings s where s.id=1),false) then
    raise exception 'FREE indisponível.';
  end if;
end;
$$;

create or replace function public.jl_free_access_status(p_token text)
returns jsonb
language plpgsql
security definer
set search_path='pg_catalog','public'
as $$
declare
  me uuid:=public.jl_player_id(p_token);
  s public.free_access_settings%rowtype;
  req public.free_access_requests%rowtype;
  mem public.free_access_memberships%rowtype;
  paid boolean:=false;
  games jsonb:='[]'::jsonb;
begin
  select * into s from public.free_access_settings where id=1;
  select * into mem from public.free_access_memberships where player_id=me;
  paid:=public.jl_free_access_active(me);
  select * into req from public.free_access_requests
  where player_id=me and status='pending'
  order by requested_at desc limit 1;

  select coalesce(jsonb_agg(public.jl_free_game_status(me,g.game_key) order by g.sort_order,g.game_key),'[]'::jsonb)
  into games
  from public.free_game_catalog g;

  return jsonb_build_object(
    'enabled',coalesce(s.enabled,false),
    'price',coalesce(s.price,10),
    'price_period','month',
    'active',paid,
    'member_active',coalesce(mem.active,false),
    'valid_until',mem.valid_until,
    'status',case when req.id is not null then 'pending' when paid then 'active' else 'trial' end,
    'request_id',req.id,
    'pending_months',req.months,
    'pending_amount',req.amount,
    'requested_at',req.requested_at,
    'balance',public.jl_player_ledger_balance(me),
    'games',games
  );
end;
$$;

create or replace function public.jl_free_access_request(p_token text,p_months integer)
returns jsonb
language plpgsql
security definer
set search_path='pg_catalog','public','extensions'
as $$
declare
  me uuid:=public.jl_player_id(p_token);
  s public.free_access_settings%rowtype;
  rid uuid:=extensions.gen_random_uuid();
  ledger_balance numeric;
  wallet_balance numeric;
  total numeric;
begin
  if p_months is null or p_months not between 1 and 120 then
    raise exception 'Quantidade de meses inválida.';
  end if;
  select * into s from public.free_access_settings where id=1 for update;
  if not coalesce(s.enabled,false) then raise exception 'FREE indisponível.'; end if;
  if exists(select 1 from public.free_access_requests where player_id=me and status='pending') then
    return public.jl_free_access_status(p_token);
  end if;

  total:=round(s.price*p_months,2);
  if total>0 then
    perform public.jl_lock_player_wallet(me);
    ledger_balance:=public.jl_player_ledger_balance(me);
    select balance into wallet_balance from public.players where id=me for update;
    if coalesce(ledger_balance,0)<total or coalesce(wallet_balance,0)<total then
      raise exception 'Saldo insuficiente.';
    end if;
  end if;

  insert into public.free_access_requests(id,player_id,amount,status,months,unit_price)
  values(rid,me,total,'pending',p_months,s.price);

  if total>0 then
    update public.players set balance=round(balance-total,2),updated_at=now() where id=me;
    insert into public.transactions(player_id,kind,amount,status,reference_id,note)
    values(me,'free_access_payment',-total,'completed',rid,
      'FREE · '||p_months||case when p_months=1 then ' mês' else ' meses' end||' · pendente de aprovação');
  end if;

  return public.jl_free_access_status(p_token);
end;
$$;

create or replace function public.jl_free_access_request(p_token text)
returns jsonb
language sql
security definer
set search_path='pg_catalog','public'
as $$
  select public.jl_free_access_request(p_token,1);
$$;

create or replace function public.jl_admin_free_access_overview(p_token text)
returns jsonb
language plpgsql
security definer
set search_path='pg_catalog','public'
as $$
declare s public.free_access_settings%rowtype;
begin
  perform public.jl_require_admin_elevated(p_token);
  select * into s from public.free_access_settings where id=1;
  return jsonb_build_object(
    'settings',jsonb_build_object('enabled',s.enabled,'price',s.price,'updated_at',s.updated_at),
    'games',coalesce((
      select jsonb_agg(jsonb_build_object(
        'game_key',g.game_key,'label',g.label,'free_enabled',g.free_enabled,
        'bet_enabled',g.bet_enabled,'trial_limit',g.trial_limit
      ) order by g.sort_order,g.game_key)
      from public.free_game_catalog g
    ),'[]'::jsonb),
    'pending',coalesce((
      select jsonb_agg(jsonb_build_object(
        'id',r.id,'player_id',r.player_id,'name',p.name,'phone',p.phone,
        'amount',r.amount,'months',r.months,'unit_price',r.unit_price,
        'status',r.status,'requested_at',r.requested_at
      ) order by r.requested_at)
      from public.free_access_requests r join public.players p on p.id=r.player_id
      where r.status='pending'
    ),'[]'::jsonb),
    'members',coalesce((
      select jsonb_agg(jsonb_build_object(
        'player_id',m.player_id,'name',p.name,'phone',p.phone,
        'active',m.active,'paid_active',public.jl_free_access_active(m.player_id),
        'amount_paid',m.amount_paid,'activated_at',m.activated_at,'valid_until',m.valid_until
      ) order by m.updated_at desc)
      from public.free_access_memberships m join public.players p on p.id=m.player_id
    ),'[]'::jsonb)
  );
end;
$$;

create or replace function public.jl_admin_free_access_review(p_token text,p_request_id uuid,p_decision text)
returns jsonb
language plpgsql
security definer
set search_path='pg_catalog','public'
as $$
declare
  req public.free_access_requests%rowtype;
  mem public.free_access_memberships%rowtype;
  admin_id uuid;
  base_until timestamptz;
  next_until timestamptz;
begin
  perform public.jl_require_admin_elevated(p_token);
  admin_id:=public.jl_admin_account_id(p_token);
  if p_decision not in ('approved','rejected') then raise exception 'Decisão inválida.'; end if;

  select * into req from public.free_access_requests where id=p_request_id for update;
  if req.id is null or req.status<>'pending' then raise exception 'Pedido indisponível.'; end if;

  update public.free_access_requests
  set status=p_decision,reviewed_at=now(),reviewed_by=admin_id
  where id=req.id;

  if p_decision='approved' then
    select * into mem from public.free_access_memberships where player_id=req.player_id for update;
    base_until:=greatest(coalesce(mem.valid_until,now()),now());
    next_until:=base_until+make_interval(months=>coalesce(req.months,1));
    if mem.player_id is null then
      insert into public.free_access_memberships(
        player_id,active,amount_paid,request_id,activated_at,updated_at,valid_until
      ) values(req.player_id,true,req.amount,req.id,now(),now(),next_until);
    else
      update public.free_access_memberships
      set active=true,
          amount_paid=round(amount_paid+req.amount,2),
          request_id=req.id,
          valid_until=next_until,
          updated_at=now()
      where player_id=req.player_id;
    end if;
  elsif req.amount>0 then
    perform public.jl_lock_player_wallet(req.player_id);
    update public.players set balance=round(balance+req.amount,2),updated_at=now() where id=req.player_id;
    insert into public.transactions(player_id,kind,amount,status,reference_id,note)
    values(req.player_id,'free_access_refund',req.amount,'completed',req.id,'FREE · pagamento devolvido');
    update public.free_access_requests set refunded_at=now() where id=req.id;
  end if;

  return public.jl_admin_free_access_overview(p_token);
end;
$$;

create or replace function public.jl_admin_free_game_settings(
  p_token text,p_game text,p_free_enabled boolean,p_bet_enabled boolean,p_trial_limit integer
)
returns jsonb
language plpgsql
security definer
set search_path='pg_catalog','public'
as $$
begin
  perform public.jl_require_admin_elevated(p_token);
  if p_trial_limit is null or p_trial_limit not between 0 and 1000 then raise exception 'Limite inválido.'; end if;
  update public.free_game_catalog
  set free_enabled=coalesce(p_free_enabled,false),
      bet_enabled=coalesce(p_bet_enabled,true),
      trial_limit=p_trial_limit,
      updated_at=now()
  where game_key=lower(trim(p_game));
  if not found then raise exception 'Jogo não encontrado.'; end if;
  return public.jl_admin_free_access_overview(p_token);
end;
$$;

create or replace function public.jl_free_room_player_guard()
returns trigger
language plpgsql
security definer
set search_path='pg_catalog','public'
as $$
declare pm text; game_name text;
begin
  if tg_table_name='ludo_room_players' then
    select play_mode into pm from public.ludo_rooms where id=new.room_id;
    game_name:='ludo';
  else
    select play_mode into pm from public.dama_rooms where id=new.room_id;
    game_name:='dama';
  end if;
  if pm='free' then perform public.jl_free_game_require(new.player_id,game_name); end if;
  return new;
end;
$$;

create or replace function public.jl_free_usage_on_room_start()
returns trigger
language plpgsql
security definer
set search_path='pg_catalog','public'
as $$
declare x record; game_name text;
begin
  if new.play_mode<>'free' then return new; end if;
  if tg_table_name='ludo_rooms' then
    if new.status<>'playing' or old.status='playing' then return new; end if;
    game_name:='ludo';
    for x in select player_id from public.ludo_room_players where room_id=new.id and status<>'left' loop
      perform public.jl_free_game_require(x.player_id,game_name);
      if not public.jl_free_access_active(x.player_id) then
        insert into public.free_trial_usage(player_id,game_key,room_id)
        values(x.player_id,game_name,new.id) on conflict do nothing;
      end if;
    end loop;
  elsif tg_table_name='dama_rooms' then
    if new.status<>'ready' or old.status='ready' then return new; end if;
    game_name:='dama';
    for x in select player_id from public.dama_room_players where room_id=new.id and status<>'left' loop
      perform public.jl_free_game_require(x.player_id,game_name);
      if not public.jl_free_access_active(x.player_id) then
        insert into public.free_trial_usage(player_id,game_key,room_id)
        values(x.player_id,game_name,new.id) on conflict do nothing;
      end if;
    end loop;
  end if;
  return new;
end;
$$;

drop trigger if exists jl_free_usage_ludo_start on public.ludo_rooms;
create trigger jl_free_usage_ludo_start
before update of status on public.ludo_rooms
for each row execute function public.jl_free_usage_on_room_start();

drop trigger if exists jl_free_usage_dama_start on public.dama_rooms;
create trigger jl_free_usage_dama_start
before update of status on public.dama_rooms
for each row execute function public.jl_free_usage_on_room_start();

create or replace function public.jl_ludo_accept_rules(p_token text,p_room uuid,p_accept boolean)
returns jsonb
language plpgsql
security definer
set search_path='public'
as $$
declare
  me uuid:=public.jl_player_id(p_token);
  r public.ludo_rooms%rowtype;
  c int;
  a int;
begin
  select * into r from public.ludo_rooms where id=p_room for update;
  if r.id is null or r.status not in ('waiting','negotiating') or not public.jl_ludo_is_member(p_room,me) then
    raise exception 'Sala indisponível.';
  end if;
  if r.play_mode='free' then perform public.jl_free_access_require(me); end if;

  if not p_accept then
    update public.ludo_room_players set accepted_rules_version=null where room_id=p_room and player_id=me;
    perform public.jl_ludo_event(p_room,me,'rules_declined',jsonb_build_object('version',r.rules_version));
    return public.jl_ludo_room_state(p_token,p_room);
  end if;

  update public.ludo_room_players
  set accepted_rules_version=r.rules_version
  where room_id=p_room and player_id=me and status<>'left';
  perform public.jl_ludo_event(p_room,me,'rules_accepted',jsonb_build_object('version',r.rules_version,'no_deadline',true));

  select count(*),count(*) filter(where accepted_rules_version=r.rules_version)
  into c,a from public.ludo_room_players where room_id=p_room and status<>'left';

  if c=r.player_count and a=c then
    if r.play_mode='free' then
      update public.ludo_room_players set stake_paid=true,stake_amount=0 where room_id=p_room and status<>'left';
      update public.ludo_rooms set status='funding',action_deadline=null,negotiation_grace_used=false,updated_at=now() where id=p_room;
      perform public.jl_ludo_start_game(p_room);
    else
      update public.ludo_rooms
      set status='funding',action_deadline=now()+make_interval(secs=>(rules->>'stake_seconds')::int),
          negotiation_grace_used=false,updated_at=now()
      where id=p_room;
    end if;
    perform public.jl_ludo_event(p_room,me,'rules_unanimous',jsonb_build_object('version',r.rules_version,'free',r.play_mode='free'));
  end if;
  return public.jl_ludo_room_state(p_token,p_room);
end;
$$;

create or replace function public.jl_dama_accept_settings(p_token text,p_room uuid,p_accept boolean default true)
returns jsonb
language plpgsql
security definer
set search_path='public'
as $$
declare
  me uuid:=public.jl_player_id(p_token);
  r public.dama_rooms%rowtype;
  rp public.dama_room_players%rowtype;
  firstp uuid;
begin
  select * into r from public.dama_rooms where id=p_room for update;
  select * into rp from public.dama_room_players
  where room_id=p_room and player_id=me and status<>'left' for update;
  if r.id is null or rp.player_id is null or r.status<>'negotiating' then raise exception 'Partida indisponível para aceitação.'; end if;
  if r.play_mode='free' then perform public.jl_free_access_require(me); end if;
  if me=r.host_id then return public.jl_dama_room_state(p_token,p_room); end if;

  if not coalesce(p_accept,true) then
    delete from public.dama_room_players where room_id=p_room and player_id=me;
    update public.dama_rooms set guest_id=null,status='waiting',updated_at=now() where id=p_room;
    perform public.jl_dama_event(p_room,me,'settings_declined','{}'::jsonb);
    return jsonb_build_object('ok',true,'accepted',false);
  end if;

  update public.dama_room_players set settings_accepted=true where room_id=p_room and player_id=me;

  if r.play_mode='free' then
    perform public.jl_free_game_require(r.host_id,'dama');
    perform public.jl_free_game_require(me,'dama');
    update public.dama_room_players set stake_paid=true,stake_amount=0 where room_id=p_room and status<>'left';
    perform public.jl_dama_init_board(p_room);
    firstp:=case r.first_player_choice when 'host' then r.host_id else r.guest_id end;
    update public.dama_rooms
    set status='ready',current_player_id=firstp,started_at=null,action_deadline=null,
        board_version=0,move_seq=0,quiet_king_moves=0,regulation_key=null,
        regulation_moves=0,regulation_limit=0,pot=0,updated_at=now()
    where id=p_room;
    perform public.jl_dama_event(p_room,firstp,'game_ready',jsonb_build_object('first_player',firstp,'timer_starts_after_first_move',true,'free',true));
    insert into public.dama_positions(room_id,position_key,occurrences)
    values(p_room,public.jl_dama_position_key(p_room,firstp),1)
    on conflict(room_id,position_key) do update
    set occurrences=public.dama_positions.occurrences+1,updated_at=now();
  else
    update public.dama_rooms set status='funding',updated_at=now() where id=p_room;
    perform public.jl_dama_event(p_room,me,'settings_accepted',jsonb_build_object(
      'bet_amount',r.bet_amount,'turn_seconds',r.turn_seconds,
      'host_color',r.host_color,'first_player',r.first_player_choice
    ));
  end if;
  return public.jl_dama_room_state(p_token,p_room);
end;
$$;

revoke all on function public.jl_free_game_status(uuid,text) from public,anon,authenticated;
revoke all on function public.jl_free_game_require(uuid,text) from public,anon,authenticated;
revoke all on function public.jl_free_usage_on_room_start() from public,anon,authenticated;

grant execute on function public.jl_free_game_public_config(text) to anon,authenticated;
grant execute on function public.jl_free_access_status(text) to anon,authenticated;
grant execute on function public.jl_free_access_request(text) to anon,authenticated;
grant execute on function public.jl_free_access_request(text,integer) to anon,authenticated;
grant execute on function public.jl_admin_free_access_overview(text) to anon,authenticated;
grant execute on function public.jl_admin_free_access_review(text,uuid,text) to anon,authenticated;
grant execute on function public.jl_admin_free_access_settings(text,numeric,boolean) to anon,authenticated;
grant execute on function public.jl_admin_free_access_set_player(text,uuid,boolean) to anon,authenticated;
grant execute on function public.jl_admin_free_game_settings(text,text,boolean,boolean,integer) to anon,authenticated;
